(function(root,factory){const model=factory();if(typeof module!=="undefined"&&module.exports)module.exports=model;if(root)root.BohrHydrogenModel=model})(typeof window!=="undefined"?window:globalThis,function(){
  const H=6.62607015e-34,C=299792458,E_CHARGE=1.602176634e-19,GROUND_ENERGY_EV=13.6,BOHR_RADIUS_M=5.29177210903e-11,HC_EV_NM=H*C/E_CHARGE*1e9;
  function clampLevel(level,max=8){return Math.max(1,Math.min(max,Math.round(Number(level))))}
  function levelState(level){const n=clampLevel(level);return{n,energyEv:-GROUND_ENERGY_EV/(n*n),radiusM:BOHR_RADIUS_M*n*n,radiusPm:BOHR_RADIUS_M*n*n*1e12,ionizationEnergyEv:GROUND_ENERGY_EV/(n*n)}}
  function transition(initialLevel,finalLevel){const initial=levelState(initialLevel),final=levelState(finalLevel),signedDeltaEv=final.energyEv-initial.energyEv,photonEnergyEv=Math.abs(signedDeltaEv),type=signedDeltaEv>0?"absorption":signedDeltaEv<0?"emission":"none",frequencyHz=photonEnergyEv?photonEnergyEv*E_CHARGE/H:0,wavelengthNm=photonEnergyEv?HC_EV_NM/photonEnergyEv:Infinity;return{initial,final,type,signedDeltaEv,photonEnergyEv,frequencyHz,wavelengthNm,series:final.n===1&&type==="emission"?"Lyman":final.n===2&&type==="emission"?"Balmer":final.n===3&&type==="emission"?"Paschen":"other",visible:wavelengthNm>=380&&wavelengthNm<=750,energyResidualEv:type==="none"?0:photonEnergyEv-Math.abs(final.energyEv-initial.energyEv)}}
  function probeAbsorption(initialLevel,wavelengthNm,maxLevel=6,toleranceEv=.025){const initial=levelState(initialLevel),wavelength=Math.max(1e-9,Number(wavelengthNm)),photonEnergyEv=HC_EV_NM/wavelength;let best=null;for(let target=initial.n+1;target<=maxLevel;target++){const candidate=transition(initial.n,target),mismatchEv=photonEnergyEv-candidate.photonEnergyEv;if(!best||Math.abs(mismatchEv)<Math.abs(best.mismatchEv))best={...candidate,targetLevel:target,mismatchEv}}const resonant=Boolean(best&&Math.abs(best.mismatchEv)<=toleranceEv);return{initial,wavelengthNm:wavelength,photonEnergyEv,resonant,targetLevel:resonant?best.targetLevel:null,nearestTargetLevel:best?.targetLevel??null,nearestEnergyEv:best?.photonEnergyEv??null,mismatchEv:best?.mismatchEv??null,toleranceEv}}
  function spectralSeries(finalLevel=2,maxInitial=8){const target=clampLevel(finalLevel,maxInitial-1);const lines=[];for(let initial=maxInitial;initial>target;initial--)lines.push(transition(initial,target));return lines.sort((a,b)=>a.wavelengthNm-b.wavelengthNm)}
  return{H,C,E_CHARGE,GROUND_ENERGY_EV,BOHR_RADIUS_M,HC_EV_NM,clampLevel,levelState,transition,probeAbsorption,spectralSeries}
});
