(function(){
  const M=window.CapacitorModel;if(!M)throw new Error("CapacitorModel is required");
  const state={mode:"geometry",areaCm2:200,distanceMm:2,voltage:120,constraint:"battery",kappa:4,fraction:0,guideStep:0,showCharges:true,showField:true,showDipoles:true,showEnergy:true};
  const $=id=>document.getElementById(id),R={canvas:$("capacitorCanvas"),relation:$("relationChart"),energy:$("energyChart"),tabs:[...document.querySelectorAll("[data-mode]")],routes:[...document.querySelectorAll(".route-step")],constraints:[...document.querySelectorAll("[data-constraint]")],presets:[...document.querySelectorAll("[data-preset]")],area:$("areaInput"),distance:$("distanceInput"),voltage:$("voltageInput"),kappa:$("kappaInput"),fraction:$("fractionInput"),areaValue:$("areaValue"),distanceValue:$("distanceValue"),voltageValue:$("voltageValue"),kappaValue:$("kappaValue"),fractionValue:$("fractionValue"),constraintValue:$("constraintValue"),modeTitle:$("modeTitle"),modeGoal:$("modeGoal"),badge:$("stateBadge"),hint:$("stageHint"),labels:[1,2,3,4,5,6].map(n=>$("metric"+n+"Label")),values:[1,2,3,4,5,6].map(n=>$("metric"+n)),nature:$("natureText"),explanation:$("explanationText"),relationTitle:$("relationTitle"),relationStatus:$("relationStatus"),energyTitle:$("energyTitle"),energyStatus:$("energyStatus"),stepIndex:$("stepIndex"),stepTitle:$("stepTitle"),stepPrompt:$("stepPrompt"),formula:$("formulaReadout"),reset:$("resetButton"),guide:$("guideButton"),step:$("stepButton"),focus:$("focusButton"),fullscreen:$("fullscreenButton"),dialog:$("guideDialog")};
  const ctx=R.canvas.getContext("2d"),rctx=R.relation.getContext("2d"),ectx=R.energy.getContext("2d"),C={bg:"#090d0f",grid:"rgba(223,229,223,.055)",cyan:"#64c7d8",green:"#7ad699",amber:"#efb950",red:"#ff786e",violet:"#b59ae5",white:"#dfe5df",muted:"#84908a"};
  const modes={geometry:["几何与电容","改变面积和板距，辨认电容器自身的结构属性","先看 C，再看带电状态怎样响应"],constraint:["连接状态","对照固定电压和固定电荷时各物理量的不同响应","切换电源边界，再改变板距"],dielectric:["插入介质","追踪极化、电容变化和介质受到的吸引力","拖动插入比例，比较两种约束"],breakdown:["储能边界","用场强和能量密度判断理想绝缘模型何时失效","提高电压或减小板距，接近空气击穿场强"]};
  const guide=[["先认结构量","电容器尚未接电时，是否已经具有电容？"],["再定约束量","改变结构前，电压和自由电荷哪一个被外部条件固定？"],["最后核能量","电容器能量变化由电池和外力分别贡献多少？"]];
  function transition(){return M.transition({constraint:state.constraint,initialAreaM2:.02,initialSeparationM:.002,initialRelativePermittivity:1,initialDielectricFraction:0,initialVoltageV:state.voltage,finalAreaM2:state.areaCm2/1e4,finalSeparationM:state.distanceMm/1000,finalRelativePermittivity:state.kappa,finalDielectricFraction:state.fraction})}
  function current(){const t=transition(),b=M.breakdown({areaM2:t.final.areaM2,separationM:t.final.separationM,relativePermittivity:t.final.relativePermittivity,dielectricFraction:t.final.dielectricFraction,constraint:t.final.constraint,voltageV:t.final.voltageV,chargeC:t.final.chargeC,breakdownFieldVm:3e6}),d=M.dielectricInsertion({areaM2:t.final.areaM2,separationM:t.final.separationM,relativePermittivity:state.kappa,fraction:state.fraction,constraint:state.constraint,voltageV:state.voltage,chargeC:t.initial.chargeC});return{t,b,d}}
  function size(c,x){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(300,Math.round(r.width)),h=Math.max(120,Math.round(r.height));if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}x.setTransform(d,0,0,d,0,0);return{w,h}}
  function grid(x,w,h){x.fillStyle=C.bg;x.fillRect(0,0,w,h);x.strokeStyle=C.grid;for(let a=18;a<w;a+=42){x.beginPath();x.moveTo(a,0);x.lineTo(a,h);x.stroke()}for(let a=18;a<h;a+=42){x.beginPath();x.moveTo(0,a);x.lineTo(w,a);x.stroke()}}
  function text(x,v,px,py,color=C.white,font="10px ui-monospace,monospace",align="left"){x.fillStyle=color;x.font=font;x.textAlign=align;x.fillText(v,px,py)}
  function arrow(x,x1,y1,x2,y2,color){x.strokeStyle=color;x.fillStyle=color;x.lineWidth=1.5;x.beginPath();x.moveTo(x1,y1);x.lineTo(x2,y2);x.stroke();const a=Math.atan2(y2-y1,x2-x1);x.beginPath();x.moveTo(x2,y2);x.lineTo(x2-7*Math.cos(a-.45),y2-7*Math.sin(a-.45));x.lineTo(x2-7*Math.cos(a+.45),y2-7*Math.sin(a+.45));x.fill()}
  function fmt(v,d=2){return Number(v).toFixed(d)}function eng(v,scale,unit,d=3){return fmt(v/scale,d)+" "+unit}
  function drawMain(q){const{w,h}=size(R.canvas,ctx);grid(ctx,w,h);const s=q.t.final,cx=w*.48,plateW=Math.min(w*.55,330),top=h*.28,gap=Math.max(70,Math.min(180,70+state.distanceMm/8*100)),bottom=top+gap,left=cx-plateW/2;ctx.fillStyle="#b7c1bb";ctx.fillRect(left,top-5,plateW,10);ctx.fillRect(left,bottom-5,plateW,10);
    if(state.fraction>0){ctx.fillStyle="rgba(181,154,229,.22)";ctx.strokeStyle=C.violet;const dw=plateW*state.fraction;ctx.fillRect(left,top+6,dw,gap-12);ctx.strokeRect(left,top+6,dw,gap-12);if(state.showDipoles)for(let x=left+16;x<left+dw-8;x+=28)for(let y=top+23;y<bottom-12;y+=32){text(ctx,"−",x,y,C.cyan,"700 9px sans-serif","center");text(ctx,"+",x+9,y,C.red,"700 9px sans-serif","center")}}
    const sign=s.voltageV>=0?1:-1;if(state.showCharges){const n=Math.max(8,Math.min(34,Math.round(Math.abs(s.chargeC)*1e9*1.5)));for(let i=0;i<n;i++){const x=left+12+(plateW-24)*(i/(n-1));text(ctx,sign>0?"+":"−",x,top-12,sign>0?C.red:C.cyan,"700 10px sans-serif","center");text(ctx,sign>0?"−":"+",x,bottom+19,sign>0?C.cyan:C.red,"700 10px sans-serif","center")}}
    if(state.showField){const density=state.showEnergy?Math.min(.25,.04+Math.abs(s.fieldVm)/3e6*.22):.05;ctx.fillStyle=`rgba(239,185,80,${density})`;ctx.fillRect(left,top+5,plateW,gap-10);for(let x=left+24;x<left+plateW-10;x+=48)arrow(ctx,x,top+22,x,bottom-20,sign>0?C.amber:C.cyan)}
    if(state.constraint==="battery"){ctx.strokeStyle=C.amber;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(left-42,top);ctx.lineTo(left-42,(top+bottom)/2-10);ctx.moveTo(left,bottom);ctx.lineTo(left-42,bottom);ctx.lineTo(left-42,(top+bottom)/2+10);ctx.stroke();ctx.fillRect(left-53,(top+bottom)/2-10,22,3);ctx.fillRect(left-48,(top+bottom)/2+8,12,3);text(ctx,"电源",left-42,bottom+27,C.amber,"700 9px sans-serif","center")}else{text(ctx,"断开 · Q固定",left-10,bottom+29,C.cyan,"700 9px sans-serif")}
    if(q.b.breakdown){ctx.strokeStyle=C.red;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-18,top+8);ctx.lineTo(cx+5,(top+bottom)/2-8);ctx.lineTo(cx-8,(top+bottom)/2+5);ctx.lineTo(cx+20,bottom-8);ctx.stroke();text(ctx,"达到击穿边界",cx,(top+bottom)/2-20,C.red,"700 11px sans-serif","center")}
    text(ctx,`d=${fmt(state.distanceMm,2)} mm`,left+plateW+18,(top+bottom)/2,C.violet,"700 10px monospace");text(ctx,`E=${eng(s.fieldVm,1e3,"kV/m",1)}`,cx,bottom+30,q.b.breakdown?C.red:C.green,"700 11px monospace","center")
  }
  function axes(x,w,h,ylabel,xlabel){const a={l:42,r:w-18,t:18,b:h-30};x.strokeStyle="rgba(223,229,223,.25)";x.beginPath();x.moveTo(a.l,a.t);x.lineTo(a.l,a.b);x.lineTo(a.r,a.b);x.stroke();text(x,ylabel,8,14,C.muted);text(x,xlabel,a.r,h-9,C.muted,"9px monospace","right");return a}
  function plot(x,p,color){x.strokeStyle=color;x.lineWidth=2;x.beginPath();p.forEach((v,i)=>i?x.lineTo(v.x,v.y):x.moveTo(v.x,v.y));x.stroke()}
  function drawRelation(q){const{w,h}=size(R.relation,rctx);grid(rctx,w,h);const a=axes(rctx,w,h,"归一化","d / mm"),cp=[],rp=[];for(let i=0;i<=120;i++){const d=.5+7.5*i/120,t=M.transition({constraint:state.constraint,initialAreaM2:.02,initialSeparationM:.002,initialVoltageV:state.voltage,finalAreaM2:state.areaCm2/1e4,finalSeparationM:d/1000,finalRelativePermittivity:state.kappa,finalDielectricFraction:state.fraction});cp.push({x:a.l+(a.r-a.l)*i/120,y:a.b-(a.b-a.t)*.82*Math.min(1,t.final.capacitanceF/t.initial.capacitanceF/4)});const ratio=state.constraint==="battery"?t.final.chargeC/t.initial.chargeC:t.final.voltageV/t.initial.voltageV;rp.push({x:a.l+(a.r-a.l)*i/120,y:a.b-(a.b-a.t)*.82*Math.min(1,ratio/4)})}plot(rctx,cp,C.green);plot(rctx,rp,state.constraint==="battery"?C.amber:C.cyan);text(rctx,"C/C₀",a.l+5,a.t+10,C.green,"700 8px monospace");text(rctx,state.constraint==="battery"?"Q/Q₀":"U/U₀",a.l+48,a.t+10,state.constraint==="battery"?C.amber:C.cyan,"700 8px monospace")}
  function bar(x,px,py,w,label,value,max,color){x.fillStyle="rgba(255,255,255,.07)";x.fillRect(px,py,w,17);x.fillStyle=color;const mid=px+w/2,span=w/2*Math.min(1,Math.abs(value)/(max||1));x.fillRect(value>=0?mid:mid-span,py,span,17);text(x,label,px,py-5,color,"700 9px sans-serif");text(x,eng(value,1e-6,"μJ",3),px+w,py-5,C.white,"700 8px monospace","right")}
  function drawEnergy(q){const{w,h}=size(R.energy,ectx);grid(ectx,w,h);const t=q.t,max=Math.max(Math.abs(t.capacitorEnergyChangeJ),Math.abs(t.batteryWorkJ),Math.abs(t.externalWorkJ),1e-12),x=38,bw=w-58;bar(ectx,x,48,bw,"电容器能量变化 ΔW",t.capacitorEnergyChangeJ,max,C.green);bar(ectx,x,99,bw,"电池对系统做功 W电池",t.batteryWorkJ,max,C.amber);bar(ectx,x,150,bw,"外力对系统做功 W外",t.externalWorkJ,max,C.violet);text(ectx,"负值",x,h-10,C.cyan,"8px monospace");text(ectx,"正值",x+bw,h-10,C.red,"8px monospace","right")}
  function update(q){const s=q.t.final,b=q.b,mode=modes[state.mode];R.modeTitle.textContent=mode[0];R.modeGoal.textContent=mode[1];R.hint.textContent=mode[2];R.badge.textContent=b.breakdown?"击穿 · 理想模型失效":state.constraint==="battery"?"接电源 · U固定":"断开电源 · Q固定";R.badge.className="state-badge "+(b.breakdown?"is-breakdown":state.constraint==="battery"?"is-battery":"is-isolated");R.labels.forEach((e,i)=>e.textContent=["电容 C","极板电荷 Q","电压 U","场强 E","储能 W","极板吸力"][i]);[eng(s.capacitanceF,1e-12,"pF"),eng(s.chargeC,1e-9,"nC"),fmt(s.voltageV,2)+" V",eng(s.fieldVm,1e3,"kV/m",2),eng(s.energyJ,1e-6,"μJ"),eng(s.attractionForceN,1e-3,"mN")].forEach((v,i)=>R.values[i].textContent=v);R.nature.textContent=b.breakdown?"场强达到空气击穿阈值，绝缘假设不再成立":state.constraint==="battery"?"电压由电源固定，结构改变会引起电荷交换":"断开后自由电荷固定，结构改变会引起电压变化";R.explanation.textContent=`C/C₀=${fmt(s.capacitanceF/q.t.initial.capacitanceF,3)} · Q/Q₀=${fmt(s.chargeC/q.t.initial.chargeC,3)} · U/U₀=${fmt(s.voltageV/q.t.initial.voltageV,3)}`;R.areaValue.textContent=fmt(state.areaCm2,0)+" cm²";R.distanceValue.textContent=fmt(state.distanceMm,2)+" mm";R.voltageValue.textContent=fmt(state.voltage,0)+" V";R.kappaValue.textContent=fmt(state.kappa,2);R.fractionValue.textContent=fmt(state.fraction*100,0)+"%";R.constraintValue.textContent=state.constraint==="battery"?"接电源 · U固定":"断开电源 · Q固定";R.relationTitle.textContent="板距扫描下的约束响应";R.relationStatus.textContent=state.constraint==="battery"?"U固定":"Q固定";R.energyTitle.textContent="能量来源与去向";R.energyStatus.textContent="ΔW=W电池+W外";const g=guide[state.guideStep];R.stepIndex.textContent=String(state.guideStep+1).padStart(2,"0");R.stepTitle.textContent=g[0];R.stepPrompt.textContent=g[1];R.formula.textContent=state.mode==="breakdown"?"E击穿≈3 MV/m":state.mode==="dielectric"?"C=C₀[1+(κ−1)x/L]":state.constraint==="battery"?"U固定 · Q=CU":"Q固定 · U=Q/C"}
  function fill(e){const a=+e.min,b=+e.max;e.style.setProperty("--range-progress",`${(+e.value-a)/(b-a)*100}%`)}function render(){const q=current();update(q);drawMain(q);drawRelation(q);drawEnergy(q);document.querySelectorAll('input[type="range"]').forEach(fill)}
  function sync(){R.area.value=state.areaCm2;R.distance.value=state.distanceMm;R.voltage.value=state.voltage;R.kappa.value=state.kappa;R.fraction.value=state.fraction;R.constraints.forEach(b=>b.classList.toggle("is-active",b.dataset.constraint===state.constraint))}
  function setMode(m){state.mode=m;R.tabs.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===m));render()}[["area","areaCm2"],["distance","distanceMm"],["voltage","voltage"],["kappa","kappa"],["fraction","fraction"]].forEach(([id,key])=>R[id].addEventListener("input",()=>{state[key]=+R[id].value;render()}));R.tabs.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));R.constraints.forEach(b=>b.addEventListener("click",()=>{state.constraint=b.dataset.constraint;sync();render()}));R.routes.forEach((b,i)=>b.addEventListener("click",()=>{state.guideStep=i;R.routes.forEach((x,j)=>x.classList.toggle("is-active",i===j));render()}));R.presets.forEach(b=>b.addEventListener("click",()=>{if(b.dataset.preset==="baseline")Object.assign(state,{areaCm2:200,distanceMm:2,voltage:120,kappa:4,fraction:0});if(b.dataset.preset==="double-distance")Object.assign(state,{areaCm2:200,distanceMm:4,voltage:120,kappa:1,fraction:0});if(b.dataset.preset==="dielectric")Object.assign(state,{areaCm2:200,distanceMm:2,voltage:120,kappa:4,fraction:1,mode:"dielectric"});if(b.dataset.preset==="breakdown")Object.assign(state,{areaCm2:200,distanceMm:1,voltage:3000,constraint:"battery",kappa:1,fraction:0,mode:"breakdown"});sync();setMode(state.mode)}));R.reset.addEventListener("click",()=>{Object.assign(state,{mode:"geometry",areaCm2:200,distanceMm:2,voltage:120,constraint:"battery",kappa:4,fraction:0,guideStep:0});sync();setMode("geometry")});R.guide.addEventListener("click",()=>R.dialog.showModal());R.step.addEventListener("click",()=>{state.guideStep=(state.guideStep+1)%3;R.routes.forEach((x,j)=>x.classList.toggle("is-active",j===state.guideStep));render()});R.focus.addEventListener("click",()=>document.body.classList.toggle("focus-mode"));R.fullscreen.addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.());[["showChargesToggle","showCharges"],["showFieldToggle","showField"],["showDipolesToggle","showDipoles"],["showEnergyToggle","showEnergy"]].forEach(([id,key])=>$(id).addEventListener("change",e=>{state[key]=e.target.checked;render()}));window.addEventListener("resize",render);sync();setMode("geometry");
})();
