(function () {
  "use strict";
  const M = window.Collision2DModel;
  if (!M) throw new Error("Collision2DModel is required");
  const MODES = { oblique: ["弹性斜碰", "接触法线改变时，两圆盘碰后方向怎样变化"], head: ["等质量正碰", "为什么一个运动圆盘会把法向速度完整交给静止圆盘"], inelastic: ["非弹性斜碰", "动量守恒时，减少的机械能怎样由恢复系数决定"], away: ["分离边界", "相对法向速度不指向接近时为什么没有碰撞冲量"] };
  const STEPS = [["先定接触法线", "圆盘接触瞬间的公法线如何决定冲量方向？"], ["再分法向切向", "为什么光滑圆盘的切向速度分量保持不变？"], ["最后核双账本", "x、y 动量和动能损失能否同时闭合？"]];
  const state = { mode: "oblique", mass1Kg: 1, mass2Kg: 1, speed1Ms: 4, angle1Deg: 0, speed2Ms: 0, angle2Deg: 0, normalDeg: 45, restitution: 1, guideStep: 0, showBefore: true, showAfter: true, showBasis: true, showLedger: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("collision2dCanvas"), momentum: $("momentumChart"), energy: $("energyChart"), mass1: $("mass1Input"), mass2: $("mass2Input"), speed1: $("speed1Input"), angle1: $("angle1Input"), speed2: $("speed2Input"), angle2: $("angle2Input"), normal: $("normalInput"), restitution: $("restitutionInput"), mass1Value: $("mass1Value"), mass2Value: $("mass2Value"), speed1Value: $("speed1Value"), angle1Value: $("angle1Value"), speed2Value: $("speed2Value"), angle2Value: $("angle2Value"), normalValue: $("normalValue"), restitutionValue: $("restitutionValue"), before: $("showBeforeToggle"), after: $("showAfterToggle"), basis: $("showBasisToggle"), ledger: $("showLedgerToggle"), approachMetric: $("approachMetric"), impulseMetric: $("impulseMetric"), velocity1Metric: $("velocity1Metric"), velocity2Metric: $("velocity2Metric"), lossMetric: $("lossMetric"), residualMetric: $("residualMetric"), nature: $("natureText"), explanation: $("explanationText"), momentumStatus: $("momentumStatus"), energyStatus: $("energyStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), mctx = R.momentum.getContext("2d"), ectx = R.energy.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, color, label, dashed = false) { line(k, x1, y1, x2, y2, color, 3, dashed ? [5, 5] : []); const a = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = color; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 9 * Math.cos(a - .5), y2 - 9 * Math.sin(a - .5)); k.lineTo(x2 - 9 * Math.cos(a + .5), y2 - 9 * Math.sin(a + .5)); k.fill(); if (label) text(k, label, x2 + 6, y2 - 6, color, 10, "left", 800); }
  function velocityArrow(k, origin, velocity, color, label, scale = 25, dashed = false) { const length = Math.hypot(velocity.x, velocity.y); if (length < 1e-9) { text(k, `${label}=0`, origin.x, origin.y - 35, color, 9, "center", 800); return; } arrow(k, origin.x, origin.y, origin.x + velocity.x * scale, origin.y - velocity.y * scale, color, label, dashed); }
  function drawMain() {
    const s = size(R.main, ctx, 290), p = M.solve(input()), cx = s.width * .5, cy = s.height * .52, diskR = 32, sep = diskR, c1 = { x: cx - p.normal.x * sep, y: cy + p.normal.y * sep }, c2 = { x: cx + p.normal.x * sep, y: cy - p.normal.y * sep };
    bg(ctx, s.width, s.height); if (state.showBasis) { line(ctx, cx - p.normal.x * 130, cy + p.normal.y * 130, cx + p.normal.x * 130, cy - p.normal.y * 130, C.green, 2, [5, 5]); line(ctx, cx - p.tangent.x * 90, cy + p.tangent.y * 90, cx + p.tangent.x * 90, cy - p.tangent.y * 90, C.violet, 1, [4, 4]); text(ctx, "n̂", cx + p.normal.x * 142, cy - p.normal.y * 142, C.green, 10, "center", 800); text(ctx, "t̂", cx + p.tangent.x * 100, cy - p.tangent.y * 100, C.violet, 10, "center", 800); }
    [[c1, C.amber, "1"], [c2, C.violet, "2"]].forEach(([c, color, label]) => { ctx.fillStyle = `${color}22`; ctx.strokeStyle = color; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(c.x, c.y, diskR, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); text(ctx, label, c.x, c.y + 5, color, 13, "center", 900); });
    const vectorScale = Math.min(26, Math.max(10, (s.width - 100) / 30)); if (state.showBefore) { velocityArrow(ctx, c1, p.u1, C.cyan, "u₁", vectorScale, true); velocityArrow(ctx, c2, p.u2, C.cyan, "u₂", vectorScale, true); } if (state.showAfter) { velocityArrow(ctx, c1, p.v1, C.amber, "v₁", vectorScale); velocityArrow(ctx, c2, p.v2, C.violet, "v₂", vectorScale); }
    if (p.collided) { arrow(ctx, c1.x, c1.y, c1.x - p.normal.x * 60, c1.y + p.normal.y * 60, C.red, "−J"); arrow(ctx, c2.x, c2.y, c2.x + p.normal.x * 60, c2.y - p.normal.y * 60, C.red, "+J"); }
    text(ctx, `φ=${fmt(state.normalDeg, 0)}°`, 22, 30, C.green, 10, "left", 800); text(ctx, p.collided ? `J=${fmt(p.impulseNs)} N·s` : "无接近 · 不碰撞", s.width - 22, 30, p.collided ? C.red : C.amber, 10, "right", 800); text(ctx, "虚线：碰前 · 实线：碰后", 22, s.height - 20, C.text, 9);
  }
  function drawMomentum() {
    const s = size(R.momentum, mctx), p = M.solve(input()), center = { x: s.width * .5, y: s.height * .56 }, vectors = [{ v: { x: p.u1.x * state.mass1Kg, y: p.u1.y * state.mass1Kg }, c: C.amber, l: "p₁前" }, { v: { x: p.u2.x * state.mass2Kg, y: p.u2.y * state.mass2Kg }, c: C.violet, l: "p₂前" }, { v: p.momentumBefore, c: C.green, l: "" }, { v: p.momentumAfter, c: C.cyan, l: "" }], max = Math.max(1, ...vectors.map(x => Math.hypot(x.v.x, x.v.y))), scale = Math.min(s.width, s.height) * .32 / max; bg(mctx, s.width, s.height); line(mctx, 25, center.y, s.width - 20, center.y, "rgba(223,229,223,.2)"); line(mctx, center.x, 20, center.x, s.height - 25, "rgba(223,229,223,.2)"); vectors.forEach((item, i) => arrow(mctx, center.x, center.y, center.x + item.v.x * scale, center.y - item.v.y * scale, item.c, item.l, i < 2)); text(mctx, "P总（前=后）", center.x + p.momentumAfter.x * scale + 6, center.y - p.momentumAfter.y * scale - 22, C.green, 9, "left", 800); text(mctx, "px", s.width - 16, center.y - 6, C.muted, 8, "right"); text(mctx, "py", center.x + 7, 13, C.muted, 8);
  }
  function drawEnergy() {
    const s = size(R.energy, ectx), p = M.solve(input()), values = state.showLedger ? [["碰前动能", p.kineticBeforeJ, C.amber], ["碰后动能", p.kineticAfterJ, C.cyan], ["损失", p.kineticLossJ, C.red]] : [], scale = Math.max(.01, ...values.map(v => Math.abs(v[1]))), x0 = 92; bg(ectx, s.width, s.height); values.forEach((v, i) => { const y = 48 + i * 54, width = Math.abs(v[1]) / scale * (s.width - 150); text(ectx, v[0], 15, y + 4, C.text, 9); ectx.fillStyle = v[2]; ectx.fillRect(x0, y - 9, width, 18); text(ectx, `${fmt(v[1])} J`, s.width - 15, y + 4, v[2], 9, "right", 800); }); text(ectx, `理论损失 ${fmt(p.expectedLossJ)} J`, s.width - 15, 15, C.green, 9, "right", 700);
  }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - Number(el.min)) / (Number(el.max) - Number(el.min)) * 100}%`); }
  function render() {
    const p = M.solve(input()), elastic = p.collided && state.restitution > .999;
    R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.badge.textContent = !p.collided ? "相互分离，没有碰撞冲量" : elastic ? "弹性碰撞，动能守恒" : `非弹性碰撞，损失 ${fmt(p.kineticLossJ)} J`; R.badge.className = `state-badge ${elastic ? "is-elastic" : !p.collided ? "is-separated" : ""}`;
    const fields = [[R.mass1, state.mass1Kg, R.mass1Value, "kg", 2], [R.mass2, state.mass2Kg, R.mass2Value, "kg", 2], [R.speed1, state.speed1Ms, R.speed1Value, "m/s", 2], [R.angle1, state.angle1Deg, R.angle1Value, "°", 0], [R.speed2, state.speed2Ms, R.speed2Value, "m/s", 2], [R.angle2, state.angle2Deg, R.angle2Value, "°", 0], [R.normal, state.normalDeg, R.normalValue, "°", 0], [R.restitution, state.restitution, R.restitutionValue, "", 2]]; fields.forEach(([el, value, label, unit, digits]) => { range(el, value); label.textContent = `${fmt(value, digits)}${unit === "°" ? unit : unit ? ` ${unit}` : ""}`; });
    R.approachMetric.textContent = `${fmt(p.approachSpeedMs)} m/s`; R.impulseMetric.textContent = `${fmt(p.impulseNs)} N·s`; R.velocity1Metric.textContent = `(${fmt(p.v1.x, 2)}, ${fmt(p.v1.y, 2)})`; R.velocity2Metric.textContent = `(${fmt(p.v2.x, 2)}, ${fmt(p.v2.y, 2)})`; R.lossMetric.textContent = `${fmt(p.kineticLossJ)} J`; const residual = Math.hypot(p.momentumResidual.x, p.momentumResidual.y); R.residualMetric.textContent = fmt(residual, 6); R.nature.textContent = !p.collided ? "法向相对速度不指向接近" : "冲量只改变法向分量"; R.explanation.textContent = !p.collided ? "gₙ≤0 → J=0" : elastic ? "e=1，动能守恒" : `e=${fmt(state.restitution, 2)}，动量守恒`; R.momentumStatus.textContent = `|Δp⃗|=${fmt(residual, 6)}`; R.energyStatus.textContent = elastic ? "动能守恒" : `损失 ${fmt(p.kineticLossJ)} J`; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = !p.collided ? "gₙ≤0 → J=0" : state.guideStep === 0 ? "J∥n̂" : state.guideStep === 1 ? "vₜ后=vₜ前" : "p⃗前=p⃗后"; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawMain(); drawMomentum(); drawEnergy();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "oblique") Object.assign(state, { mass1Kg: 1, mass2Kg: 1, speed1Ms: 4, angle1Deg: 0, speed2Ms: 0, angle2Deg: 0, normalDeg: 45, restitution: 1 }); if (mode === "head") Object.assign(state, { mass1Kg: 1, mass2Kg: 1, speed1Ms: 4, angle1Deg: 0, speed2Ms: 0, angle2Deg: 0, normalDeg: 0, restitution: 1 }); if (mode === "inelastic") Object.assign(state, { mass1Kg: 2, mass2Kg: 3, speed1Ms: 5, angle1Deg: 20, speed2Ms: 2, angle2Deg: -30, normalDeg: 35, restitution: .4 }); if (mode === "away") Object.assign(state, { mass1Kg: 1, mass2Kg: 1, speed1Ms: 1, angle1Deg: 180, speed2Ms: 0, angle2Deg: 0, normalDeg: 0, restitution: 1 }); render(); }
  function reset() { Object.assign(state, { mode: "oblique", mass1Kg: 1, mass2Kg: 1, speed1Ms: 4, angle1Deg: 0, speed2Ms: 0, angle2Deg: 0, normalDeg: 45, restitution: 1, guideStep: 0, showBefore: true, showAfter: true, showBasis: true, showLedger: true, dragging: false }); [[R.before, "showBefore"], [R.after, "showAfter"], [R.basis, "showBasis"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { mass1Kg: [.1, 10], mass2Kg: [.1, 10], speed1Ms: [0, 15], angle1Deg: [-180, 180], speed2Ms: [0, 15], angle2Deg: [-180, 180], normalDeg: [-90, 90], restitution: [0, 1] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); if (MODES[next.mode]) state.mode = next.mode; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showBefore", "showAfter", "showBasis", "showLedger"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.mass1, "mass1Kg"], [R.mass2, "mass2Kg"], [R.speed1, "speed1Ms"], [R.angle1, "angle1Deg"], [R.speed2, "speed2Ms"], [R.angle2, "angle2Deg"], [R.normal, "normalDeg"], [R.restitution, "restitution"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.before, "showBefore"], [R.after, "showAfter"], [R.basis, "showBasis"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(), cx = box.left + box.width / 2, cy = box.top + box.height / 2; state.normalDeg = clamp(-Math.atan2(event.clientY - cy, event.clientX - cx) * 180 / Math.PI, -90, 90); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.collision2dLab = { solve: next => M.solve(next), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
