(function () {
  const model = (data) => ({
    status: "planned",
    visual: "关系图与动态示意",
    ...data
  });

  const books = [
    {
      id: "required-1",
      title: "必修第一册",
      summary: "从描述运动到建立牛顿力学，形成高中物理最基本的建模语言。",
      chapters: [
        { id: "required-1-1", title: "第一章 运动的描述" },
        { id: "required-1-2", title: "第二章 匀变速直线运动的研究" },
        { id: "required-1-3", title: "第三章 相互作用" },
        { id: "required-1-4", title: "第四章 运动和力的关系" }
      ]
    },
    {
      id: "required-2",
      title: "必修第二册",
      summary: "从曲线运动进入圆周运动、万有引力以及功和机械能。",
      chapters: [
        { id: "required-2-5", title: "第五章 抛体运动" },
        { id: "required-2-6", title: "第六章 圆周运动" },
        { id: "required-2-7", title: "第七章 万有引力与宇宙航行" },
        { id: "required-2-8", title: "第八章 机械能守恒定律" }
      ]
    },
    {
      id: "required-3",
      title: "必修第三册",
      summary: "从静电场和电路出发，建立电能、电磁感应与电磁波的基础图景。",
      chapters: [
        { id: "required-3-9", title: "第九章 静电场及其应用" },
        { id: "required-3-10", title: "第十章 静电场中的能量" },
        { id: "required-3-11", title: "第十一章 电路及其应用" },
        { id: "required-3-12", title: "第十二章 电能 能量守恒定律" },
        { id: "required-3-13", title: "第十三章 电磁感应与电磁波初步" }
      ]
    },
    {
      id: "selective-1",
      title: "选择性必修第一册",
      summary: "从动量守恒扩展到机械振动、机械波和光的传播与成像。",
      chapters: [
        { id: "selective-1-1", title: "第一章 动量守恒定律" },
        { id: "selective-1-2", title: "第二章 机械振动" },
        { id: "selective-1-3", title: "第三章 机械波" },
        { id: "selective-1-4", title: "第四章 光" }
      ]
    },
    {
      id: "selective-2",
      title: "选择性必修第二册",
      summary: "从磁场力进入电磁感应、交变电流、电磁振荡和传感器。",
      chapters: [
        { id: "selective-2-1", title: "第一章 安培力与洛伦兹力" },
        { id: "selective-2-2", title: "第二章 电磁感应" },
        { id: "selective-2-3", title: "第三章 交变电流" },
        { id: "selective-2-4", title: "第四章 电磁振荡与电磁波" },
        { id: "selective-2-5", title: "第五章 传感器" }
      ]
    },
    {
      id: "selective-3",
      title: "选择性必修第三册",
      summary: "从微观粒子运动到热力学、量子现象和原子核。",
      chapters: [
        { id: "selective-3-1", title: "第一章 分子动理论" },
        { id: "selective-3-2", title: "第二章 气体、固体和液体" },
        { id: "selective-3-3", title: "第三章 热力学定律" },
        { id: "selective-3-4", title: "第四章 原子结构和波粒二象性" },
        { id: "selective-3-5", title: "第五章 原子核" }
      ]
    }
  ];

  const models = [
    model({
      id: "motion-description",
      chapterId: "required-1-1",
      title: "参考系、位置与位移",
      category: "运动与力",
      visual: "坐标轴与运动轨迹",
      summary: "用同一物体在不同参考系中的位置变化，区分路程、位移和运动描述。",
      hook: "同一辆车相对于路边在运动，相对于车内乘客却可以是静止的。究竟是谁在运动？",
      model: "选定参考系和坐标轴，用位置随时间的变化描述物体运动；位移只比较初末位置，不等于实际走过的路程。",
      relations: ["位置 x(t)", "位移 Δx = x2 - x1", "路程是轨迹长度", "运动描述依赖参考系"],
      explore: ["切换参考系，观察同一物体的 x-t 图像如何改变。", "让物体往返运动，比较位移和路程的变化。"],
      misconceptions: "位移不是物体走过的长度；运动和静止必须先说明参考系。",
      prerequisite: "数轴、时间间隔和正负方向"
    }),
    model({
      id: "motion-graphs",
      chapterId: "required-1-1",
      title: "x-t 与 v-t 图像",
      category: "运动与力",
      visual: "同步运动图像",
      summary: "把运动过程、位置图像、速度图像和轨迹放在同一时间轴上。",
      hook: "图像上的斜率和面积为什么能告诉我们速度和位移？",
      model: "x-t 图像的斜率表示速度；v-t 图像的斜率表示加速度，图像与时间轴围成的有向面积表示位移。",
      relations: ["x-t 斜率 -> v", "v-t 斜率 -> a", "v-t 面积 -> Δx"],
      explore: ["在匀速、加速和减速三种状态间切换，比较两类图像。", "改变运动方向，观察图像正负号和面积符号。"],
      misconceptions: "图像的高度、斜率和面积代表不同物理量，不能混用。",
      prerequisite: "速度、加速度和函数图像的斜率",
      status: "open",
      lab: "motion-graphs.html"
    }),
    model({
      id: "uniform-acceleration",
      chapterId: "required-1-2",
      title: "匀变速直线运动",
      category: "运动与力",
      visual: "轨迹与三类运动图像",
      summary: "通过速度均匀变化的运动，建立位移、速度、加速度之间的联系。",
      hook: "速度每秒增加相同的数值，位移为什么不是每秒增加相同的数值？",
      model: "加速度恒定时，v-t 图像是直线，x-t 图像是抛物线；运动学公式是图像关系的代数表达。",
      relations: ["v = v0 + at", "x = v0t + 1/2at^2", "v^2 - v0^2 = 2ax"],
      explore: ["固定加速度，比较不同初速度的轨迹和图像。", "暂停在相等时间间隔，观察位移增量如何变化。"],
      misconceptions: "加速度恒定不代表速度恒定；速度为零的瞬间加速度仍可能不为零。",
      prerequisite: "速度、加速度、x-t 和 v-t 图像"
    }),
    model({
      id: "free-fall",
      chapterId: "required-1-2",
      title: "自由落体与竖直上抛",
      category: "运动与力",
      visual: "逐帧位置与速度矢量",
      summary: "在忽略空气阻力的模型中，比较下落、上抛和最高点附近的状态。",
      hook: "物体到达最高点时速度为零，为什么并没有停留在那里？",
      model: "自由落体和竖直上抛都以重力加速度 g 做匀变速直线运动，最高点只是速度方向改变的瞬间。",
      relations: ["a = -g", "上升与下落共享同一加速度", "最高点 v = 0 但 a != 0"],
      explore: ["在最高点暂停，同时显示速度和加速度箭头。", "比较相同高度上升和下降时的速率。"],
      misconceptions: "最高点速度为零不等于加速度为零；下落时间和上升时间的结论依赖初末高度。",
      prerequisite: "匀变速直线运动和重力加速度"
    }),
    model({
      id: "force-vectors",
      chapterId: "required-1-3",
      title: "力的三要素与矢量合成",
      category: "运动与力",
      visual: "受力图与矢量平行四边形",
      summary: "把力的大小、方向、作用点和合力关系从示意图中分离出来。",
      hook: "两个方向不同的力，为什么不能直接把数值相加？",
      model: "力是矢量，合力由各分力的矢量和决定；受力分析必须先确定研究对象和真实接触关系。",
      relations: ["F合 = ΣF", "正交分解 Fx, Fy", "平衡条件 F合 = 0"],
      explore: ["拖动两个分力的方向和大小，观察合力箭头。", "切换不同研究对象，比较对应受力图。"],
      misconceptions: "合力不是额外存在的一个力；受力图不能把物体对外施力画到物体受力图中。",
      prerequisite: "矢量方向、正交分解和牛顿第二定律"
    }),
    model({
      id: "friction-model",
      chapterId: "required-1-3",
      title: "静摩擦力与滑动摩擦力",
      category: "运动与力",
      visual: "接触面与力的响应曲线",
      summary: "通过外力逐渐增大的过程，显示静摩擦力如何自适应以及何时转入滑动。",
      hook: "静止物体受到推力却没有运动，静摩擦力到底有没有变化？",
      model: "静摩擦力在不超过最大值时随外界需要变化；发生相对滑动后转为滑动摩擦力，方向总是阻碍相对运动。",
      relations: ["0 <= f静 <= fmax", "fmax = μsN", "f滑 = μkN"],
      explore: ["逐渐增大水平拉力，记录静摩擦力和加速度。", "改变正压力，比较最大静摩擦力和滑动摩擦力。"],
      misconceptions: "静摩擦力不总是等于 μN；没有相对运动不代表没有摩擦力。",
      prerequisite: "受力分析、平衡条件和牛顿第二定律",
      status: "open",
      lab: "friction.html"
    }),
    model({
      id: "elastic-force",
      chapterId: "required-1-3",
      title: "弹簧弹力与胡克定律",
      category: "运动与力",
      visual: "形变量与弹力图像",
      summary: "把形变量、弹力方向和弹簧劲度系数联系起来，观察线性模型的适用范围。",
      hook: "弹簧被拉长后，弹力为什么指向恢复原状的方向？",
      model: "在弹性限度内，弹力大小与形变量成正比，方向总是指向恢复平衡位置的方向。",
      relations: ["F = kx", "k 表示劲度系数", "弹性限度决定模型边界"],
      explore: ["改变劲度系数，比较相同形变量下的弹力。", "逐渐超出线性范围，观察胡克定律何时失效。"],
      misconceptions: "x 是相对原长的形变量；弹力方向不能只看物体运动方向。",
      prerequisite: "力的方向、位移和函数图像"
    }),
    model({
      id: "newton-laws",
      chapterId: "required-1-4",
      title: "牛顿第二定律",
      category: "运动与力",
      visual: "合力、质量与加速度联动",
      summary: "同步改变合力和质量，直接观察 a 与 F、m 的关系。",
      hook: "同样的推力作用在不同质量的物体上，为什么运动状态改变得不同？",
      model: "物体的加速度由合外力和质量共同决定，方向与合外力相同，大小满足 F合 = ma。",
      relations: ["a ∝ F合", "a ∝ 1/m", "F合决定加速度而非速度"],
      explore: ["固定质量改变合力，拟合 a-F 图像。", "固定合力改变质量，比较相同时间内的速度变化。"],
      misconceptions: "合力越大不一定速度越大；没有合力只表示加速度为零。",
      prerequisite: "受力分析、加速度和矢量合成",
      status: "open",
      lab: "newton-laws.html"
    }),
    model({
      id: "action-reaction",
      chapterId: "required-1-4",
      title: "牛顿第三定律",
      category: "运动与力",
      visual: "相互作用力成对显示",
      summary: "用两个物体的受力箭头和力的实时读数，区分作用力与反作用力。",
      hook: "大人推小车和小车推大人，两个力谁更大？",
      model: "相互作用力大小相等、方向相反、作用在两个相互作用的物体上，产生和消失同步。",
      relations: ["FAB = -FBA", "作用对象不同", "不能在同一受力图中抵消"],
      explore: ["改变两个物体质量，比较相互作用力和各自加速度。", "分别切换两个研究对象的受力图。"],
      misconceptions: "作用力和反作用力不是同一物体上的平衡力；质量不同不改变相互作用力大小。",
      prerequisite: "研究对象、受力图和矢量方向"
    }),
    model({
      id: "connected-bodies",
      chapterId: "required-1-4",
      title: "连接体与整体法",
      category: "运动与力",
      visual: "系统边界与内外力切换",
      summary: "在多个物体组成的系统中切换整体法和隔离法，观察内力是否影响整体运动。",
      hook: "两个物体用轻绳相连时，绳中张力为什么有时不需要先求？",
      model: "选整体可消去内部相互作用力，选单个物体可求张力等内力；方法取决于问题目标。",
      relations: ["F外合 = ma整体", "内力成对出现", "轻绳约束加速度关系"],
      explore: ["切换系统边界，比较整体和隔离受力图。", "改变接触面摩擦，观察约束条件是否仍成立。"],
      misconceptions: "整体法不是忽略内力，而是内力在整体方程中相互抵消；轻绳约束有适用条件。",
      prerequisite: "牛顿第二定律和牛顿第三定律"
    }),

    model({
      id: "projectile-decomposition",
      chapterId: "required-2-5",
      title: "抛体运动的分解",
      category: "运动与力",
      visual: "轨迹、速度分量与图像",
      summary: "将斜抛或平抛运动分解为水平方向和竖直方向的独立运动。",
      hook: "最高点的竖直速度为零，为什么水平方向仍然在前进？",
      model: "忽略空气阻力时，水平方向做匀速运动，竖直方向做自由落体或竖直上抛运动。",
      relations: ["vx = v0 cosθ", "vy = v0 sinθ - gt", "轨迹是抛物线"],
      explore: ["固定初速度改变发射角，比较射程和飞行时间。", "单独隐藏一个速度分量，观察轨迹解释是否仍成立。"],
      misconceptions: "最高点不是速度为零；轨迹是曲线不代表加速度沿轨迹方向。",
      prerequisite: "匀变速运动、矢量分解",
      status: "open",
      lab: "projectile.html"
    }),
    model({
      id: "circular-motion",
      chapterId: "required-2-6",
      title: "匀速圆周运动",
      category: "运动与力",
      visual: "圆轨道、速度与加速度箭头",
      summary: "比较速率、速度方向、周期和向心加速度，建立圆周运动的几何图景。",
      hook: "速率保持不变，为什么速度仍然在变化？",
      model: "匀速圆周运动中速率恒定但速度方向持续改变，因此存在指向圆心的向心加速度。",
      relations: ["a向 = v^2/r = ω^2r", "v = ωr", "T = 2π/ω"],
      explore: ["改变速度和半径，比较向心加速度。", "在圆周不同位置暂停，同时查看速度和加速度方向。"],
      misconceptions: "向心力不是一种新的力，而是指向圆心的合力；向心加速度不沿切线。",
      prerequisite: "速度方向、加速度和牛顿第二定律",
      status: "open",
      lab: "circular.html"
    }),
    model({
      id: "centripetal-force",
      chapterId: "required-2-6",
      title: "生活中的圆周运动与临界条件",
      category: "运动与力",
      visual: "过山车与受力临界图",
      summary: "把向心加速度需求和支持力、摩擦力、重力等真实力联系起来。",
      hook: "汽车转弯时为什么容易侧滑？过山车到最高点为什么不会掉下来？",
      model: "圆周运动的临界状态由径向方向的合力是否能提供所需向心力决定，摩擦和支持力可能成为约束条件。",
      relations: ["ΣF径 = mv^2/r", "最大静摩擦力限制转弯", "临界接触 N = 0"],
      explore: ["逐渐增大车速，观察摩擦力达到上限的时刻。", "改变圆轨道半径，比较安全速度范围。"],
      misconceptions: "向心力不能与某一个真实力简单等同；临界状态要说明哪个约束先达到极限。",
      prerequisite: "受力分析、圆周运动和静摩擦力"
    }),
    model({
      id: "gravitation-field",
      chapterId: "required-2-7",
      title: "万有引力与引力场",
      category: "运动与力",
      visual: "引力场强与距离关系",
      summary: "用可调质量和距离显示万有引力的方向、大小以及反平方关系。",
      hook: "两个物体相距变为原来两倍，引力为什么不是变为一半？",
      model: "任意两个有质量物体之间存在相互吸引力，大小与质量乘积成正比、与距离平方成反比。",
      relations: ["F = Gm1m2/r^2", "g = GM/r^2", "场强方向指向产生场的质量"],
      explore: ["固定质量改变距离，在对数坐标中观察反平方关系。", "比较地表和高空的重力加速度。"],
      misconceptions: "重力加速度 g 不是处处相同；引力场强描述单位质量所受力。",
      prerequisite: "力的矢量、比例关系和圆周运动"
    }),
    model({
      id: "orbital-motion",
      chapterId: "required-2-7",
      title: "卫星轨道与宇宙航行",
      category: "运动与力",
      visual: "轨道半径、速度与周期",
      summary: "从万有引力提供向心力出发，比较不同轨道的速度、周期和能量。",
      hook: "卫星离地越高，运行速度为什么反而越小，但周期却变长？",
      model: "近圆轨道中万有引力充当向心力；轨道半径决定速度、周期和机械能的尺度。",
      relations: ["v = √(GM/r)", "T^2 ∝ r^3", "同步轨道需匹配自转周期"],
      explore: ["拖动轨道半径，观察速度和周期的相反变化。", "比较不同轨道的引力势能和动能。"],
      misconceptions: "高轨道速度小不代表机械能小；脱离地球不是只看某一时刻速度方向。",
      prerequisite: "万有引力、圆周运动和机械能"
    }),
    model({
      id: "work-and-power",
      chapterId: "required-2-8",
      title: "功与功率",
      category: "能量与动量",
      visual: "力与位移夹角、能量流",
      summary: "同时显示力、位移和夹角，理解功的正负以及功率代表做功快慢。",
      hook: "人提着重物水平走路，手的力很大，为什么这个力对物体做功却可能为零？",
      model: "恒力功由力在位移方向的分量决定；功率描述单位时间内能量转移的快慢。",
      relations: ["W = Fs cosθ", "P = W/t", "瞬时功率 P = Fv cosθ"],
      explore: ["改变力与位移夹角，观察功的正负。", "固定总功，改变完成时间，比较功率。"],
      misconceptions: "有力不一定有功；功率大不等于一段时间内做功一定多。",
      prerequisite: "力、位移、速度和三角函数"
    }),
    model({
      id: "mechanical-energy",
      chapterId: "required-2-8",
      title: "机械能守恒",
      category: "能量与动量",
      visual: "动能与势能堆叠图",
      summary: "让动能、重力势能和弹性势能随时间交换，直接观察总机械能是否保持。",
      hook: "物体速度变小了，能量去哪儿了？",
      model: "只有重力或弹力做功时，动能与相应势能可以相互转化，机械能总量保持不变。",
      relations: ["Ek = 1/2mv^2", "Ep = mgh", "E弹 = 1/2kx^2", "E机械 = 常量"],
      explore: ["切换有无摩擦，比较机械能和内能的变化。", "在相同高度读取速度，验证能量关系。"],
      misconceptions: "机械能守恒不等于所有形式的能量不变；存在阻力时总能量仍守恒，但机械能通常减少。",
      prerequisite: "功、动能和势能"
    }),

    model({
      id: "coulomb-force",
      chapterId: "required-3-9",
      title: "库仑定律与点电荷",
      category: "电磁学",
      visual: "电荷相互作用箭头",
      summary: "改变电荷量和距离，观察同种、异种电荷之间作用力的大小和方向。",
      hook: "电荷相距变为两倍，电力为什么下降得特别快？",
      model: "真空中点电荷间作用力沿两电荷连线，大小与电荷量乘积成正比、与距离平方成反比。",
      relations: ["F = k|q1q2|/r^2", "同号相斥、异号相吸", "力是相互作用力"],
      explore: ["分别改变一个电荷量和距离，比较力的变化率。", "放入第三个电荷，观察矢量叠加。"],
      misconceptions: "库仑力方向由电荷正负决定，不是永远排斥；点电荷模型有空间尺度限制。",
      prerequisite: "矢量合成、比例关系和万有引力"
    }),
    model({
      id: "electric-field",
      chapterId: "required-3-9",
      title: "电场强度与电场线",
      category: "电磁学",
      visual: "电场矢量与场线",
      summary: "用试探电荷和场线显示电场的方向、强弱及叠加关系。",
      hook: "不放入电荷时，空间中是否仍然存在电场？",
      model: "电场是电荷在空间建立的物理场；电场强度等于单位正电荷所受电场力，方向定义为正电荷受力方向。",
      relations: ["E = F/q", "点电荷 E = k|Q|/r^2", "场强遵循矢量叠加"],
      explore: ["隐藏试探电荷，只显示场线和场强箭头。", "叠加两个点电荷，寻找场强为零或方向突变的位置。"],
      misconceptions: "电场线不是实际存在的轨迹；场强与试探电荷电量无关。",
      prerequisite: "库仑定律、矢量和单位"
    }),
    model({
      id: "electric-conductor",
      chapterId: "required-3-9",
      title: "静电平衡与静电感应",
      category: "电磁学",
      visual: "导体内外电荷分布",
      summary: "观察自由电荷移动到平衡后的分布，以及尖端放电和屏蔽的模型。",
      hook: "外电场没有直接穿透导体，导体内部的电荷做了什么？",
      model: "静电平衡时导体内部场强为零，电荷分布在表面，导体表面是等势面，尖端处电荷更集中。",
      relations: ["导体内部 E = 0", "表面等势", "表面电场垂直导体表面"],
      explore: ["靠近带电体，观察导体表面正负电荷重新分布。", "改变导体形状，比较尖端处场线密度。"],
      misconceptions: "导体内部无场只适用于静电平衡；电荷不一定均匀分布在所有表面。",
      prerequisite: "电场线、等势面和电荷运动"
    }),
    model({
      id: "electric-potential",
      chapterId: "required-3-10",
      title: "电势与等势面",
      category: "电磁学",
      visual: "等势线与电场线",
      summary: "把电势高低、电势差和电场方向放在同一空间图中比较。",
      hook: "电场线从高电势指向低电势，为什么正电荷却可能向低电势运动？",
      model: "电势是单位正电荷的电势能；电势差描述电场力做功的能力，电场线与等势面处处垂直。",
      relations: ["U = qφ", "WAB = q(φA - φB)", "E垂直等势面"],
      explore: ["在等势线上移动电荷，检查电场力做功。", "比较等势线疏密和场强大小。"],
      misconceptions: "电势是标量，可为负；电势高低与正负电荷的运动方向不能直接等同。",
      prerequisite: "电场力做功、能量和场线"
    }),
    model({
      id: "capacitor-energy",
      chapterId: "required-3-10",
      title: "电容器与电场能量",
      category: "电磁学",
      visual: "极板、电势差与储能",
      summary: "改变极板距离、面积和介质，观察电容、电荷和电压之间的联系。",
      hook: "电容器断开电源后，改变极板间距，哪些物理量会改变？",
      model: "电容表示储存电荷的能力，取决于结构和介质；储存的电场能量与电荷和电压共同决定。",
      relations: ["C = Q/U", "平行板 C ∝ εS/d", "E储 = 1/2CU^2"],
      explore: ["分别在接电源和断开电源状态改变极板距离。", "切换介质，观察场强、能量和电势差的变化。"],
      misconceptions: "电容不是电容器所带电荷；接通电源与断开电源是两种不同约束条件。",
      prerequisite: "电势差、电场和能量"
    }),
    model({
      id: "ohm-circuit",
      chapterId: "required-3-11",
      title: "电流、电压与电阻",
      category: "电磁学",
      visual: "电路图与伏安特性",
      summary: "同步显示电路中的电流、电压和电阻，比较线性和非线性元件。",
      hook: "电压加倍，电流一定也加倍吗？",
      model: "电流表示单位时间通过导体横截面的电荷量；欧姆定律只适用于一定条件下的导体或元件。",
      relations: ["I = q/t", "U = IR", "R = ρL/S"],
      explore: ["扫过电压，绘制定值电阻和灯泡的 U-I 图像。", "改变导线长度和横截面积，观察电阻变化。"],
      misconceptions: "电阻是元件属性，不是电流消耗掉的东西；欧姆定律不是所有元件的普遍关系。",
      prerequisite: "电荷、电势差和比例图像"
    }),
    model({
      id: "series-parallel-circuit",
      chapterId: "required-3-11",
      title: "串并联电路与电表",
      category: "电磁学",
      visual: "电路拓扑与实时读数",
      summary: "通过电路拓扑切换，比较串联、并联中电流和电压的分配。",
      hook: "家庭电路为什么采用并联，而不是把所有用电器串起来？",
      model: "串联支路电流相同、总电压分配；并联各支路电压相同、总电流分流，电表接入方式取决于测量对象。",
      relations: ["串联 R总 = ΣR", "并联 1/R总 = Σ1/R", "电流表串联、电压表并联"],
      explore: ["逐个断开支路，观察并联电路的局部和整体读数。", "错误接入电表，显示其对电路的影响。"],
      misconceptions: "并联不是电压相加；理想电流表和电压表的内阻模型不能颠倒。",
      prerequisite: "电流、电压、电阻和电路图"
    }),
    model({
      id: "internal-resistance",
      chapterId: "required-3-11",
      title: "闭合电路与电源内阻",
      category: "电磁学",
      visual: "端电压与外电阻曲线",
      summary: "改变外电阻，显示电动势、端电压、内电压和路端电流的变化。",
      hook: "电池标称电压为什么在大电流用电器接入时会下降？",
      model: "实际电源有内阻，闭合电路中电动势提供的能量一部分消耗在内阻上。",
      relations: ["I = E/(R+r)", "U = E - Ir", "P输出在 R = r 时最大"],
      explore: ["改变外电阻，画出端电压和电流曲线。", "比较内阻损耗与外电路获得功率。"],
      misconceptions: "电动势不是电源两端的电压；端电压等于电动势只在无电流时成立。",
      prerequisite: "串联电路、功率和能量守恒"
    }),
    model({
      id: "electric-power-energy",
      chapterId: "required-3-12",
      title: "电功率与电能",
      category: "能量与动量",
      visual: "电能流与功率曲线",
      summary: "把电流、电压、功率和用电时间联系起来，比较不同负载的能量消耗。",
      hook: "额定功率更大的电器一定更费电吗？",
      model: "电功率是电能转化的快慢，实际耗电量还取决于工作时间和实际工作状态。",
      relations: ["P = UI = I^2R = U^2/R", "W = Pt", "焦耳热 Q = I^2Rt"],
      explore: ["改变工作时间，比较瞬时功率和累计电能。", "切换串并联，观察功率分配。"],
      misconceptions: "功率和电能不是同一个量；额定功率只对应额定工作条件。",
      prerequisite: "电路、电功率和能量"
    }),
    model({
      id: "electromagnetic-induction-basic",
      chapterId: "required-3-13",
      title: "电磁感应与楞次定律",
      category: "电磁学",
      visual: "磁通量、线圈与感应电流",
      summary: "改变磁场、面积或相对运动，观察磁通量变化如何产生感应电动势。",
      hook: "磁铁靠近线圈时，线圈为什么会反过来阻碍这个变化？",
      model: "闭合回路磁通量发生变化时产生感应电动势，感应电流方向总是阻碍磁通量的变化。",
      relations: ["Φ = BS cosθ", "E感 = -ΔΦ/Δt", "负号体现楞次定律"],
      explore: ["分别改变 B、S 和 θ，比较磁通量变化率。", "反转磁铁运动方向，观察感应电流方向改变。"],
      misconceptions: "有磁场不一定有感应电流，关键是磁通量变化；楞次定律不是阻碍磁通量本身。",
      prerequisite: "磁场、面积、角度和能量守恒"
    }),
    model({
      id: "electromagnetic-wave",
      chapterId: "required-3-13",
      title: "电磁波的产生与传播",
      category: "振动与波",
      visual: "相互垂直的场振荡",
      summary: "用时空切片显示电场、磁场和传播方向的关系，建立电磁波的场图像。",
      hook: "电磁波传播时没有介质，空间中到底是什么在振荡？",
      model: "变化的电场产生磁场，变化的磁场产生电场；电场、磁场和传播方向两两垂直。",
      relations: ["E ⟂ B ⟂ 传播方向", "真空中 c = 1/√(ε0μ0)", "频率决定波的类型"],
      explore: ["切换传播方向，观察 E 和 B 的方向关系。", "扫过频率，比较不同电磁波的波长和能量尺度。"],
      misconceptions: "电磁波不需要机械介质；电场和磁场不是两列彼此独立的机械波。",
      prerequisite: "机械波、场和振荡"
    }),

    model({
      id: "momentum-impulse",
      chapterId: "selective-1-1",
      title: "动量与冲量",
      category: "能量与动量",
      visual: "力-时间图像与动量变化",
      summary: "将碰撞过程中的力、作用时间和动量变化放在同一时间轴上。",
      hook: "安全气囊为什么能降低伤害，明明它没有消除碰撞前后的速度变化？",
      model: "动量描述运动状态，冲量描述力在一段时间内对动量的累积改变。",
      relations: ["p = mv", "I = FΔt = Δp", "F-t 面积表示冲量"],
      explore: ["保持动量变化不变，延长作用时间，比较平均力。", "比较硬碰撞和软碰撞的力-时间图像。"],
      misconceptions: "冲量不是力本身；作用时间变长不代表动量变化一定变小。",
      prerequisite: "牛顿第二定律、速度和图像面积"
    }),
    model({
      id: "momentum-collision",
      chapterId: "selective-1-1",
      title: "一维碰撞与动量守恒",
      category: "能量与动量",
      visual: "碰撞前后速度与动量条",
      summary: "比较弹性碰撞、非弹性碰撞中的动量和机械能变化。",
      hook: "碰撞后两个物体粘在一起，动量还守恒吗？机械能呢？",
      model: "系统所受合外力为零或外力冲量可忽略时，总动量守恒；机械能是否守恒取决于碰撞类型。",
      relations: ["Σp前 = Σp后", "弹性碰撞机械能也守恒", "完全非弹性碰撞速度相同"],
      explore: ["改变质量和初速度，验证碰撞前后总动量。", "分别显示动量、动能和内能的变化。"],
      misconceptions: "动量守恒不等于动能守恒；守恒对象必须是选定的系统。",
      prerequisite: "动量、冲量和能量"
    }),
    model({
      id: "recoil-and-rocket",
      chapterId: "selective-1-1",
      title: "反冲与火箭模型",
      category: "能量与动量",
      visual: "质量流出与质心运动",
      summary: "用封闭系统和质量流出的模型解释反冲、喷气推进与速度变化。",
      hook: "没有地面可蹬，火箭为什么仍能加速？",
      model: "系统内部物质相互作用时，总动量仍可守恒；火箭通过向后喷出高速气体获得向前动量。",
      relations: ["系统总动量守恒", "喷气速度和质量流率影响推力", "质量变化使模型更复杂"],
      explore: ["改变喷气速度和质量流率，比较推力。", "分别把火箭和火箭加燃料看作系统，比较动量方程。"],
      misconceptions: "火箭不是依靠空气反作用；系统边界变化时不能机械套用定质量公式。",
      prerequisite: "动量守恒、系统边界和牛顿第三定律"
    }),
    model({
      id: "simple-harmonic-motion",
      chapterId: "selective-1-2",
      title: "简谐振动",
      category: "振动与波",
      visual: "振子、时间图像与相位圆",
      summary: "同步观察位移、速度、加速度和能量的相位关系。",
      hook: "振子在端点速度为零，为什么加速度却最大？",
      model: "回复力与位移成正比且方向相反的周期运动称为简谐运动，位移、速度和加速度具有固定相位关系。",
      relations: ["F = -kx", "a = -ω^2x", "T = 2π√(m/k)"],
      explore: ["拖动相位，比较端点和平衡位置的状态。", "改变质量和劲度系数，比较周期和能量分配。"],
      misconceptions: "简谐运动不是所有往复运动；端点加速度最大但速度为零。",
      prerequisite: "牛顿第二定律、周期和正弦图像",
      status: "open",
      lab: "oscillation.html"
    }),
    model({
      id: "resonance",
      chapterId: "selective-1-2",
      title: "受迫振动与共振",
      category: "振动与波",
      visual: "振幅-频率响应曲线",
      summary: "改变驱动力频率，观察振幅在固有频率附近显著增大的现象。",
      hook: "为什么不是驱动力越大，振幅就越大？频率也会决定响应。",
      model: "受迫振动的稳态振幅取决于驱动力频率、固有频率和阻尼；驱动频率接近固有频率时出现共振。",
      relations: ["共振频率接近固有频率", "阻尼越大峰值越低", "振幅由频率响应决定"],
      explore: ["扫描驱动力频率，绘制共振曲线。", "改变阻尼，比较峰值和带宽。"],
      misconceptions: "共振不等于振动频率无限增大；有阻尼时峰值频率不一定正好等于无阻尼固有频率。",
      prerequisite: "简谐振动、频率和能量输入"
    }),
    model({
      id: "wave-propagation",
      chapterId: "selective-1-3",
      title: "机械波的形成与传播",
      category: "振动与波",
      visual: "介质质点与波形同步",
      summary: "区分波形传播速度和介质质点的振动速度，观察能量传播而非物质整体迁移。",
      hook: "绳上的波向前传播，绳上的每个质点真的跑到前面了吗？",
      model: "波是振动状态和能量的传播，介质质点只在平衡位置附近振动；波速由介质和条件决定。",
      relations: ["v波 = λf", "质点振动方向不等于波传播方向", "波传播能量和信息"],
      explore: ["标记一个介质质点，追踪它的振动轨迹。", "改变频率和波长，观察波速关系。"],
      misconceptions: "波速不是质点速度；波传播不必伴随介质整体向前移动。",
      prerequisite: "振动、周期、频率和速度"
    }),
    model({
      id: "wave-superposition",
      chapterId: "selective-1-3",
      title: "波的叠加与驻波",
      category: "振动与波",
      visual: "入射波、反射波与合成波",
      summary: "通过相向传播的两列波，显示节点、腹部和振幅的空间分布。",
      hook: "节点为什么始终不动，腹部为什么振幅最大？",
      model: "满足条件的两列相向传播波叠加形成驻波，节点处总位移始终为零，腹部处振幅最大。",
      relations: ["叠加原理", "相邻节点间距 λ/2", "节点与腹部相差 λ/4"],
      explore: ["改变波长，观察节点间距。", "分别隐藏两列分波，检查合成波如何产生。"],
      misconceptions: "驻波没有整体向前传播的波形；节点不动不代表附近介质没有能量交换。",
      prerequisite: "波的传播、相位和叠加",
      status: "open",
      lab: "waves.html"
    }),
    model({
      id: "reflection-refraction",
      chapterId: "selective-1-4",
      title: "光的反射与折射",
      category: "光学",
      visual: "光线、法线与介质界面",
      summary: "改变入射角和介质折射率，观察反射、折射方向及全反射临界条件。",
      hook: "筷子插入水中看起来弯了，光线实际走了哪条路？",
      model: "光在均匀介质中沿直线传播，在介质界面发生反射和折射；折射程度由两介质和入射角共同决定。",
      relations: ["反射角 = 入射角", "n1 sinθ1 = n2 sinθ2", "大于临界角时发生全反射"],
      explore: ["扫描入射角，比较反射角和折射角。", "改变介质折射率，寻找全反射临界角。"],
      misconceptions: "法线不是界面本身；全反射要求光从光密介质射向光疏介质。",
      prerequisite: "角度、三角函数和波传播"
    }),
    model({
      id: "thin-lens-imaging",
      chapterId: "selective-1-4",
      title: "透镜成像",
      category: "光学",
      visual: "主光线与成像位置",
      summary: "拖动物距和焦距，观察实像、虚像、放大率和光线汇聚。",
      hook: "物体逐渐靠近凸透镜时，倒立实像为什么会变成正立虚像？",
      model: "薄透镜模型用焦距和物距确定像的位置、大小和正倒；三条特殊光线可用于几何作图。",
      relations: ["1/f = 1/u + 1/v", "m = v/u", "u 与 f 的相对关系决定像的性质"],
      explore: ["跨过一倍和二倍焦距，记录像的性质变化。", "改变焦距，比较同一物距下的成像。"],
      misconceptions: "虚像不是光线真实会聚的位置；放大不等于一定是虚像。",
      prerequisite: "光的折射、相似三角形和函数关系"
    }),
    model({
      id: "light-interference-diffraction",
      chapterId: "selective-1-4",
      title: "光的干涉与衍射",
      category: "光学",
      visual: "强度分布与条纹",
      summary: "把相位差、路程差和屏上亮暗条纹联系起来，展示光的波动性。",
      hook: "两束光叠加后有些地方变亮，有些地方反而变暗，光能量去哪儿了？",
      model: "相干光叠加时，光强由相位差决定；障碍物或狭缝尺寸接近波长时会产生明显衍射。",
      relations: ["相长/相消干涉", "条纹间距与 λ、L、d 有关", "衍射显著条件 a 与 λ 同量级"],
      explore: ["改变波长和双缝间距，比较条纹间距。", "逐渐减小狭缝宽度，观察衍射展宽。"],
      misconceptions: "干涉条纹不是光子被分成不同能量；明显干涉需要相干条件。",
      prerequisite: "波的叠加、相位差和几何光路"
    }),

    model({
      id: "magnetic-field",
      chapterId: "selective-2-1",
      title: "电流的磁场",
      category: "电磁学",
      visual: "磁场线与方向判断",
      summary: "显示直线电流、环形电流和螺线管周围的磁场分布。",
      hook: "电流周围为什么会出现环绕电流方向的磁场？",
      model: "运动电荷或电流在空间建立磁场，磁场方向可由右手定则判断，场线疏密反映相对强弱。",
      relations: ["直线电流 B ∝ I/r", "螺线管 B 与 nI 有关", "磁场方向用右手定则"],
      explore: ["反转电流方向，观察磁场方向反转。", "比较单根导线和螺线管的场线分布。"],
      misconceptions: "磁场线不是磁场中真实存在的线；磁场方向不是小磁针 N 极运动方向的任意描述。",
      prerequisite: "电流、矢量方向和场线"
    }),
    model({
      id: "lorentz-force",
      chapterId: "selective-2-1",
      title: "安培力与洛伦兹力",
      category: "电磁学",
      visual: "速度、电流与磁场三向关系",
      summary: "改变电流、速度和磁场方向，实时显示磁场力的方向与大小。",
      hook: "磁场力为什么能改变速度方向，却不一定改变速率？",
      model: "载流导线在磁场中受安培力，运动电荷在磁场中受洛伦兹力；力方向同时取决于运动或电流方向和磁场方向。",
      relations: ["F安 = BIL sinθ", "F洛 = qvB sinθ", "磁场力垂直速度时不做功"],
      explore: ["扫描夹角，观察力从零到最大的变化。", "比较电场力和磁场力对速率、方向的作用。"],
      misconceptions: "带电粒子速度平行磁场时不受磁场力；磁场力不做功不代表不改变运动。",
      prerequisite: "矢量、圆周运动和电场力",
      status: "open",
      lab: "charged-particle.html"
    }),
    model({
      id: "velocity-selector",
      chapterId: "selective-2-1",
      title: "速度选择器与质谱仪",
      category: "电磁学",
      visual: "复合场中的带电粒子",
      summary: "把电场力和磁场力同时显示，解释配速、偏转和质量分离。",
      hook: "不同速度的带电粒子进入同一装置，为什么只有一种速度能直线通过？",
      model: "在相互垂直的电场和磁场中，满足 qE = qvB 的粒子受到的横向合力为零；偏转半径可用于测量动量和质量。",
      relations: ["v = E/B", "r = mv/(qB)", "选择速度后可进行质量分析"],
      explore: ["改变 E 或 B，寻找直线通过的速度。", "固定速度改变质量，比较磁场中的轨道半径。"],
      misconceptions: "配速只抵消特定方向的力；速度选择器不是让所有粒子速度相同。",
      prerequisite: "电场力、洛伦兹力和圆周运动"
    }),
    model({
      id: "faraday-law",
      chapterId: "selective-2-2",
      title: "法拉第电磁感应定律",
      category: "电磁学",
      visual: "磁通量-时间图像",
      summary: "从磁通量变化率读出感应电动势，区分磁通量大小和变化快慢。",
      hook: "磁通量很大但保持不变时，为什么可能没有感应电动势？",
      model: "感应电动势大小等于磁通量变化率的负值，变化越快，感应电动势越大。",
      relations: ["E = -NΔΦ/Δt", "E 与斜率有关", "线圈匝数放大感应效应"],
      explore: ["对同样磁通量变化使用不同时间，比较感应电动势。", "增加线圈匝数，比较电压响应。"],
      misconceptions: "感应电动势不由磁通量绝对值决定，而由变化率决定；开路时可以有感应电动势但没有持续电流。",
      prerequisite: "磁通量、函数斜率和电路"
    }),
    model({
      id: "generator",
      chapterId: "selective-2-2",
      title: "交流发电机",
      category: "电磁学",
      visual: "线圈转动与正弦电压",
      summary: "把线圈转动、磁通量变化和输出电压波形同步显示。",
      hook: "线圈转得越来越快时，输出电压的峰值和频率分别怎么变？",
      model: "线圈在磁场中转动使磁通量周期变化，从而产生随时间变化的感应电动势。",
      relations: ["Φ = BS cosωt", "e ∝ sinωt", "转速影响频率和峰值"],
      explore: ["改变转速，比较波形周期。", "改变线圈匝数和磁场强度，比较峰值电压。"],
      misconceptions: "交流方向改变不等于电流大小始终不变；发电机输出频率与转速有关。",
      prerequisite: "法拉第定律、正弦函数和角速度"
    }),
    model({
      id: "alternating-current",
      chapterId: "selective-2-3",
      title: "交变电流与有效值",
      category: "电磁学",
      visual: "瞬时值与热效应对比",
      summary: "比较交变电流的瞬时值、峰值、周期和有效值，连接波形与热效应。",
      hook: "交流电压不断变化，电器铭牌上的 220 V 到底指什么？",
      model: "有效值是与某一直流电在相同电阻上产生相同热效应的等效值，不等于波形的最大值。",
      relations: ["U有效 = Um/√2", "I有效 = Im/√2", "P = U有效I有效"],
      explore: ["改变波形峰值，比较有效值和平均值。", "把交流和等效直流接入同一电阻，比较热效应。"],
      misconceptions: "正弦交流一个周期平均值为零，但热效应不为零；有效值不是瞬时值。",
      prerequisite: "周期函数、功率和能量"
    }),
    model({
      id: "transformer",
      chapterId: "selective-2-3",
      title: "变压器与远距离输电",
      category: "电磁学",
      visual: "线圈匝数与能量流",
      summary: "改变原副线圈匝数和负载，观察升压、降压、电流变化及输电损耗。",
      hook: "为什么升高输电电压可以减少线路损耗？",
      model: "交变电流产生变化磁通量，在副线圈中感应电压；理想变压器电压比等于匝数比，功率近似守恒。",
      relations: ["U1/U2 = n1/n2", "I1/I2 = n2/n1", "线路损耗 P损 = I^2R"],
      explore: ["保持输送功率，比较不同电压下的线路电流和损耗。", "改变负载，观察理想模型和实际效率。"],
      misconceptions: "变压器不能改变直流电压；升压同时会降低副边电流。",
      prerequisite: "电磁感应、交流电和功率"
    }),
    model({
      id: "lc-oscillation",
      chapterId: "selective-2-4",
      title: "电磁振荡",
      category: "振动与波",
      visual: "电容器与线圈能量交换",
      summary: "显示电场能和磁场能在 LC 回路中的周期转换。",
      hook: "电容器放电后电流为什么不会立刻停止，而是继续给电容器反向充电？",
      model: "LC 回路中电容器电场能和线圈磁场能周期性相互转化，理想情况下总能量守恒。",
      relations: ["T = 2π√(LC)", "ω = 1/√(LC)", "E电 + E磁 = 常量"],
      explore: ["改变 L 或 C，比较振荡周期。", "暂停在能量交换的四个关键状态。"],
      misconceptions: "电流最大时电容器电压为零；电磁振荡不是电荷单向流动。",
      prerequisite: "电容器、电感、简谐振动和能量"
    }),
    model({
      id: "sensor-model",
      chapterId: "selective-2-5",
      title: "传感器的输入与输出",
      category: "综合应用",
      visual: "物理量-电信号转换曲线",
      summary: "把温度、光照、压力等物理量和电阻、电压或电流信号联系起来。",
      hook: "手机如何把光照、加速度和温度变成可读的数字？",
      model: "传感器把非电学物理量转换为可测的电学量，关键是输入-输出特性和测量电路。",
      relations: ["输入物理量 -> 敏感元件 -> 电信号", "灵敏度是曲线斜率", "量程与分辨率有取舍"],
      explore: ["比较光敏电阻、热敏电阻的输入输出曲线。", "改变分压电路，观察同一传感器的输出范围。"],
      misconceptions: "传感器输出不一定与输入成正比；灵敏度高不等于测量范围大。",
      prerequisite: "电阻、电路和图像斜率"
    }),

    model({
      id: "brownian-motion",
      chapterId: "selective-3-1",
      title: "布朗运动与分子热运动",
      category: "热学",
      visual: "微粒随机轨迹与统计分布",
      summary: "用大量微粒的随机碰撞展示宏观温度与微观热运动之间的关系。",
      hook: "看似静止的液体中，微小颗粒为什么会不停地无规则运动？",
      model: "布朗运动是悬浮微粒受到周围分子不平衡撞击产生的宏观表现，温度越高，分子热运动越剧烈。",
      relations: ["随机碰撞", "温度反映分子热运动剧烈程度", "单次轨迹无规则，统计规律可描述"],
      explore: ["改变温度和微粒质量，比较轨迹扩散。", "增加采样数量，观察均方位移的统计趋势。"],
      misconceptions: "布朗运动不是悬浮微粒自身有生命；温度不是单个分子的速度。",
      prerequisite: "概率、平均值和微观粒子"
    }),
    model({
      id: "ideal-gas",
      chapterId: "selective-3-2",
      title: "理想气体模型",
      category: "热学",
      visual: "分子碰撞与宏观状态量",
      summary: "同时显示分子运动、容器碰撞和压强温度体积的宏观变化。",
      hook: "气体压强从哪里来？是分子之间互相推挤，还是撞击器壁的结果？",
      model: "理想气体忽略分子体积和相互作用，压强来自分子对器壁的大量碰撞，宏观状态由 p、V、T 描述。",
      relations: ["pV = nRT", "温度反映平均动能", "压强来自动量交换"],
      explore: ["固定体积加热气体，比较碰撞频率和压强。", "固定温度压缩气体，检查 p-V 关系。"],
      misconceptions: "温度不是气体分子平均速度的简单线性值；理想气体是近似模型。",
      prerequisite: "分子热运动、压强和比例关系"
    }),
    model({
      id: "gas-laws",
      chapterId: "selective-3-2",
      title: "气体实验定律",
      category: "热学",
      visual: "p-V-T 状态图",
      summary: "在等温、等压、等容条件下切换约束，比较气体状态变化。",
      hook: "气球在热水中变大，是因为分子变大了，还是碰撞状态改变了？",
      model: "在一定条件下，气体的压强、体积和温度之间遵循可测的定量关系；每个实验定律都对应一个保持不变的条件。",
      relations: ["等温 pV = 常量", "等压 V/T = 常量", "等容 p/T = 常量"],
      explore: ["只改变一个状态量，观察其他量如何响应。", "切换约束条件，比较三种图像的形状。"],
      misconceptions: "使用气体定律必须明确不变量；摄氏温度不能直接代入比例公式。",
      prerequisite: "理想气体模型、绝对温度和函数图像"
    }),
    model({
      id: "phase-change",
      chapterId: "selective-3-2",
      title: "固体、液体与相变",
      category: "热学",
      visual: "加热曲线与微观结构",
      summary: "用温度-时间曲线显示熔化、沸腾过程中的能量去向和状态变化。",
      hook: "冰在熔化、液体在沸腾时继续吸热，温度为什么可以保持不变？",
      model: "相变过程中吸收的能量主要用于改变分子间作用和结构，温度不一定继续升高。",
      relations: ["Q = cmΔT", "Q = mL", "沸点随外界压强变化"],
      explore: ["比较不同加热功率下的加热曲线。", "改变外界压强，观察沸点变化。"],
      misconceptions: "相变平台不是没有吸热；沸腾温度不是固定的宇宙常数。",
      prerequisite: "内能、温度和能量守恒"
    }),
    model({
      id: "first-law-thermodynamics",
      chapterId: "selective-3-3",
      title: "热力学第一定律",
      category: "热学",
      visual: "内能、热量与功的能量流",
      summary: "用能量流向图区分吸热、放热、对外做功和内能变化。",
      hook: "气体膨胀时温度下降，是因为它把热量全部释放出去了吗？",
      model: "内能变化由热传递和做功共同决定，能量不会凭空产生或消失。",
      relations: ["ΔU = Q + W外", "对外做功时系统能量减少", "状态量与过程量不同"],
      explore: ["对气体加热并允许膨胀，分解能量去向。", "比较等体积和等压过程的能量变化。"],
      misconceptions: "热量和内能不是同一物理量；功和热量是过程量，内能是状态量。",
      prerequisite: "功、能量守恒和气体状态变化"
    }),
    model({
      id: "heat-engine",
      chapterId: "selective-3-3",
      title: "热机与热力学第二定律",
      category: "热学",
      visual: "循环过程与能量流",
      summary: "显示高温热源、低温热源、做功和散热，理解热机效率的限制。",
      hook: "热量为什么不能全部转化为有用功？",
      model: "热机通过循环从高温热源吸热并对外做功，同时向低温热源放热；效率受第二定律限制。",
      relations: ["η = W/Q吸", "W = Q吸 - Q放", "η < 1"],
      explore: ["改变冷热源温度，比较理想效率上限。", "查看一个循环中内能变化回到零的原因。"],
      misconceptions: "热机效率低不是能量守恒失效；循环结束时系统内能回到初态。",
      prerequisite: "内能、功、热量和循环过程"
    }),
    model({
      id: "photoelectric-effect",
      chapterId: "selective-3-4",
      title: "光电效应",
      category: "近代物理",
      visual: "光频率、电子能量与遏止电压",
      summary: "改变光频率和强度，观察光电子最大初动能和光电流的变化。",
      hook: "光越强不一定让电子跑得越快，决定电子能量的关键是什么？",
      model: "光以光子形式与金属电子作用，光电子最大初动能由光频率决定，光强主要影响单位时间光电子数。",
      relations: ["E光子 = hν", "Ekmax = hν - W0", "eUc = Ekmax"],
      explore: ["固定频率改变光强，比较光电流。", "改变频率，寻找截止频率并测量遏止电压。"],
      misconceptions: "光强增大不直接提高单个光电子最大能量；低于截止频率时增加光强也不能产生光电效应。",
      prerequisite: "能量守恒、频率和电势差"
    }),
    model({
      id: "bohr-model",
      chapterId: "selective-3-4",
      title: "玻尔模型与原子能级",
      category: "近代物理",
      visual: "能级跃迁与光谱线",
      summary: "用离散能级和跃迁箭头解释原子吸收、发射光子的频率。",
      hook: "原子为什么只发出某些颜色的光，而不是连续所有颜色？",
      model: "原子能量取离散值，电子在能级间跃迁时吸收或发射特定能量的光子。",
      relations: ["hν = |E高 - E低|", "能级离散", "谱线对应跃迁能量差"],
      explore: ["选择不同跃迁，比较发射光子的频率和波长。", "从谱线反推能级差。"],
      misconceptions: "能级图上的电子轨道不是经典行星轨道；发光不是电子连续损失能量。",
      prerequisite: "光子能量、频率和能量守恒"
    }),
    model({
      id: "matter-wave",
      chapterId: "selective-3-4",
      title: "物质波与波粒二象性",
      category: "近代物理",
      visual: "粒子束与衍射图样",
      summary: "比较粒子动量和德布罗意波长，理解微观粒子为什么会出现波动现象。",
      hook: "电子是粒子，为什么通过晶体后会出现衍射条纹？",
      model: "微观粒子具有与动量相关的物质波性质，粒子性和波动性在不同实验中呈现不同侧面。",
      relations: ["λ = h/p", "动量越大波长越短", "衍射是波动性的证据"],
      explore: ["改变粒子速度，比较德布罗意波长。", "比较电子和宏观小球的衍射可见性。"],
      misconceptions: "物质波不是粒子外面机械振动的介质波；宏观物体波长极短不等于没有公式。",
      prerequisite: "动量、波长和光的衍射"
    }),
    model({
      id: "radioactive-decay",
      chapterId: "selective-3-5",
      title: "放射性衰变与半衰期",
      category: "近代物理",
      visual: "随机衰变与统计衰变曲线",
      summary: "同时展示单个原子核的随机性和大量原子核衰变的统计规律。",
      hook: "单个原子核什么时候衰变无法预测，为什么大量原子核却有稳定的半衰期？",
      model: "放射性衰变对单个原子核是随机事件，对大量原子核服从指数衰减统计规律。",
      relations: ["N = N0(1/2)^(t/T)", "半衰期是统计特征", "衰变常数描述概率速率"],
      explore: ["改变初始原子核数，比较随机波动和平均曲线。", "用半衰期读取样品年龄比例。"],
      misconceptions: "半衰期不是每个原子核的寿命；样品数量越少，统计波动越明显。",
      prerequisite: "指数函数、概率和统计"
    }),
    model({
      id: "binding-energy",
      chapterId: "selective-3-5",
      title: "质量亏损与结合能",
      category: "近代物理",
      visual: "核子质量与能量释放",
      summary: "用核子组成和质量差连接原子核稳定性、结合能和能量释放。",
      hook: "原子核由核子组成，为什么整体质量会小于核子质量之和？",
      model: "核子结合成原子核时释放能量，静质量减少对应结合能；平均结合能可用于比较核稳定性。",
      relations: ["E = Δmc^2", "结合能越大不一定越稳定", "平均结合能反映核子平均束缚程度"],
      explore: ["比较不同质量数的平均结合能曲线。", "模拟裂变和聚变的质量差与能量释放。"],
      misconceptions: "质量亏损不是物质凭空消失；总能量包括静能和其他能量形式。",
      prerequisite: "能量守恒、质量和指数尺度"
    }),
    model({
      id: "nuclear-fission-fusion",
      chapterId: "selective-3-5",
      title: "核裂变与核聚变",
      category: "近代物理",
      visual: "核反应链与能量释放",
      summary: "比较重核裂变、轻核聚变、链式反应和能量释放条件。",
      hook: "裂变和聚变都能释放能量，它们利用的质量变化机制相同吗？",
      model: "重核裂变和轻核聚变都可能使产物平均结合能提高，质量差转化为释放的能量；链式反应还涉及中子增殖。",
      relations: ["质量差 -> 能量", "裂变需要链式条件", "聚变需要高温和约束"],
      explore: ["改变中子繁殖概率，观察链式反应是否持续。", "比较裂变和聚变反应前后的质量与能量。"],
      misconceptions: "核能不是化学燃烧；聚变不是简单把两个原子核强行碰在一起就一定发生。",
      prerequisite: "结合能、质量亏损和概率过程"
    })
  ];

  // The directory is intentionally selective: the remaining models stay available
  // as source material for later development without making the student view noisy.
  const featuredModelIds = new Set([
    "motion-graphs",
    "uniform-acceleration",
    "free-fall",
    "friction-model",
    "newton-laws",

    "projectile-decomposition",
    "circular-motion",
    "centripetal-force",
    "orbital-motion",
    "mechanical-energy",

    "electric-field",
    "electric-conductor",
    "electric-potential",
    "capacitor-energy",
    "ohm-circuit",
    "internal-resistance",
    "electromagnetic-induction-basic",

    "momentum-collision",
    "simple-harmonic-motion",
    "resonance",
    "wave-propagation",
    "wave-superposition",
    "thin-lens-imaging",
    "light-interference-diffraction",

    "magnetic-field",
    "lorentz-force",
    "velocity-selector",
    "faraday-law",
    "alternating-current",
    "transformer",
    "lc-oscillation",

    "gas-laws",
    "first-law-thermodynamics",
    "heat-engine",
    "photoelectric-effect",
    "radioactive-decay",
    "binding-energy"
  ]);

  models.forEach((item) => {
    item.featured = featuredModelIds.has(item.id);
  });

  window.physicsCurriculum = {
    books,
    models,
    directoryModels: models.filter((item) => item.featured),
    selectionNote: "目录只展示适合通过动态关系、图像或模型实验帮助理解的核心内容；其他教材知识保留在课程顺序中，不单独制作可视化模型。",
    categories: ["全部", "运动与力", "能量与动量", "振动与波", "电磁学", "热学", "光学", "近代物理", "综合应用"],
    statusLabels: {
      open: "可视化实验已开放",
      planned: "交互实验开发中"
    }
  };
})();
