(function () {
  "use strict";
  const M = window.CyclotronModel;
  if (!M) throw new Error("CyclotronModel is required");
  const MODES = { orbit: ["轨道扩径", "为什么粒子每次过缝后轨道半径都会增大"], steps: ["能量阶梯", "连续增能为什么只发生在每次穿越缝隙的瞬间"], frequency: ["频率同步", "为什么非相对论回旋频率与轨道半径无关"], boundary: ["相对论失谐", "固定高频源为什么会在高能时逐渐错过加速相位"] };
  const STEPS = [["先分盒内与缝隙", "粒子在哪个区域改变速率，在哪个区域只改变方向？"], ["再锁定频率", "电压为什么必须在每半个回旋周期后反向？"], ["最后查失谐", "相对论效应怎样让粒子逐渐错过加速相位？"]];
  const state = { mode: "orbit", fieldT: 1.2, gapVoltageKv: 30, deeRadiusM: .5, massU: 1.007276, chargeE: 1, initialEnergyKev: 1, crossing: 100, rfRatio: 1, guideStep: 0, showOrbit: true, showField: true, showGap: true, showBoundary: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("cyclotronCanvas"), energy: $("energyChart"), phase: $("phaseChart"), field: $("fieldInput"), voltage: $("voltageInput"), radius: $("radiusInput"), mass: $("massInput"), charge: $("chargeInput"), crossing: $("crossingInput"), ratio: $("ratioInput"), fieldValue: $("fieldValue"), voltageValue: $("voltageValue"), radiusValue: $("radiusValue"), massValue: $("massValue"), chargeValue: $("chargeValue"), crossingValue: $("crossingValue"), ratioValue: $("ratioValue"), orbitToggle: $("showOrbitToggle"), fieldToggle: $("showFieldToggle"), gapToggle: $("showGapToggle"), boundaryToggle: $("showBoundaryToggle"), frequencyMetric: $("frequencyMetric"), energyMetric: $("energyMetric"), orbitMetric: $("orbitMetric"), gainMetric: $("gainMetric"), edgeMetric: $("edgeMetric"), residualMetric: $("residualMetric"), nature: $("natureText"), explanation: $("explanationText"), energyStatus: $("energyStatus"), phaseStatus: $("phaseStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), ectx = R.energy.getContext("2d"), pctx = R.phase.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function drawMain() {
    const s = size(R.main, ctx, 290), p = M.solve(input()), cx = s.width * .5, cy = s.height * .51, radius = Math.min(s.height * .39, s.width * .3), gap = 12;
    bg(ctx, s.width, s.height); ctx.fillStyle = "rgba(100,199,217,.08)"; ctx.strokeStyle = "rgba(100,199,217,.45)"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(cx - gap / 2, cy, radius, Math.PI / 2, Math.PI * 1.5); ctx.lineTo(cx - gap / 2, cy + radius); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.beginPath(); ctx.arc(cx + gap / 2, cy, radius, -Math.PI / 2, Math.PI / 2); ctx.lineTo(cx + gap / 2, cy - radius); ctx.closePath(); ctx.fill(); ctx.stroke();
    if (state.showField) for (let y = cy - radius + 24; y < cy + radius; y += 42) for (let x = cx - radius + 24; x < cx + radius; x += 42) { if ((x - cx) ** 2 + (y - cy) ** 2 > radius ** 2) continue; ctx.strokeStyle = C.cyan; ctx.beginPath(); ctx.arc(x, y, 3.5, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = C.cyan; ctx.beginPath(); ctx.arc(x, y, 1.2, 0, Math.PI * 2); ctx.fill(); }
    if (state.showGap) { line(ctx, cx, cy - radius + 10, cx, cy + radius - 10, C.amber, 2, [5, 5]); const direction = state.crossing % 2 ? -1 : 1; line(ctx, cx - 4, cy - 22, cx - 4, cy + 22, direction > 0 ? C.green : C.red, 3); text(ctx, direction > 0 ? "+ U −" : "− U +", cx, cy - radius - 13, C.amber, 10, "center", 800); }
    if (state.showOrbit && state.crossing > 0) { const maxN = Math.max(1, Math.min(p.crossingsToEdge, state.crossing)), points = Math.min(6000, Math.max(160, maxN * 12)); ctx.strokeStyle = 'rgba(121,217,146,.16)'; ctx.lineWidth = .7; ctx.beginPath(); for (let i = 0; i <= points; i += 1) { const n = maxN * i / points, rr = radius * Math.sqrt((state.initialEnergyKev + n * state.chargeE * state.gapVoltageKv) / (state.initialEnergyKev + Math.max(1, p.crossingsToEdge) * state.chargeE * state.gapVoltageKv)), angle = Math.PI * n, x = cx + rr * Math.cos(angle), y = cy + rr * Math.sin(angle); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.stroke(); const rr = radius * clamp(p.orbitRadiusM / state.deeRadiusM, 0, 1); ctx.strokeStyle = C.green; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(cx, cy, rr, 0, Math.PI * 2); ctx.stroke(); const angle = Math.PI * state.crossing, px = cx + rr * Math.cos(angle), py = cy + rr * Math.sin(angle); ctx.fillStyle = C.amber; ctx.beginPath(); ctx.arc(px, py, 6, 0, Math.PI * 2); ctx.fill(); }
    if (state.showBoundary) { ctx.strokeStyle = p.nonRelativisticValid ? C.green : C.red; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(cx, cy, radius + 7, 0, Math.PI * 2); ctx.stroke(); }
    text(ctx, "D₁", cx - radius * .58, cy + 5, C.text, 13, "center", 800); text(ctx, "D₂", cx + radius * .58, cy + 5, C.text, 13, "center", 800); text(ctx, `N=${state.crossing}`, 22, s.height - 22, C.text, 10); text(ctx, `r=${fmt(p.orbitRadiusM, 3)} m`, s.width - 22, s.height - 22, C.green, 10, "right", 800);
  }
  function axes(k, s, xmax, ymin, ymax) { const p = { l: 44, r: 18, t: 20, b: 30 }, x = v => p.l + v / (xmax || 1) * (s.width - p.l - p.r), y = v => s.height - p.b - (v - ymin) / (ymax - ymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(223,229,223,.3)"); line(k, p.l, y(0), s.width - p.r, y(0), "rgba(223,229,223,.3)"); return { x, y, p }; }
  function drawCharts() {
    const p = M.solve(input()), maxN = Math.max(20, Math.min(1000, p.crossingsToEdge)), ideal = Array.from({ length: 181 }, (_, i) => M.solve({ ...input(), crossing: Math.round(maxN * i / 180) })); let s = size(R.energy, ectx); bg(ectx, s.width, s.height); const a = axes(ectx, s, maxN, 0, Math.max(.01, ideal.at(-1).kineticMev) * 1.08); ectx.strokeStyle = C.amber; ectx.lineWidth = 2; ectx.beginPath(); ideal.forEach((v, i) => i ? ectx.lineTo(a.x(v.crossing), a.y(v.kineticMev)) : ectx.moveTo(a.x(v.crossing), a.y(v.kineticMev))); ectx.stroke(); ectx.strokeStyle = C.cyan; ectx.beginPath(); ideal.forEach((v, i) => { const scaled = v.orbitRadiusM / state.deeRadiusM * ideal.at(-1).kineticMev; i ? ectx.lineTo(a.x(v.crossing), a.y(scaled)) : ectx.moveTo(a.x(v.crossing), a.y(scaled)); }); ectx.stroke(); line(ectx, a.x(Math.min(state.crossing, maxN)), a.p.t, a.x(Math.min(state.crossing, maxN)), s.height - a.p.b, C.green, 1, [4, 4]); text(ectx, "K", 8, 14, C.amber, 9, "left", 800); text(ectx, "r/R", 26, 14, C.cyan, 9, "left", 800);
    const seq = M.crossingSequence(input(), Math.min(1000, Math.max(state.crossing, 80))); s = size(R.phase, pctx); bg(pctx, s.width, s.height); const phaseMax = Math.max(Math.PI, ...seq.map(v => Math.abs(v.phaseErrorRad))), b = axes(pctx, s, Math.max(1, seq.at(-1).crossing), -phaseMax, phaseMax); pctx.strokeStyle = C.violet; pctx.lineWidth = 2; pctx.beginPath(); seq.forEach((v, i) => i ? pctx.lineTo(b.x(v.crossing), b.y(v.phaseErrorRad)) : pctx.moveTo(b.x(v.crossing), b.y(v.phaseErrorRad))); pctx.stroke(); pctx.strokeStyle = C.green; pctx.beginPath(); seq.forEach((v, i) => { const y = v.gainFactor * phaseMax; i ? pctx.lineTo(b.x(v.crossing), b.y(y)) : pctx.moveTo(b.x(v.crossing), b.y(y)); }); pctx.stroke(); line(pctx, b.p.l, b.y(Math.PI / 2), s.width - b.p.r, b.y(Math.PI / 2), C.red, 1, [4, 4]); line(pctx, b.p.l, b.y(-Math.PI / 2), s.width - b.p.r, b.y(-Math.PI / 2), C.red, 1, [4, 4]); text(pctx, "相位误差", 8, 14, C.violet, 9, "left", 800); text(pctx, "增能效率", 60, 14, C.green, 9, "left", 800);
  }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - Number(el.min)) / (Number(el.max) - Number(el.min)) * 100}%`); }
  function render() {
    const p = M.solve(input()), boundary = !p.nonRelativisticValid || state.mode === "boundary", edge = state.crossing >= p.crossingsToEdge;
    R.crossing.max = Math.min(3000, Math.max(100, p.crossingsToEdge)); if (state.crossing > +R.crossing.max) state.crossing = +R.crossing.max; const actual = M.solve(input());
    R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.badge.textContent = edge ? "已到达 D 形盒边缘" : boundary ? "正在检查相位失谐" : "理想同步加速"; R.badge.className = `state-badge ${edge ? "is-edge" : boundary ? "is-boundary" : ""}`;
    const fields = [[R.field, state.fieldT, R.fieldValue, "T", 2], [R.voltage, state.gapVoltageKv, R.voltageValue, "kV", 1], [R.radius, state.deeRadiusM, R.radiusValue, "m", 2], [R.mass, state.massU, R.massValue, "u", 3], [R.charge, state.chargeE, R.chargeValue, "e", 0], [R.crossing, state.crossing, R.crossingValue, "", 0], [R.ratio, state.rfRatio, R.ratioValue, "", 3]]; fields.forEach(([el, value, label, unit, digits]) => { range(el, value); label.textContent = `${fmt(value, digits)}${unit ? ` ${unit}` : ""}`; });
    R.frequencyMetric.textContent = `${fmt(actual.cyclotronFrequencyHz / 1e6)} MHz`; R.energyMetric.textContent = `${fmt(actual.kineticMev)} MeV`; R.orbitMetric.textContent = `${fmt(actual.orbitRadiusM)} m`; R.gainMetric.textContent = `${fmt(actual.gainPerCrossingKev, 1)} keV`; R.edgeMetric.textContent = String(actual.crossingsToEdge); R.residualMetric.textContent = `${fmt(actual.radiusResidualM, 6)} m`; R.nature.textContent = boundary ? `γ=${fmt(actual.gamma, 5)}，实际频率下降` : edge ? "粒子可从盒边引出" : "盒内磁场只改变方向"; R.explanation.textContent = state.mode === "frequency" ? "T=2πm/(qB)" : state.mode === "boundary" ? "frel=fc/γ" : "ΔK=qU"; R.energyStatus.textContent = `N=${state.crossing} · K=${fmt(actual.kineticMev)}MeV`; const seq = M.crossingSequence(input(), Math.min(state.crossing, 1000)), last = seq.at(-1); R.phaseStatus.textContent = Math.abs(last?.phaseErrorRad || 0) < .1 ? "同步" : `错相 ${fmt((last.phaseErrorRad % (2 * Math.PI)) * 180 / Math.PI, 1)}°`; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = state.mode === "boundary" ? "frel=fc/γ" : state.mode === "frequency" ? "f=qB/(2πm)" : "ΔK=qU"; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawMain(); drawCharts();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "orbit") Object.assign(state, { fieldT: 1.2, gapVoltageKv: 30, deeRadiusM: .5, massU: 1.007276, chargeE: 1, crossing: 100, rfRatio: 1 }); if (mode === "steps") Object.assign(state, { crossing: 240, rfRatio: 1 }); if (mode === "frequency") Object.assign(state, { crossing: 320, rfRatio: 1 }); if (mode === "boundary") Object.assign(state, { fieldT: 2.5, gapVoltageKv: 100, deeRadiusM: 1, massU: 1.007276, chargeE: 1, crossing: 500, rfRatio: 1 }); render(); }
  function reset() { Object.assign(state, { mode: "orbit", fieldT: 1.2, gapVoltageKv: 30, deeRadiusM: .5, massU: 1.007276, chargeE: 1, initialEnergyKev: 1, crossing: 100, rfRatio: 1, guideStep: 0, showOrbit: true, showField: true, showGap: true, showBoundary: true, dragging: false }); [[R.orbitToggle, "showOrbit"], [R.fieldToggle, "showField"], [R.gapToggle, "showGap"], [R.boundaryToggle, "showBoundary"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { fieldT: [.1, 3], gapVoltageKv: [1, 200], deeRadiusM: [.05, 1.5], massU: [.1, 20], chargeE: [1, 5], initialEnergyKev: [0, 100], crossing: [0, 3000], rfRatio: [.9, 1.1] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); state.crossing = Math.round(state.crossing); state.chargeE = Math.round(state.chargeE); if (MODES[next.mode]) state.mode = next.mode; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showOrbit", "showField", "showGap", "showBoundary"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.field, "fieldT"], [R.voltage, "gapVoltageKv"], [R.radius, "deeRadiusM"], [R.mass, "massU"], [R.charge, "chargeE"], [R.crossing, "crossing"], [R.ratio, "rfRatio"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.orbitToggle, "showOrbit"], [R.fieldToggle, "showField"], [R.gapToggle, "showGap"], [R.boundaryToggle, "showBoundary"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(), limit = Math.min(3000, Math.max(100, M.solve(input()).crossingsToEdge)); state.crossing = Math.round(clamp((event.clientX - box.left) / box.width * limit, 0, limit)); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.cyclotronLab = { solve: next => M.solve(next), sequence: (next, count) => M.crossingSequence(next, count), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
