(function () {
  "use strict";
  const M = window.DoubleRailModel;
  if (!M) throw new Error("DoubleRailModel is required");
  const MODES = { equal: ["等质量耦合", "为什么两杆最终趋向同一速度"], unequal: ["不等质量", "共同速度为什么由质量加权的总动量决定"], force: ["恒力驱动", "怎样拆分质心加速与相对速度反馈"], fixed: ["固定一杆", "约束力为什么会破坏双杆系统动量守恒"] };
  const STEPS = [["先看相对速度", "为什么两杆同速后感应电流为零？"], ["再分质心运动", "内部安培力为何不改变自由双杆总动量？"], ["最后核能量", "减少的相对运动动能转化成了什么？"]];
  const state = { mode: "equal", mass1Kg: .5, mass2Kg: .5, lengthM: .5, fieldT: .8, resistanceOhm: .8, initialV1Ms: 4, initialV2Ms: 0, force1N: 0, force2N: 0, initialGapM: 8, timeS: 1.25, guideStep: 0, showVectors: true, showCurrent: true, showCom: true, showLedger: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("doubleRailCanvas"), velocityChart: $("velocityChart"), ledgerChart: $("ledgerChart"), mass1: $("mass1Input"), mass2: $("mass2Input"), v1: $("velocity1Input"), v2: $("velocity2Input"), f1: $("force1Input"), f2: $("force2Input"), field: $("fieldInput"), resistance: $("resistanceInput"), length: $("lengthInput"), time: $("timeInput"), mass1Value: $("mass1Value"), mass2Value: $("mass2Value"), v1Value: $("velocity1Value"), v2Value: $("velocity2Value"), f1Value: $("force1Value"), f2Value: $("force2Value"), fieldValue: $("fieldValue"), resistanceValue: $("resistanceValue"), lengthValue: $("lengthValue"), timeValue: $("timeValue"), vectors: $("showVectorsToggle"), current: $("showCurrentToggle"), com: $("showComToggle"), ledger: $("showLedgerToggle"), velocity1Metric: $("velocity1Metric"), velocity2Metric: $("velocity2Metric"), relativeMetric: $("relativeMetric"), currentMetric: $("currentMetric"), momentumMetric: $("momentumMetric"), residualMetric: $("residualMetric"), nature: $("natureText"), explanation: $("explanationText"), responseStatus: $("responseStatus"), ledgerStatus: $("ledgerStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), hint: $("stageHint"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), vctx = R.velocityChart.getContext("2d"), lctx = R.ledgerChart.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, color, label) { line(k, x1, y1, x2, y2, color, 3); const a = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = color; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 9 * Math.cos(a - .5), y2 - 9 * Math.sin(a - .5)); k.lineTo(x2 - 9 * Math.cos(a + .5), y2 - 9 * Math.sin(a + .5)); k.fill(); if (label) text(k, label, x2 + 6, y2 - 7, color, 10, "left", 800); }
  function drawMain() {
    const s = size(R.main, ctx, 270), p = M.solve(input()), left = 65, right = s.width - 55, top = 80, bottom = s.height - 70;
    bg(ctx, s.width, s.height); for (let y = top + 22; y < bottom; y += 50) for (let x = left + 22; x < right; x += 52) { ctx.strokeStyle = C.cyan; ctx.beginPath(); ctx.arc(x, y, 4, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = C.cyan; ctx.beginPath(); ctx.arc(x, y, 1.4, 0, Math.PI * 2); ctx.fill(); }
    line(ctx, left, top, right, top, C.text, 5); line(ctx, left, bottom, right, bottom, C.text, 5);
    const span = right - left - 100, centerShift = clamp((p.displacement1M + p.displacement2M) * .02, -.15, .15) * span, gapPx = clamp(p.separationM / state.initialGapM, .03, 1) * span * .5, center = (left + right) / 2 + centerShift, x1 = center - gapPx / 2, x2 = center + gapPx / 2;
    line(ctx, x1, top + 3, x1, bottom - 3, C.amber, 9); line(ctx, x2, top + 3, x2, bottom - 3, C.violet, 9); text(ctx, "1", x1, top - 13, C.amber, 12, "center", 800); text(ctx, state.mode === "fixed" ? "2 · 固定" : "2", x2, top - 13, C.violet, 12, "center", 800);
    if (state.showCurrent && Math.abs(p.currentA) > 1e-6) { const dir = Math.sign(p.currentA); arrow(ctx, x1, dir > 0 ? bottom - 30 : top + 30, x1, dir > 0 ? top + 30 : bottom - 30, C.green, "I"); arrow(ctx, x1 + 20, top, x2 - 20, top, C.green, ""); }
    if (state.showVectors) { const drawV = (x, value, color, label, y) => { const len = clamp(Math.abs(value) * 18, 16, 100), sign = value < 0 ? -1 : 1; arrow(ctx, x, y, x + sign * len, y, color, label); }; drawV(x1, p.velocity1Ms, C.amber, "v₁", (top + bottom) / 2 - 20); if (state.mode !== "fixed") drawV(x2, p.velocity2Ms, C.violet, "v₂", (top + bottom) / 2 + 20); const f = clamp(Math.abs(p.magneticForceN) * 55, 18, 80), sign = Math.sign(p.relativeVelocityMs) || 1; arrow(ctx, x1, bottom + 27, x1 - sign * f, bottom + 27, C.red, "F磁1"); arrow(ctx, x2, bottom + 27, x2 + sign * f, bottom + 27, C.red, state.mode === "fixed" ? "F磁2+约束" : "F磁2"); }
    if (state.showCom && state.mode !== "fixed") { const comX = (state.mass1Kg * x1 + state.mass2Kg * x2) / (state.mass1Kg + state.mass2Kg); line(ctx, comX, top - 2, comX, bottom + 2, C.cyan, 1, [4, 4]); text(ctx, "质心", comX, 48, C.cyan, 9, "center", 700); }
    text(ctx, `t=${fmt(p.timeS, 2)} s`, left, s.height - 23, C.text, 10); text(ctx, `Δv=${fmt(p.relativeVelocityMs)} m/s`, right, s.height - 23, C.green, 10, "right", 800); if (p.contact) text(ctx, "两杆已接触 · 解析模型在此停止", (left + right) / 2, s.height - 23, C.red, 10, "center", 800);
  }
  function axes(k, s, xmax, ymin, ymax) { const p = { l: 44, r: 18, t: 20, b: 30 }, x = v => p.l + v / xmax * (s.width - p.l - p.r), y = v => s.height - p.b - (v - ymin) / (ymax - ymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(223,229,223,.3)"); line(k, p.l, y(0), s.width - p.r, y(0), "rgba(223,229,223,.3)"); return { x, y, p }; }
  function drawCharts() {
    const p = M.solve(input()), series = M.series(input(), 10, 180); let s = size(R.velocityChart, vctx); bg(vctx, s.width, s.height); const all = series.flatMap(v => [v.velocity1Ms, v.velocity2Ms, v.relativeVelocityMs]), min = Math.min(-.1, ...all) * 1.1, max = Math.max(.1, ...all) * 1.1, a = axes(vctx, s, 10, min, max); [["velocity1Ms", C.amber], ["velocity2Ms", C.violet], ["relativeVelocityMs", C.green]].forEach(([key, color]) => { vctx.strokeStyle = color; vctx.lineWidth = 2; vctx.beginPath(); series.forEach((v, i) => i ? vctx.lineTo(a.x(v.requestedTimeS), a.y(v[key])) : vctx.moveTo(a.x(v.requestedTimeS), a.y(v[key]))); vctx.stroke(); }); line(vctx, a.x(state.timeS), a.p.t, a.x(state.timeS), s.height - a.p.b, C.cyan, 1, [4, 4]); text(vctx, "v₁", 8, 14, C.amber, 9, "left", 800); text(vctx, "v₂", 27, 14, C.violet, 9, "left", 800); text(vctx, "Δv", 46, 14, C.green, 9, "left", 800);
    s = size(R.ledgerChart, lctx); bg(lctx, s.width, s.height); const values = state.showLedger ? [["初动能", p.kinetic0J, C.amber], ["当前动能", p.kineticJ, C.cyan], ["外力功", p.externalWorkJ, C.green], ["焦耳热", p.resistorHeatJ, C.red]] : [], scale = Math.max(.01, ...values.map(v => Math.abs(v[1]))), x0 = 88; values.forEach((v, i) => { const y = 42 + i * 40, width = Math.abs(v[1]) / scale * (s.width - 140); text(lctx, v[0], 15, y + 4, C.text, 9); lctx.fillStyle = v[2]; lctx.fillRect(x0, y - 8, width, 16); text(lctx, `${fmt(v[1])} J`, s.width - 15, y + 4, v[2], 9, "right", 800); }); text(lctx, `Δp残差 ${fmt(p.momentumResidualKgmS, 6)} kg·m/s`, s.width - 15, 14, C.green, 9, "right", 700);
  }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - Number(el.min)) / (Number(el.max) - Number(el.min)) * 100}%`); }
  function render() {
    const p = M.solve(input()), mode = MODES[state.mode], synced = Math.abs(p.relativeVelocityMs) < .05;
    R.modeTitle.textContent = mode[0]; R.modeGoal.textContent = mode[1]; R.badge.textContent = p.contact ? "两杆接触，模型停止" : synced ? "两杆已接近同速" : state.mode === "fixed" ? "约束吸收外力冲量" : "相对运动正在衰减"; R.badge.className = `state-badge ${p.contact ? "is-contact" : synced ? "is-synced" : ""}`;
    const fields = [[R.mass1, state.mass1Kg, R.mass1Value, "kg"], [R.mass2, state.mass2Kg, R.mass2Value, "kg"], [R.v1, state.initialV1Ms, R.v1Value, "m/s"], [R.v2, state.initialV2Ms, R.v2Value, "m/s"], [R.f1, state.force1N, R.f1Value, "N"], [R.f2, state.force2N, R.f2Value, "N"], [R.field, state.fieldT, R.fieldValue, "T"], [R.resistance, state.resistanceOhm, R.resistanceValue, "Ω"], [R.length, state.lengthM, R.lengthValue, "m"], [R.time, state.timeS, R.timeValue, "s"]]; fields.forEach(([el, value, label, unit]) => { range(el, value); label.textContent = `${fmt(value, 2)} ${unit}`; });
    R.velocity1Metric.textContent = `${fmt(p.velocity1Ms)} m/s`; R.velocity2Metric.textContent = `${fmt(p.velocity2Ms)} m/s`; R.relativeMetric.textContent = `${fmt(p.relativeVelocityMs)} m/s`; R.currentMetric.textContent = `${fmt(p.currentA)} A`; R.momentumMetric.textContent = `${fmt(p.momentumKgmS)} kg·m/s`; R.residualMetric.textContent = `${fmt(p.energyResidualJ, 6)} J`; R.nature.textContent = p.contact ? "接触后需切换碰撞模型" : state.mode === "fixed" ? "固定杆的约束力属于系统外力" : "内部磁力等大反向"; R.explanation.textContent = state.mode === "fixed" ? "Δp系统=J约束" : "Δp系统=(F₁+F₂)t"; R.responseStatus.textContent = `t=${fmt(p.timeS, 2)}s · τ=${fmt(p.tauS, 2)}s`; R.ledgerStatus.textContent = Math.abs(p.energyResidualJ) < 1e-8 && Math.abs(p.momentumResidualKgmS) < 1e-8 ? "守恒闭合" : "检查残差"; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = state.mode === "fixed" ? "m₁dv₁/dt=F₁−kv₁" : "ε=BL(v₁−v₂)"; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawMain(); drawCharts();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "equal") Object.assign(state, { mass1Kg: .5, mass2Kg: .5, initialV1Ms: 4, initialV2Ms: 0, force1N: 0, force2N: 0, timeS: 1.25 }); if (mode === "unequal") Object.assign(state, { mass1Kg: .5, mass2Kg: 1.5, initialV1Ms: 4, initialV2Ms: 0, force1N: 0, force2N: 0, timeS: 1.88 }); if (mode === "force") Object.assign(state, { mass1Kg: .5, mass2Kg: 1.5, initialV1Ms: 0, initialV2Ms: 0, force1N: 1.2, force2N: 0, timeS: 2 }); if (mode === "fixed") Object.assign(state, { mass1Kg: .5, mass2Kg: .5, initialV1Ms: 4, initialV2Ms: 0, force1N: 0, force2N: 0, timeS: 2.5 }); render(); }
  function reset() { Object.assign(state, { mode: "equal", mass1Kg: .5, mass2Kg: .5, lengthM: .5, fieldT: .8, resistanceOhm: .8, initialV1Ms: 4, initialV2Ms: 0, force1N: 0, force2N: 0, initialGapM: 8, timeS: 1.25, guideStep: 0, showVectors: true, showCurrent: true, showCom: true, showLedger: true, dragging: false }); [[R.vectors, "showVectors"], [R.current, "showCurrent"], [R.com, "showCom"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { mass1Kg: [.1, 5], mass2Kg: [.1, 5], lengthM: [.1, 1.5], fieldT: [0, 2], resistanceOhm: [.05, 10], initialV1Ms: [-10, 10], initialV2Ms: [-10, 10], force1N: [-10, 10], force2N: [-10, 10], initialGapM: [.3, 12], timeS: [0, 10] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); if (MODES[next.mode]) state.mode = next.mode; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showVectors", "showCurrent", "showCom", "showLedger"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.mass1, "mass1Kg"], [R.mass2, "mass2Kg"], [R.v1, "initialV1Ms"], [R.v2, "initialV2Ms"], [R.f1, "force1N"], [R.f2, "force2N"], [R.field, "fieldT"], [R.resistance, "resistanceOhm"], [R.length, "lengthM"], [R.time, "timeS"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.vectors, "showVectors"], [R.current, "showCurrent"], [R.com, "showCom"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(); state.timeS = clamp((event.clientX - box.left) / box.width * 10, 0, 10); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.doubleRailLab = { solve: next => M.solve(next), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
