(function () {
  const model = window.OrbitalModel;
  if (!model) throw new Error("OrbitalModel is required");
  const state = { mode:"circular", altitudeKm:400, targetKm:35793, speedRatio:1, progress:0, running:false, rate:.5, guideStep:0, showVelocity:true, showGravity:true, showEnergy:true, showScale:true, showTheory:true, lastTime:0 };
  const refs = {
    canvas:document.getElementById("orbitalCanvas"),relationChart:document.getElementById("relationChart"),energyChart:document.getElementById("energyChart"),
    sceneTabs:Array.from(document.querySelectorAll(".scene-tab[data-mode]")),routeSteps:Array.from(document.querySelectorAll(".route-step")),targetSection:document.getElementById("targetSection"),impulseSection:document.getElementById("impulseSection"),
    altitudeInput:document.getElementById("altitudeInput"),targetInput:document.getElementById("targetInput"),speedRatioInput:document.getElementById("speedRatioInput"),progressInput:document.getElementById("progressInput"),
    altitudeValue:document.getElementById("altitudeValue"),targetValue:document.getElementById("targetValue"),speedRatioValue:document.getElementById("speedRatioValue"),playbackValue:document.getElementById("playbackValue"),
    modeTitle:document.getElementById("modeTitle"),modeGoal:document.getElementById("modeGoal"),stateBadge:document.getElementById("stateBadge"),stageHint:document.getElementById("stageHint"),
    orbitMetric:document.getElementById("orbitMetric"),speedMetric:document.getElementById("speedMetric"),periodMetric:document.getElementById("periodMetric"),gravityMetric:document.getElementById("gravityMetric"),energyMetric:document.getElementById("energyMetric"),apsisMetric:document.getElementById("apsisMetric"),orbitNature:document.getElementById("orbitNature"),orbitExplanation:document.getElementById("orbitExplanation"),
    relationTitle:document.getElementById("relationTitle"),relationStatus:document.getElementById("relationStatus"),energyTitle:document.getElementById("energyTitle"),energyStatus:document.getElementById("energyStatus"),stepIndex:document.getElementById("stepIndex"),stepTitle:document.getElementById("stepTitle"),stepPrompt:document.getElementById("stepPrompt"),formulaReadout:document.getElementById("formulaReadout"),
    playButton:document.getElementById("playButton"),pauseButton:document.getElementById("pauseButton"),keyButton:document.getElementById("keyButton"),resetButton:document.getElementById("resetButton"),guideButton:document.getElementById("guideButton"),stepButton:document.getElementById("stepButton"),focusButton:document.getElementById("focusButton"),fullscreenButton:document.getElementById("fullscreenButton"),guideDialog:document.getElementById("guideDialog"),
    presets:Array.from(document.querySelectorAll("[data-preset]")),rates:Array.from(document.querySelectorAll("[data-rate]")),showVelocityToggle:document.getElementById("showVelocityToggle"),showGravityToggle:document.getElementById("showGravityToggle"),showEnergyToggle:document.getElementById("showEnergyToggle"),showScaleToggle:document.getElementById("showScaleToggle"),showTheoryToggle:document.getElementById("showTheoryToggle")
  };
  const ctx=refs.canvas.getContext("2d"),relationCtx=refs.relationChart.getContext("2d"),energyCtx=refs.energyChart.getContext("2d");
  const modes = {
    circular:{title:"圆轨道标度",goal:"万有引力恰好提供向心加速度，轨道半径决定速度与周期",hint:"拖动高度，比较速度、周期和机械能"},
    synchronous:{title:"同步轨道",goal:"轨道周期匹配地球恒星日只是地球静止轨道的必要条件",hint:"寻找周期为 23 h 56 min 的轨道高度"},
    transfer:{title:"霍曼转移",goal:"两次瞬时切向变速把卫星从一条圆轨道送入另一条圆轨道",hint:"拖动过程，追踪近地点加速、转移椭圆和远地点圆化"},
    escape:{title:"变速与逃逸",goal:"切向速度改变比机械能、偏心率和轨道是否闭合",hint:"跨过圆轨道速度与 √2 倍逃逸阈值"}
  };
  const guide=[
    {title:"先平衡引力与向心需求",prompt:"同一高度若速度不是圆轨道速度，卫星还能保持圆轨道吗？"},
    {title:"再核对轨道能量",prompt:"高轨道速度更小，为什么它的总机械能反而更大？"},
    {title:"最后施加切向变速",prompt:"一次切向加速为什么先抬高轨道另一侧，而不是立刻整体升高？"}
  ];
  const colors={cyan:"#67c6d8",green:"#7bd898",amber:"#f0b84d",red:"#ff776c",violet:"#b79ae6",muted:"#8d9992",white:"#dfe5df"};
  function fmt(value,d=2){return Number(value).toFixed(d)}
  function setCanvasSize(canvas,context){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(300,Math.round(r.width)),h=Math.max(170,Math.round(r.height));if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d}context.setTransform(d,0,0,d,0,0);return{width:w,height:h}}
  function setProgress(input){const p=(Number(input.value)-Number(input.min))/(Number(input.max)-Number(input.min))*100;input.style.setProperty("--range-progress",p+"%")}
  function current(){
    const circular=model.circularState(state.altitudeKm);
    const sync=model.synchronousState();
    const transfer=model.hohmannTransfer(state.altitudeKm,state.targetKm);
    const impulse=model.tangentialImpulseState(state.altitudeKm,state.speedRatio);
    return{circular,sync,transfer,impulse}
  }
  function arrow(context,x1,y1,x2,y2,color,label){const a=Math.atan2(y2-y1,x2-x1);context.save();context.strokeStyle=color;context.fillStyle=color;context.lineWidth=2.5;context.beginPath();context.moveTo(x1,y1);context.lineTo(x2,y2);context.stroke();context.beginPath();context.moveTo(x2,y2);context.lineTo(x2-8*Math.cos(a-.5),y2-8*Math.sin(a-.5));context.lineTo(x2-8*Math.cos(a+.5),y2-8*Math.sin(a+.5));context.closePath();context.fill();context.font="700 10px ui-monospace,monospace";context.fillText(label,x2+6,y2-6);context.restore()}
  function drawGrid(context,w,h){context.fillStyle="#070c10";context.fillRect(0,0,w,h);context.fillStyle="rgba(223,229,223,.34)";for(let i=0;i<44;i++){const x=(i*83%997)/997*w,y=(i*151%613)/613*h,r=i%7===0?1.4:.7;context.beginPath();context.arc(x,y,r,0,Math.PI*2);context.fill()}}
  function visualRadius(altitudeKm,maxPx){return Math.min(maxPx,46+Math.log1p(Math.max(0,altitudeKm)/800)*29)}
  function earth(context,cx,cy,r,rotation=0){const g=context.createRadialGradient(cx-r*.25,cy-r*.3,r*.1,cx,cy,r);g.addColorStop(0,"#75b8c8");g.addColorStop(.58,"#245b76");g.addColorStop(1,"#102c42");context.fillStyle=g;context.beginPath();context.arc(cx,cy,r,0,Math.PI*2);context.fill();context.save();context.translate(cx,cy);context.rotate(rotation);context.fillStyle="rgba(123,216,152,.62)";context.beginPath();context.ellipse(-r*.25,-r*.15,r*.28,r*.16,.4,0,Math.PI*2);context.ellipse(r*.2,r*.18,r*.3,r*.13,-.35,0,Math.PI*2);context.fill();context.restore();context.strokeStyle="rgba(103,198,216,.28)";context.lineWidth=5;context.beginPath();context.arc(cx,cy,r+3,0,Math.PI*2);context.stroke()}
  function satellite(context,x,y,angle,color=colors.white){context.save();context.translate(x,y);context.rotate(angle);context.fillStyle=color;context.fillRect(-7,-4,14,8);context.fillStyle=colors.cyan;context.fillRect(-18,-6,9,12);context.fillRect(9,-6,9,12);context.restore()}
  function drawCircular(d,w,h,syncMode=false){const cx=w*.49,cy=h*.53,earthR=Math.min(54,h*.16),alt=syncMode?d.sync.altitudeKm:d.circular.altitudeKm,orbitR=visualRadius(alt,Math.min(w*.38,h*.42)),phase=state.progress*Math.PI*2-Math.PI/2;earth(ctx,cx,cy,earthR,syncMode?state.progress*Math.PI*2:0);ctx.strokeStyle=syncMode?colors.green:colors.cyan;ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,orbitR,0,Math.PI*2);ctx.stroke();if(syncMode){const leoR=visualRadius(400,orbitR-8);ctx.strokeStyle="rgba(103,198,216,.3)";ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(cx,cy,leoR,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}const x=cx+Math.cos(phase)*orbitR,y=cy+Math.sin(phase)*orbitR;satellite(ctx,x,y,phase+Math.PI/2,syncMode?colors.green:colors.white);if(state.showVelocity)arrow(ctx,x,y,x-Math.sin(phase)*54,y+Math.cos(phase)*54,colors.cyan,"v");if(state.showGravity)arrow(ctx,x,y,x+(cx-x)*.38,y+(cy-y)*.38,colors.amber,"g");if(state.showScale){ctx.fillStyle=colors.muted;ctx.font="10px ui-monospace,monospace";ctx.fillText(syncMode?"同步半径 42164 km":"地球半径 6371 km",18,22);ctx.fillText("轨道显示采用压缩尺度",18,h-18)}}
  function drawTransfer(d,w,h){const t=d.transfer,cx=w*.47,cy=h*.52,earthR=Math.min(50,h*.15),outerAlt=Math.max(t.start.altitudeKm,t.target.altitudeKm),outerPx=visualRadius(outerAlt,Math.min(w*.39,h*.42)),innerAlt=Math.min(t.start.altitudeKm,t.target.altitudeKm),innerPx=visualRadius(innerAlt,outerPx-18),aPx=(outerPx+innerPx)/2,cPx=(outerPx-innerPx)/2;earth(ctx,cx,cy,earthR);ctx.strokeStyle="rgba(103,198,216,.42)";ctx.setLineDash([5,5]);for(const r of [innerPx,outerPx]){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke()}ctx.setLineDash([]);ctx.strokeStyle=colors.violet;ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(cx-cPx,cy,aPx,Math.sqrt(innerPx*outerPx),0,0,Math.PI*2);ctx.stroke();const theta=state.progress*Math.PI,r=aPx*(1-(cPx/aPx)**2)/(1+(cPx/aPx)*Math.cos(theta)),x=cx+r*Math.cos(theta),y=cy-r*Math.sin(theta);satellite(ctx,x,y,theta-Math.PI/2,colors.violet);if(state.showVelocity)arrow(ctx,x,y,x+Math.sin(theta)*48,y+Math.cos(theta)*48,colors.cyan,"v");ctx.fillStyle=colors.amber;ctx.font="700 10px ui-monospace,monospace";ctx.fillText("Δv₁",cx+innerPx+8,cy-8);ctx.fillText("Δv₂",cx-outerPx-28,cy-8);ctx.fillStyle=colors.muted;ctx.font="10px ui-monospace,monospace";ctx.fillText("半椭圆转移 · 两个焦点中只有一个是地心",18,h-18)}
  function drawImpulse(d,w,h){const q=d.impulse,cx=w*.48,cy=h*.53,earthR=Math.min(53,h*.16),basePx=visualRadius(state.altitudeKm,Math.min(w*.32,h*.37));earth(ctx,cx,cy,earthR);ctx.strokeStyle="rgba(103,198,216,.3)";ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(cx,cy,basePx,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);let x,y,angle;if(q.isBound){const perAlt=Math.max(0,q.perigeeAltitudeKm),apoAlt=Math.max(0,q.apogeeAltitudeKm),perPx=visualRadius(perAlt,Math.min(w*.35,h*.4)),apoPx=visualRadius(apoAlt,Math.min(w*.41,h*.44)),a=(perPx+apoPx)/2,c=(apoPx-perPx)/2;ctx.strokeStyle=q.impactsEarth?colors.red:colors.violet;ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(cx-c,cy,a,Math.sqrt(Math.max(8,perPx*apoPx)),0,0,Math.PI*2);ctx.stroke();const theta=state.progress*Math.PI*2,r=a*(1-(c/a)**2)/(1+(c/a)*Math.cos(theta));x=cx+r*Math.cos(theta);y=cy-r*Math.sin(theta);angle=theta-Math.PI/2}else{const p=state.progress,curve=basePx+p*w*.42;x=cx+curve;y=cy-curve*.32-30*Math.sin(p*Math.PI);angle=-.3;ctx.strokeStyle=colors.red;ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(cx+basePx,cy);ctx.quadraticCurveTo(cx+w*.28,cy-h*.18,cx+w*.46,cy-h*.28);ctx.stroke()}satellite(ctx,x,y,angle,q.classification==="escape"?colors.red:colors.white);if(state.showVelocity)arrow(ctx,x,y,x+50*Math.cos(angle),y+50*Math.sin(angle),colors.cyan,"v");ctx.fillStyle=q.classification==="impact"?colors.red:colors.muted;ctx.font="10px ui-monospace,monospace";ctx.fillText("v/vc = "+fmt(state.speedRatio,3)+" · vesc/vc = √2",18,h-18)}
  function drawScene(){const {width:w,height:h}=setCanvasSize(refs.canvas,ctx),d=current();drawGrid(ctx,w,h);if(state.mode==="transfer")drawTransfer(d,w,h);else if(state.mode==="escape")drawImpulse(d,w,h);else drawCircular(d,w,h,state.mode==="synchronous")}
  function axes(context,w,h,xLabel,yLabel){const p={l:42,r:14,t:18,b:30},pw=w-p.l-p.r,ph=h-p.t-p.b;context.strokeStyle="rgba(223,229,223,.13)";context.fillStyle=colors.muted;context.font="9px ui-monospace,monospace";for(let i=0;i<=4;i++){const x=p.l+pw*i/4,y=p.t+ph*i/4;context.beginPath();context.moveTo(x,p.t);context.lineTo(x,p.t+ph);context.stroke();context.beginPath();context.moveTo(p.l,y);context.lineTo(p.l+pw,y);context.stroke()}context.fillText(yLabel,p.l,10);context.textAlign="right";context.fillText(xLabel,w-5,h-8);context.textAlign="left";return{p,pw,ph}}
  function drawRelation(){const {width:w,height:h}=setCanvasSize(refs.relationChart,relationCtx),d=current();relationCtx.clearRect(0,0,w,h);relationCtx.fillStyle="#101512";relationCtx.fillRect(0,0,w,h);const a=axes(relationCtx,w,h,"h / 10³ km","归一化");const points=model.radiusScan(100,50000),x=v=>a.p.l+v/50000*a.pw,y=v=>a.p.t+(1-v)*a.ph;function line(key,scale,color){relationCtx.strokeStyle=color;relationCtx.lineWidth=2;relationCtx.beginPath();points.forEach((p,i)=>{const yy=y(p[key]/scale);i?relationCtx.lineTo(x(p.altitudeKm),yy):relationCtx.moveTo(x(p.altitudeKm),yy)});relationCtx.stroke()}if(state.showTheory){line("speedKms",points[0].speedKms,colors.cyan);line("periodHours",points.at(-1).periodHours,colors.violet)}const currentAlt=state.mode==="synchronous"?d.sync.altitudeKm:state.altitudeKm;relationCtx.fillStyle=colors.amber;relationCtx.beginPath();relationCtx.arc(x(Math.min(50000,currentAlt)),y(model.circularState(currentAlt).speedKms/points[0].speedKms),4,0,Math.PI*2);relationCtx.fill();relationCtx.fillStyle=colors.cyan;relationCtx.fillText("v/v₀",a.p.l+5,a.p.t+13);relationCtx.fillStyle=colors.violet;relationCtx.fillText("T/Tmax",a.p.l+48,a.p.t+13)}
  function drawEnergy(){const {width:w,height:h}=setCanvasSize(refs.energyChart,energyCtx),d=current();energyCtx.clearRect(0,0,w,h);energyCtx.fillStyle="#101512";energyCtx.fillRect(0,0,w,h);let K,U,E,label;if(state.mode==="escape"){K=d.impulse.speedMps**2/2;U=-model.EARTH.mu/d.impulse.circular.radiusM;E=d.impulse.specificEnergyJkg;label="变速后"}else if(state.mode==="transfer"){K=d.transfer.transferPerigeeSpeedMps**2/2;U=-model.EARTH.mu/d.transfer.inner.radiusM;E=d.transfer.transferSpecificEnergyJkg;label="转移轨道"}else{const q=state.mode==="synchronous"?d.sync:d.circular;K=q.kineticJkg;U=q.potentialJkg;E=q.totalJkg;label=state.mode==="synchronous"?"同步轨道":"当前圆轨道"}const max=Math.max(Math.abs(U),Math.abs(K),1),zero=h*.52,scale=(h*.38)/max,bars=[["K",K,colors.cyan],["U",U,colors.red],["ε",E,colors.amber]];energyCtx.strokeStyle="rgba(223,229,223,.25)";energyCtx.beginPath();energyCtx.moveTo(30,zero);energyCtx.lineTo(w-18,zero);energyCtx.stroke();bars.forEach((b,i)=>{const x=45+i*(w-90)/3,bh=Math.abs(b[1])*scale;energyCtx.fillStyle=b[2];energyCtx.fillRect(x,b[1]>=0?zero-bh:zero,Math.min(52,(w-110)/3),bh);energyCtx.fillStyle=colors.white;energyCtx.font="10px ui-monospace,monospace";energyCtx.fillText(b[0],x,zero+(b[1]>=0?-bh-7:bh+14))});energyCtx.fillStyle=colors.muted;energyCtx.fillText(label,12,16);if(state.showEnergy)energyCtx.fillText("单位 MJ/kg · 正负号保留",12,h-10)}
  function description(d){if(state.mode==="synchronous")return{badge:"同步 · 35793 km",cls:"is-sync",orbit:"地球同步圆轨道",speed:d.sync.speedKms,period:d.sync.periodS,g:d.sync.gravityMps2,E:d.sync.totalJkg,apsis:"35793 / 35793 km",nature:"周期匹配不等于一定静止",explain:"还需圆形、赤道面内且与地球自转同向",formula:"r_sync = [μ(T/2π)²]¹ᐟ³ = 42164 km"};
    if(state.mode==="transfer"){const t=d.transfer,p=state.progress<.02?"第一次变速":state.progress>.98?"第二次变速":"转移椭圆";return{badge:"霍曼转移 · "+fmt(t.transferTimeHours,2)+" h",cls:"is-transfer",orbit:p,speed:(t.transferPerigeeSpeedMps+(t.transferApogeeSpeedMps-t.transferPerigeeSpeedMps)*state.progress)/1000,period:t.transferTimeS*2,g:model.EARTH.mu/(t.semiMajorM**2),E:t.transferSpecificEnergyJkg,apsis:fmt(t.inner.altitudeKm,0)+" / "+fmt(t.outer.altitudeKm,0)+" km",nature:"两次切向变速连接圆轨道",explain:"升轨先在近地点加速，到远地点再次加速圆化",formula:"Δv总 = "+fmt(t.totalDeltaVMps/1000,3)+" km/s"}}
    if(state.mode==="escape"){const q=d.impulse,names={circular:"圆轨道",elliptic:"椭圆轨道",impact:"轨道撞地",escape:"非束缚逃逸"};return{badge:names[q.classification]+" · "+fmt(state.speedRatio,3)+" vc",cls:q.classification==="impact"?"is-impact":q.classification==="escape"?"is-escape":"is-circular",orbit:names[q.classification],speed:q.speedMps/1000,period:q.isBound?2*Math.PI*Math.sqrt(q.semiMajorM**3/model.EARTH.mu):Infinity,g:q.circular.gravityMps2,E:q.specificEnergyJkg,apsis:fmt(q.perigeeAltitudeKm,0)+" / "+(Number.isFinite(q.apogeeAltitudeKm)?fmt(q.apogeeAltitudeKm,0):"∞")+" km",nature:q.classification==="escape"?"ε ≥ 0，轨道不再闭合":q.classification==="impact"?"近地点低于地表":q.classification==="circular"?"v = vc，轨道保持圆形":"ε < 0，形成椭圆轨道",explain:q.classification==="escape"?"达到逃逸条件后无需持续推力来维持逃逸":"一次切向变速同时改变能量和角动量",formula:"ε = v²/2−μ/r = "+fmt(q.specificEnergyJkg/1e6,2)+" MJ/kg"}}
    const q=d.circular;return{badge:(q.altitudeKm<2000?"LEO":"圆轨道")+" · "+fmt(q.altitudeKm,0)+" km",cls:"is-circular",orbit:"圆轨道",speed:q.speedKms,period:q.periodS,g:q.gravityMps2,E:q.totalJkg,apsis:fmt(q.altitudeKm,0)+" / "+fmt(q.altitudeKm,0)+" km",nature:"Fᵍ 提供向心力",explain:"高度增加时圆轨道速度减小，但周期增大",formula:"vc = √(μ/r) = "+fmt(q.speedKms,3)+" km/s"}}
  function syncUI(){const d=current(),info=description(d),mode=modes[state.mode],task=guide[state.guideStep];refs.altitudeValue.textContent=fmt(state.altitudeKm,0)+" km";refs.targetValue.textContent=fmt(state.targetKm,0)+" km";refs.speedRatioValue.textContent=fmt(state.speedRatio,3)+" vᶜ";refs.playbackValue.textContent=(state.running?"运行中":"已暂停")+" · "+fmt(state.progress*100,0)+"%";refs.modeTitle.textContent=mode.title;refs.modeGoal.textContent=mode.goal;refs.stageHint.textContent=mode.hint;refs.stateBadge.textContent=info.badge;refs.stateBadge.className="state-badge "+info.cls;refs.orbitMetric.textContent=info.orbit;refs.speedMetric.textContent=fmt(info.speed,3)+" km/s";refs.periodMetric.textContent=Number.isFinite(info.period)?(info.period<7200?fmt(info.period/60,2)+" min":fmt(info.period/3600,2)+" h"):"—";refs.gravityMetric.textContent=fmt(info.g,3)+" m/s²";refs.energyMetric.textContent=fmt(info.E/1e6,2)+" MJ/kg";refs.apsisMetric.textContent=info.apsis;refs.orbitNature.textContent=info.nature;refs.orbitExplanation.textContent=info.explain;refs.formulaReadout.textContent=info.formula;refs.targetSection.hidden=state.mode!=="transfer";refs.impulseSection.hidden=state.mode!=="escape";refs.relationTitle.textContent=state.mode==="transfer"?"转移轨道速度位置":state.mode==="escape"?"圆轨道与逃逸阈值":"轨道半径-速度与周期";refs.relationStatus.textContent=state.mode==="escape"?"vesc=√2 vc":"v∝r⁻¹ᐟ²";refs.energyTitle.textContent=state.mode==="escape"?"变速后比机械能":"轨道比机械能";refs.energyStatus.textContent="K+U=ε";refs.stepIndex.textContent="0"+(state.guideStep+1);refs.stepTitle.textContent=task.title;refs.stepPrompt.textContent=task.prompt;refs.playButton.setAttribute("aria-pressed",String(state.running));refs.sceneTabs.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===state.mode));refs.routeSteps.forEach((b,i)=>b.classList.toggle("is-active",i===state.guideStep));refs.rates.forEach(b=>b.classList.toggle("is-active",Number(b.dataset.rate)===state.rate));[refs.altitudeInput,refs.targetInput,refs.speedRatioInput,refs.progressInput].forEach(setProgress)}
  function render(){drawScene();drawRelation();drawEnergy();syncUI()}
  function setMode(mode){state.mode=mode;state.running=false;state.progress=0;if(mode==="synchronous")state.altitudeKm=Math.round(model.synchronousState().altitudeKm);if(mode==="transfer"){state.altitudeKm=400;state.targetKm=35793}if(mode==="escape"){state.altitudeKm=400;state.speedRatio=1}refs.altitudeInput.value=state.altitudeKm;refs.targetInput.value=state.targetKm;refs.speedRatioInput.value=state.speedRatio;refs.progressInput.value=0;render()}
  function setState(next={}){if(next.altitudeKm!==undefined)state.altitudeKm=model.clamp(next.altitudeKm,0,50000);if(next.targetKm!==undefined)state.targetKm=model.clamp(next.targetKm,500,60000);if(next.speedRatio!==undefined)state.speedRatio=model.clamp(next.speedRatio,.55,1.55);if(next.progress!==undefined)state.progress=model.clamp(next.progress,0,1);if(next.rate!==undefined)state.rate=model.clamp(next.rate,.5,1);if(next.guideStep!==undefined)state.guideStep=model.clamp(Math.round(next.guideStep),0,guide.length-1);[[refs.showVelocityToggle,"showVelocity"],[refs.showGravityToggle,"showGravity"],[refs.showEnergyToggle,"showEnergy"],[refs.showScaleToggle,"showScale"],[refs.showTheoryToggle,"showTheory"]].forEach(([input,key])=>{if(next[key]!==undefined)state[key]=Boolean(next[key]);input.checked=state[key]});if(typeof next.mode==="string"&&modes[next.mode])state.mode=next.mode;state.running=false;refs.altitudeInput.value=state.altitudeKm;refs.targetInput.value=state.targetKm;refs.speedRatioInput.value=state.speedRatio;refs.progressInput.value=state.progress;render()}
  let progressDragging=false;function setProgressFromPointer(event){const rect=refs.canvas.getBoundingClientRect();state.progress=model.clamp((event.clientX-rect.left)/rect.width,0,1);state.running=false;refs.progressInput.value=state.progress;render()}refs.canvas.addEventListener("pointerdown",event=>{progressDragging=true;refs.canvas.setPointerCapture?.(event.pointerId);setProgressFromPointer(event)});refs.canvas.addEventListener("pointermove",event=>{if(progressDragging)setProgressFromPointer(event)});refs.canvas.addEventListener("pointerup",event=>{progressDragging=false;if(refs.canvas.hasPointerCapture?.(event.pointerId))refs.canvas.releasePointerCapture(event.pointerId)});refs.canvas.addEventListener("pointercancel",()=>progressDragging=false);
  refs.sceneTabs.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));refs.routeSteps.forEach((b,i)=>b.addEventListener("click",()=>{state.guideStep=i;render()}));
  refs.altitudeInput.addEventListener("input",()=>{state.altitudeKm=Number(refs.altitudeInput.value);state.progress=0;render()});refs.targetInput.addEventListener("input",()=>{state.targetKm=Number(refs.targetInput.value);state.progress=0;render()});refs.speedRatioInput.addEventListener("input",()=>{state.speedRatio=Number(refs.speedRatioInput.value);state.progress=0;render()});refs.progressInput.addEventListener("input",()=>{state.progress=Number(refs.progressInput.value);state.running=false;render()});
  refs.presets.forEach(b=>b.addEventListener("click",()=>{const p=b.dataset.preset;if(p==="leo"){setMode("circular");state.altitudeKm=400}else if(p==="geo")setMode("synchronous");else if(p==="transfer")setMode("transfer");else{setMode("escape");state.speedRatio=Math.SQRT2}refs.altitudeInput.value=state.altitudeKm;refs.speedRatioInput.value=state.speedRatio;render()}));
  refs.rates.forEach(b=>b.addEventListener("click",()=>{state.rate=Number(b.dataset.rate);render()}));refs.playButton.addEventListener("click",()=>{state.running=true;state.lastTime=0;render()});refs.pauseButton.addEventListener("click",()=>{state.running=false;render()});refs.keyButton.addEventListener("click",()=>{state.progress=state.mode==="transfer"?.5:state.mode==="escape"?1:.25;refs.progressInput.value=state.progress;state.running=false;render()});refs.resetButton.addEventListener("click",()=>setMode(state.mode));
  [[refs.showVelocityToggle,"showVelocity"],[refs.showGravityToggle,"showGravity"],[refs.showEnergyToggle,"showEnergy"],[refs.showScaleToggle,"showScale"],[refs.showTheoryToggle,"showTheory"]].forEach(([el,key])=>el.addEventListener("change",()=>{state[key]=el.checked;render()}));
  refs.guideButton.addEventListener("click",()=>refs.guideDialog.showModal());refs.stepButton.addEventListener("click",()=>{state.guideStep=(state.guideStep+1)%guide.length;render()});refs.focusButton.addEventListener("click",()=>{document.body.classList.toggle("focus-mode");refs.focusButton.setAttribute("aria-pressed",String(document.body.classList.contains("focus-mode")))});refs.fullscreenButton.addEventListener("click",()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()});
  function frame(time){if(state.running){if(!state.lastTime)state.lastTime=time;state.progress+=(time-state.lastTime)/1000*state.rate*.18;state.lastTime=time;if(state.progress>=1)state.progress=0;refs.progressInput.value=state.progress;render()}requestAnimationFrame(frame)}
  window.orbitalLab={getState:()=>({...state}),setState,setMode,solve:current};window.addEventListener("resize",render);render();requestAnimationFrame(frame);
})();
