(function () {
  "use strict";
  const M = window.PendulumModel;
  if (!M) throw new Error("PendulumModel is required");
  const MODES = { small: ["小角近似", "振幅较小时，精确周期与小角公式有多接近"], large: ["大角摆动", "振幅增大时，为什么真实周期会明显长于小角公式"], gravity: ["长度与重力", "摆长和重力场如何共同决定周期"], damped: ["阻尼衰减", "机械能减少时，周期、相图和耗散账本怎样变化"] };
  const STEPS = [["先测一个周期", "应选择哪些相同运动状态作为一个完整周期的起止点？"], ["再扫振幅", "从多大振幅开始，小角周期误差不再可以忽略？"], ["最后核能量", "势能、动能和阻尼耗散能否闭合？"]];
  const state = { mode: "small", lengthM: 1, gravity: 9.8, amplitudeDeg: 10, massKg: 1, dampingS: 0, timeS: .5, guideStep: 0, showForces: true, showSmall: true, showTrail: true, showEnergy: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("pendulumCanvas"), period: $("periodChart"), phase: $("phaseEnergyChart"), length: $("lengthInput"), gravity: $("gravityInput"), amplitude: $("amplitudeInput"), mass: $("massInput"), damping: $("dampingInput"), time: $("timeInput"), lengthValue: $("lengthValue"), gravityValue: $("gravityValue"), amplitudeValue: $("amplitudeValue"), massValue: $("massValue"), dampingValue: $("dampingValue"), timeValue: $("timeValue"), forces: $("showForcesToggle"), small: $("showSmallToggle"), trail: $("showTrailToggle"), energy: $("showEnergyToggle"), angleMetric: $("angleMetric"), speedMetric: $("speedMetric"), tensionMetric: $("tensionMetric"), smallPeriodMetric: $("smallPeriodMetric"), exactPeriodMetric: $("exactPeriodMetric"), errorMetric: $("errorMetric"), nature: $("natureText"), explanation: $("explanationText"), periodStatus: $("periodStatus"), energyStatus: $("energyStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), pctx = R.period.getContext("2d"), ectx = R.phase.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, color, label) { line(k, x1, y1, x2, y2, color, 3); const a = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = color; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 9 * Math.cos(a - .5), y2 - 9 * Math.sin(a - .5)); k.lineTo(x2 - 9 * Math.cos(a + .5), y2 - 9 * Math.sin(a + .5)); k.fill(); if (label) text(k, label, x2 + 6, y2 - 6, color, 10, "left", 800); }
  function geometry(s, theta) { const pivot = { x: s.width * .5, y: 48 }, length = Math.min(s.height - 100, s.width * .34); return { pivot, length, bob: { x: pivot.x + length * Math.sin(theta), y: pivot.y + length * Math.cos(theta) } }; }
  function drawMain() {
    const s = size(R.main, ctx, 300), p = M.stateAt(state.timeS, input()), g = geometry(s, p.thetaRad); bg(ctx, s.width, s.height); ctx.strokeStyle = "rgba(223,229,223,.22)"; ctx.lineWidth = 1; ctx.beginPath(); ctx.arc(g.pivot.x, g.pivot.y, g.length, Math.PI / 2 - p.amplitudeRad, Math.PI / 2 + p.amplitudeRad); ctx.stroke(); line(ctx, g.pivot.x - 55, g.pivot.y, g.pivot.x + 55, g.pivot.y, C.text, 5); ctx.fillStyle = C.text; ctx.beginPath(); ctx.arc(g.pivot.x, g.pivot.y, 6, 0, Math.PI * 2); ctx.fill();
    if (state.showTrail) for (let i = 0; i <= 8; i += 1) { const q = M.stateAt(state.timeS * i / 8, input()), h = geometry(s, q.thetaRad); ctx.fillStyle = `rgba(240,185,81,${.08 + i * .025})`; ctx.beginPath(); ctx.arc(h.bob.x, h.bob.y, 5, 0, Math.PI * 2); ctx.fill(); }
    line(ctx, g.pivot.x, g.pivot.y, g.bob.x, g.bob.y, C.text, 3); ctx.fillStyle = C.amber; ctx.beginPath(); ctx.arc(g.bob.x, g.bob.y, 15, 0, Math.PI * 2); ctx.fill();
    if (state.showSmall) { const h = geometry(s, p.smallAngleThetaRad); line(ctx, g.pivot.x, g.pivot.y, h.bob.x, h.bob.y, C.cyan, 1, [5, 5]); ctx.strokeStyle = C.cyan; ctx.beginPath(); ctx.arc(h.bob.x, h.bob.y, 10, 0, Math.PI * 2); ctx.stroke(); text(ctx, "小角解", h.bob.x + 14, h.bob.y, C.cyan, 9); }
    if (state.showForces) { arrow(ctx, g.bob.x, g.bob.y, g.bob.x, g.bob.y + clamp(p.massKg * p.gravity * 6, 25, 90), C.red, "mg"); const ux = (g.pivot.x - g.bob.x) / g.length, uy = (g.pivot.y - g.bob.y) / g.length, len = clamp(p.tensionN * 6, 25, 100); arrow(ctx, g.bob.x, g.bob.y, g.bob.x + ux * len, g.bob.y + uy * len, C.green, "T"); }
    text(ctx, `θ=${fmt(p.thetaDeg, 2)}°`, 22, 30, C.amber, 10, "left", 800); text(ctx, `t=${fmt(state.timeS, 2)} s`, s.width - 22, 30, C.text, 10, "right", 800); text(ctx, "拖动摆球设置初始振幅", 22, s.height - 20, C.muted, 9);
  }
  function axes(k, s, xmax, ymin, ymax, left = 44, right = 18) { const p = { l: left, r: right, t: 20, b: 30 }, x = v => p.l + v / (xmax || 1) * (s.width - p.l - p.r), y = v => s.height - p.b - (v - ymin) / (ymax - ymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(223,229,223,.3)"); line(k, p.l, y(0), s.width - p.r, y(0), "rgba(223,229,223,.3)"); return { x, y, p }; }
  function drawPeriod() {
    const s = size(R.period, pctx), sweep = M.periodSweep(input(), 85), maxRatio = Math.max(...sweep.map(v => v.exactPeriodS / v.smallAnglePeriodS)), a = axes(pctx, s, 170, .98, maxRatio * 1.03); bg(pctx, s.width, s.height); pctx.strokeStyle = C.amber; pctx.lineWidth = 2; pctx.beginPath(); sweep.forEach((v, i) => { const ratio = v.exactPeriodS / v.smallAnglePeriodS; i ? pctx.lineTo(a.x(v.amplitudeDeg), a.y(ratio)) : pctx.moveTo(a.x(v.amplitudeDeg), a.y(ratio)); }); pctx.stroke(); line(pctx, a.p.l, a.y(1), s.width - a.p.r, a.y(1), C.cyan, 1, [5, 5]); const p = M.periods(input()); pctx.fillStyle = C.green; pctx.beginPath(); pctx.arc(a.x(state.amplitudeDeg), a.y(p.exactPeriodS / p.smallAnglePeriodS), 6, 0, Math.PI * 2); pctx.fill(); text(pctx, "T精确/T₀", 8, 14, C.amber, 9, "left", 800); text(pctx, "θ₀/°", s.width - 14, s.height - 6, C.muted, 8, "right");
  }
  function drawPhaseEnergy() {
    const s = size(R.phase, ectx), p = M.stateAt(state.timeS, input()), series = M.series(input(), Math.min(20, 3 * p.exactPeriodS), 100), split = s.width * .56; bg(ectx, s.width, s.height); line(ectx, split, 15, split, s.height - 20, "rgba(223,229,223,.2)"); const thetaMax = Math.max(.1, ...series.map(v => Math.abs(v.thetaRad))), omegaMax = Math.max(.1, ...series.map(v => Math.abs(v.angularVelocityRadS))), mapX = v => 28 + (v + thetaMax) / (2 * thetaMax) * (split - 55), mapY = v => s.height - 25 - (v + omegaMax) / (2 * omegaMax) * (s.height - 50); ectx.strokeStyle = C.violet; ectx.lineWidth = 2; ectx.beginPath(); series.forEach((v, i) => i ? ectx.lineTo(mapX(v.thetaRad), mapY(v.angularVelocityRadS)) : ectx.moveTo(mapX(v.thetaRad), mapY(v.angularVelocityRadS))); ectx.stroke(); ectx.fillStyle = C.amber; ectx.beginPath(); ectx.arc(mapX(p.thetaRad), mapY(p.angularVelocityRadS), 5, 0, Math.PI * 2); ectx.fill(); text(ectx, "θ–ω 相图", 16, 14, C.violet, 9, "left", 800);
    if (state.showEnergy) { const values = [["势能", p.potentialJ, C.amber], ["动能", p.kineticJ, C.cyan], ["耗散", p.dissipatedJ, C.red]], max = Math.max(.01, p.initialEnergyJ), x0 = split + 54; values.forEach((v, i) => { const yy = 48 + i * 50, width = Math.abs(v[1]) / max * (s.width - x0 - 20); text(ectx, v[0], split + 10, yy + 4, C.text, 8); ectx.fillStyle = v[2]; ectx.fillRect(x0, yy - 8, width, 16); text(ectx, `${fmt(v[1])}J`, s.width - 10, yy + 4, v[2], 8, "right", 700); }); }
  }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - Number(el.min)) / (Number(el.max) - Number(el.min)) * 100}%`); }
  function render() {
    const p = M.stateAt(state.timeS, input()), small = p.periodErrorPercent < 1, damped = state.dampingS > .001;
    R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.badge.textContent = damped ? "阻尼使相图向内收缩" : small ? "小角近似有效" : `大角周期增加 ${fmt(p.periodErrorPercent, 2)}%`; R.badge.className = `state-badge ${damped ? "is-damped" : small ? "is-small" : ""}`;
    const fields = [[R.length, state.lengthM, R.lengthValue, "m", 2], [R.gravity, state.gravity, R.gravityValue, "m/s²", 2], [R.amplitude, state.amplitudeDeg, R.amplitudeValue, "°", 1], [R.mass, state.massKg, R.massValue, "kg", 2], [R.damping, state.dampingS, R.dampingValue, "s⁻¹", 3], [R.time, state.timeS, R.timeValue, "s", 2]]; fields.forEach(([el, value, label, unit, digits]) => { range(el, value); label.textContent = `${fmt(value, digits)}${unit === "°" ? unit : ` ${unit}`}`; });
    R.angleMetric.textContent = `${fmt(p.thetaDeg, 2)}°`; R.speedMetric.textContent = `${fmt(p.speedMs)} m/s`; R.tensionMetric.textContent = `${fmt(p.tensionN)} N`; R.smallPeriodMetric.textContent = `${fmt(p.smallAnglePeriodS)} s`; R.exactPeriodMetric.textContent = `${fmt(p.exactPeriodS)} s`; R.errorMetric.textContent = `${fmt(p.periodErrorPercent, 3)}%`; R.nature.textContent = damped ? "机械能转化为耗散能" : small ? "sinθ≈θ 误差很小" : "非线性回复力使周期变长"; R.explanation.textContent = damped ? "E机+E耗散=E初" : small ? "T精确≈T₀" : "T精确>T₀"; R.periodStatus.textContent = `θ₀=${fmt(state.amplitudeDeg, 0)}° · 偏差${fmt(p.periodErrorPercent, 2)}%`; R.energyStatus.textContent = Math.abs(p.energyResidualJ) < 2e-7 ? damped ? "含耗散账本闭合" : "能量守恒" : "检查残差"; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = state.mode === "large" ? "T=4√(L/g)K(k)" : damped ? "E机+E耗散=E初" : "T₀=2π√(L/g)"; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawMain(); drawPeriod(); drawPhaseEnergy();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "small") Object.assign(state, { lengthM: 1, gravity: 9.8, amplitudeDeg: 10, massKg: 1, dampingS: 0, timeS: .5 }); if (mode === "large") Object.assign(state, { lengthM: 1, gravity: 9.8, amplitudeDeg: 60, dampingS: 0, timeS: .54 }); if (mode === "gravity") Object.assign(state, { lengthM: 2, gravity: 3.7, amplitudeDeg: 10, dampingS: 0, timeS: 1 }); if (mode === "damped") Object.assign(state, { lengthM: 1, gravity: 9.8, amplitudeDeg: 30, dampingS: .12, timeS: 8 }); render(); }
  function reset() { Object.assign(state, { mode: "small", lengthM: 1, gravity: 9.8, amplitudeDeg: 10, massKg: 1, dampingS: 0, timeS: .5, guideStep: 0, showForces: true, showSmall: true, showTrail: true, showEnergy: true, dragging: false }); [[R.forces, "showForces"], [R.small, "showSmall"], [R.trail, "showTrail"], [R.energy, "showEnergy"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { lengthM: [.1, 5], gravity: [1.6, 25], amplitudeDeg: [1, 170], massKg: [.1, 10], dampingS: [0, 1], timeS: [0, 20] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); if (MODES[next.mode]) state.mode = next.mode; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showForces", "showSmall", "showTrail", "showEnergy"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.length, "lengthM"], [R.gravity, "gravity"], [R.amplitude, "amplitudeDeg"], [R.mass, "massKg"], [R.damping, "dampingS"], [R.time, "timeS"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.forces, "showForces"], [R.small, "showSmall"], [R.trail, "showTrail"], [R.energy, "showEnergy"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(), s = { width: box.width, height: box.height }, g = geometry(s, 0), dx = event.clientX - box.left - g.pivot.x, dy = Math.max(1, event.clientY - box.top - g.pivot.y); state.amplitudeDeg = clamp(Math.abs(Math.atan2(dx, dy) * 180 / Math.PI), 1, 170); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.pendulumLab = { periods: next => M.periods(next), stateAt: (time, next) => M.stateAt(time, next), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
