(function () {
  const model = window.PhotoelectricModel;
  if (!model) throw new Error("PhotoelectricModel is required");
  const refs = {
    canvas:document.getElementById("photoCanvas"),energyChart:document.getElementById("energyChart"),currentChart:document.getElementById("currentChart"),wavelengthInput:document.getElementById("wavelengthInput"),intensityInput:document.getElementById("intensityInput"),voltageInput:document.getElementById("voltageInput"),wavelengthValue:document.getElementById("wavelengthValue"),intensityValue:document.getElementById("intensityValue"),voltageValue:document.getElementById("voltageValue"),spectralNote:document.getElementById("spectralNote"),materialNote:document.getElementById("materialNote"),timeValue:document.getElementById("timeValue"),photonMetric:document.getElementById("photonMetric"),workMetric:document.getElementById("workMetric"),kineticMetric:document.getElementById("kineticMetric"),stoppingMetric:document.getElementById("stoppingMetric"),speedMetric:document.getElementById("speedMetric"),currentMetric:document.getElementById("currentMetric"),photoNature:document.getElementById("photoNature"),photoExplanation:document.getElementById("photoExplanation"),modeTitle:document.getElementById("modeTitle"),modeGoal:document.getElementById("modeGoal"),stateBadge:document.getElementById("stateBadge"),stageHint:document.getElementById("stageHint"),energyChartStatus:document.getElementById("energyChartStatus"),currentChartStatus:document.getElementById("currentChartStatus"),stepIndex:document.getElementById("stepIndex"),stepTitle:document.getElementById("stepTitle"),stepPrompt:document.getElementById("stepPrompt"),formulaReadout:document.getElementById("formulaReadout"),playButton:document.getElementById("playButton"),pauseButton:document.getElementById("pauseButton"),keyButton:document.getElementById("keyButton"),resetButton:document.getElementById("resetButton"),guideButton:document.getElementById("guideButton"),stepButton:document.getElementById("stepButton"),focusButton:document.getElementById("focusButton"),fullscreenButton:document.getElementById("fullscreenButton"),guideDialog:document.getElementById("guideDialog"),showPhotonsToggle:document.getElementById("showPhotonsToggle"),showElectronsToggle:document.getElementById("showElectronsToggle"),showEnergyToggle:document.getElementById("showEnergyToggle"),showFieldToggle:document.getElementById("showFieldToggle"),showEventsToggle:document.getElementById("showEventsToggle"),sceneTabs:Array.from(document.querySelectorAll(".scene-tab[data-mode]")),routeSteps:Array.from(document.querySelectorAll(".route-step")),materialButtons:Array.from(document.querySelectorAll("[data-material]")),presetButtons:Array.from(document.querySelectorAll("[data-preset]")),rateButtons:Array.from(document.querySelectorAll("[data-rate]"))
  };
  const context=refs.canvas.getContext("2d"),energyContext=refs.energyChart.getContext("2d"),currentContext=refs.currentChart.getContext("2d");
  const COLORS={photon:"#b58ce5",electron:"#64c7d9",energy:"#f2b84b",threshold:"#ff7468",current:"#79d992",text:"#a6b0a9",muted:"#717b75"};
  const modes={threshold:{title:"截止频率",goal:"只有单个光子能量超过逸出功，电子才可能逸出",hint:"拖动波长，跨过当前材料的截止条件",key:"◎ 截止波长"},intensity:{title:"频率与光强",goal:"频率决定最大初动能，光强主要改变发射数量",hint:"保持波长不变，只改变光强比较电子速率和光电流",key:"◎ 强光对照"},stopping:{title:"遏止电压",goal:"用反向电场使最快光电子恰好不能到达阳极",hint:"改变极板电压，在伏安曲线上寻找电流归零点",key:"◎ 遏止点"},materials:{title:"材料对照",goal:"逸出功不同使各材料具有不同截止频率和截止波长",hint:"保持入射光不变，切换阴极材料比较是否逸出",key:"◎ 锌板紫外"}};
  const guide=[{title:"先判断能否逸出",prompt:"把低频光增强很多，为什么仍不能释放一个电子？"},{title:"再区分能量与数量",prompt:"只提高光强时，最大初动能和饱和光电流分别怎样变化？"},{title:"最后测最大初动能",prompt:"为什么反向电压的电流归零点能给出最快电子的初动能？"}];
  const state={mode:"threshold",wavelengthNm:400,intensity:60,voltage:0,material:"sodium",running:true,playbackRate:.5,elapsed:0,guideStep:0,dragging:false,showPhotons:true,showElectrons:true,showEnergy:true,showField:true,showEvents:true};
  let frameCount=0;
  function clamp(v,min,max){return Math.min(max,Math.max(min,Number(v)))} function fmt(v,d=3){return Number(v).toFixed(d).replace("-","−")} function solve(){return model.solve(state)}
  function canvasSize(canvas,ctx,minH=180){const r=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.max(280,Math.round(r.width)),h=Math.max(minH,Math.round(r.height));if(canvas.width!==w*ratio||canvas.height!==h*ratio){canvas.width=w*ratio;canvas.height=h*ratio}ctx.setTransform(ratio,0,0,ratio,0,0);return{width:w,height:h}}
  function line(ctx,x1,y1,x2,y2,color,width=1,dash=[]){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore()} function text(ctx,value,x,y,color=COLORS.text,size=10,align="left",weight=500){ctx.fillStyle=color;ctx.font=`${weight} ${size}px ui-sans-serif,system-ui`;ctx.textAlign=align;ctx.fillText(value,x,y)}
  function arrow(ctx,x1,y1,x2,y2,color,width=1.7){const a=Math.atan2(y2-y1,x2-x1);line(ctx,x1,y1,x2,y2,color,width);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-7*Math.cos(a-.48),y2-7*Math.sin(a-.48));ctx.lineTo(x2-7*Math.cos(a+.48),y2-7*Math.sin(a+.48));ctx.fill()}
  function wavelengthColor(lambda){if(lambda<380)return"#aa79ff";if(lambda<450)return"#767cff";if(lambda<495)return"#52b9ff";if(lambda<570)return"#79d992";if(lambda<590)return"#f2d45c";if(lambda<620)return"#ff9d52";return"#ff7468"}
  function drawScene(){const s=solve(),{width,height}=canvasSize(refs.canvas,context,260),cy=height*.49,cathodeX=width*.36,anodeX=width*.76,top=Math.max(50,height*.17),bottom=height-Math.max(55,height*.15),lightColor=wavelengthColor(s.wavelengthNm);context.fillStyle="#090d0f";context.fillRect(0,0,width,height);for(let x=0;x<width;x+=36)line(context,x,0,x,height,"rgba(238,241,230,.035)");for(let y=0;y<height;y+=36)line(context,0,y,width,y,"rgba(238,241,230,.035)");context.strokeStyle="rgba(238,241,230,.28)";context.lineWidth=2;context.beginPath();context.roundRect(width*.19,top-20,width*.66,bottom-top+40,Math.min(60,height*.18));context.stroke();
    context.fillStyle="#8a928d";context.fillRect(cathodeX-10,top,20,bottom-top);context.fillStyle="#bdc4bf";context.fillRect(anodeX-8,top+20,16,bottom-top-40);text(context,`${s.material.symbol} 阴极`,cathodeX,top-16,COLORS.energy,10,"center",700);text(context,"阳极",anodeX,top-16,COLORS.electron,10,"center",700);
    if(state.showField&&Math.abs(s.voltage)>.02){const dir=s.voltage>0?1:-1;for(let i=1;i<=4;i++){const y=top+(bottom-top)*i/5;arrow(context,dir>0?cathodeX+25:anodeX-25,y,dir>0?anodeX-25:cathodeX+25,y,s.voltage>0?`${COLORS.current}99`:`${COLORS.threshold}99`,1.2)}text(context,s.voltage>0?"加速电场":"遏止电场",(cathodeX+anodeX)/2,bottom+28,s.voltage>0?COLORS.current:COLORS.threshold,9,"center",700)}
    if(state.showPhotons&&s.intensity>0){const count=Math.max(1,Math.round(s.intensity/9));for(let i=0;i<count;i++){const phase=(state.elapsed*(.38+.03*i)+i/count)%1,x=width*.06+(cathodeX-width*.06)*phase,y=cy+(i-(count-1)/2)*Math.min(16,(bottom-top)/(count+2));context.strokeStyle=lightColor;context.lineWidth=1.8;context.beginPath();for(let k=0;k<=28;k++){const px=x-34+34*k/28,py=y+Math.sin(k*.9+state.elapsed*8)*3;if(k)context.lineTo(px,py);else context.moveTo(px,py)}context.stroke();context.fillStyle=lightColor;context.beginPath();context.arc(x,y,3.2,0,Math.PI*2);context.fill()}}
    if(state.showElectrons&&s.emits){const count=Math.max(2,Math.round(s.intensity/12));for(let i=0;i<count;i++){const phase=(state.elapsed*(.24+.018*i)+i/count)%1,blocked=s.voltage<=-s.stoppingVoltage&&s.stoppingVoltage>0;let x,y;if(blocked){const q=Math.sin(Math.PI*phase),reach=.08+.22*(.35+i/count*.6);x=cathodeX+q*(anodeX-cathodeX)*reach;y=cy+(i-(count-1)/2)*13-Math.sin(Math.PI*phase)*18}else{x=cathodeX+(anodeX-cathodeX)*phase;y=cy+(i-(count-1)/2)*13+Math.sin(Math.PI*phase)*(i%2?11:-11)}context.fillStyle=COLORS.electron;context.beginPath();context.arc(x,y,3,0,Math.PI*2);context.fill();if(i<4)line(context,x-10,y+2,x,y,`${COLORS.electron}66`,1)}}
    if(!s.emits&&s.intensity>0){context.strokeStyle=`${COLORS.threshold}aa`;context.lineWidth=2;context.beginPath();context.arc(cathodeX,cy,12+5*Math.sin(state.elapsed*5),0,Math.PI*2);context.stroke();text(context,"hν < W₀ · 无电子逸出",(cathodeX+anodeX)/2,cy,COLORS.threshold,11,"center",700)}
    if(state.showEnergy){const x=width*.055,y=height-49,w=Math.min(250,width*.29),scale=w/Math.max(5,s.photonEnergyEv+.4);text(context,"单个光子能量账本",x,y-18,COLORS.muted,9);context.fillStyle=COLORS.energy;context.fillRect(x,y,s.material.workFunctionEv*scale,9);context.fillStyle=s.emits?COLORS.electron:COLORS.threshold;context.fillRect(x+s.material.workFunctionEv*scale,y,s.maxKineticEnergyEv*scale,9);text(context,"W₀",x+4,y+25,COLORS.energy,8);if(s.emits)text(context,"Eₖₘₐₓ",x+s.material.workFunctionEv*scale+4,y+25,COLORS.electron,8)}
    if(state.showEvents)text(context,`代表性事件率 ${Math.round(s.intensity*.6)}/周期 · 收集效率 ${(s.collectionFraction*100).toFixed(0)}%`,width-14,height-15,COLORS.muted,9,"right");text(context,`λ = ${fmt(s.wavelengthNm,0)} nm`,width*.07,top-18,lightColor,10,"left",700);text(context,`U = ${fmt(s.voltage,2)} V`,anodeX,bottom+28,s.voltage<0?COLORS.threshold:COLORS.current,10,"center",700)}
  function axes(ctx,w,h,xMin,xMax,yMin,yMax,xLabel,yLabel){const p={l:48,r:18,t:20,b:34},x=v=>p.l+(v-xMin)/(xMax-xMin)*(w-p.l-p.r),y=v=>h-p.b-(v-yMin)/(yMax-yMin)*(h-p.t-p.b);line(ctx,p.l,p.t,p.l,h-p.b,"rgba(238,241,230,.28)");line(ctx,p.l,h-p.b,w-p.r,h-p.b,"rgba(238,241,230,.28)");for(let i=0;i<=4;i++){const xv=xMin+(xMax-xMin)*i/4,yv=yMin+(yMax-yMin)*i/4;line(ctx,x(xv),p.t,x(xv),h-p.b,"rgba(238,241,230,.05)");line(ctx,p.l,y(yv),w-p.r,y(yv),"rgba(238,241,230,.05)");text(ctx,fmt(xv,1),x(xv),h-15,COLORS.muted,8,"center");text(ctx,fmt(yv,1),p.l-7,y(yv)+3,COLORS.muted,8,"right")}text(ctx,xLabel,w-p.r,h-4,COLORS.muted,8,"right");text(ctx,yLabel,5,12,COLORS.muted,8);return{x,y,p}}
  function plot(ctx,pts,map,xKey,yKey,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();pts.forEach((p,i)=>{const x=map.x(p[xKey]),y=map.y(p[yKey]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
  function drawCharts(){const s=solve();let size=canvasSize(refs.energyChart,energyContext);energyContext.fillStyle="#111512";energyContext.fillRect(0,0,size.width,size.height);const fMin=3.5,fMax=16,points=Array.from({length:121},(_,i)=>{const f=(fMin+(fMax-fMin)*i/120)*1e14,e=Math.max(0,model.H*f/model.E-s.material.workFunctionEv);return{f:f/1e14,e}}),map=axes(energyContext,size.width,size.height,fMin,fMax,0,5.2,"ν / 10¹⁴ Hz","Eₖₘₐₓ / eV");plot(energyContext,points,map,"f","e",COLORS.energy,2.3);const fc=s.thresholdFrequencyHz/1e14;line(energyContext,map.x(fc),map.p.t,map.x(fc),size.height-map.p.b,COLORS.threshold,1.2,[4,4]);energyContext.fillStyle=COLORS.electron;energyContext.beginPath();energyContext.arc(map.x(s.frequencyHz/1e14),map.y(s.maxKineticEnergyEv),5,0,Math.PI*2);energyContext.fill();
    size=canvasSize(refs.currentChart,currentContext);currentContext.fillStyle="#111512";currentContext.fillRect(0,0,size.width,size.height);const volts=model.voltageSeries(state,120).map(p=>({u:p.voltage,i:p.photocurrentNa})),imap=axes(currentContext,size.width,size.height,-6,6,0,Math.max(1,s.saturationCurrentNa*1.15),"U / V","I / nA");plot(currentContext,volts,imap,"u","i",COLORS.current,2.3);line(currentContext,imap.x(-s.stoppingVoltage),imap.p.t,imap.x(-s.stoppingVoltage),size.height-imap.p.b,COLORS.threshold,1.1,[4,4]);currentContext.fillStyle=COLORS.electron;currentContext.beginPath();currentContext.arc(imap.x(s.voltage),imap.y(s.photocurrentNa),5,0,Math.PI*2);currentContext.fill()}
  function spectralName(lambda){return lambda<380?"紫外":lambda<450?"紫":lambda<495?"蓝":lambda<570?"绿":lambda<590?"黄":lambda<620?"橙":"红"}
  function status(s){if(!s.emits)return{badge:s.intensity<=0?"无入射光":"低于截止频率",cls:"blocked",nature:"hν < W₀",explanation:`${fmt(s.photonEnergyEv,3)} eV 不足以克服 ${s.material.label} 的 ${fmt(s.material.workFunctionEv,2)} eV 逸出功`};if(s.photocurrentNa<.001&&s.voltage<0)return{badge:"达到遏止",cls:"stopped",nature:"eU꜀ = Eₖₘₐₓ",explanation:"最快光电子也无法到达阳极，光电流为零"};return{badge:"发生光电效应",cls:"emitting",nature:"hν > W₀",explanation:`每个光子最多留下 ${fmt(s.maxKineticEnergyEv,3)} eV 给光电子`}}
  function rangeProgress(input){const min=Number(input.min),max=Number(input.max);input.style.setProperty("--range-progress",`${(Number(input.value)-min)/(max-min)*100}%`)}
  function render(){const s=solve(),mode=modes[state.mode],st=status(s);refs.wavelengthInput.value=state.wavelengthNm;refs.intensityInput.value=state.intensity;refs.voltageInput.value=state.voltage;refs.wavelengthValue.textContent=`${fmt(state.wavelengthNm,0)} nm`;refs.intensityValue.textContent=`${fmt(state.intensity,0)}%`;refs.voltageValue.textContent=`${fmt(state.voltage,2)} V`;refs.spectralNote.textContent=`${spectralName(s.wavelengthNm)}光 · ν = ${fmt(s.frequencyHz/1e14,3)}×10¹⁴ Hz`;refs.materialNote.textContent=`${s.material.label} · W₀ = ${fmt(s.material.workFunctionEv,2)} eV`;refs.timeValue.textContent=`${state.running?"运行中":"已暂停"} · ${fmt(state.elapsed,1)} s`;refs.photonMetric.textContent=`${fmt(s.photonEnergyEv,3)} eV`;refs.workMetric.textContent=`${fmt(s.material.workFunctionEv,3)} eV`;refs.kineticMetric.textContent=`${fmt(s.maxKineticEnergyEv,3)} eV`;refs.stoppingMetric.textContent=`${fmt(s.stoppingVoltage,3)} V`;refs.speedMetric.textContent=s.maxSpeed?`${fmt(s.maxSpeed/1e5,2)}×10⁵ m/s`:"0 m/s";refs.currentMetric.textContent=`${fmt(s.photocurrentNa,3)} nA`;refs.photoNature.textContent=st.nature;refs.photoExplanation.textContent=st.explanation;refs.modeTitle.textContent=mode.title;refs.modeGoal.textContent=mode.goal;refs.stageHint.textContent=mode.hint;refs.stateBadge.textContent=st.badge;refs.stateBadge.className=`state-badge is-${st.cls}`;refs.energyChartStatus.textContent=`斜率 h · 截止频率 ${fmt(s.thresholdFrequencyHz/1e14,2)}×10¹⁴ Hz`;refs.currentChartStatus.textContent=`U꜀ = ${fmt(s.stoppingVoltage,3)} V · Iₛ = ${fmt(s.saturationCurrentNa,2)} nA`;refs.formulaReadout.textContent=s.emits?`${fmt(s.photonEnergyEv,3)} = ${fmt(s.material.workFunctionEv,3)} + ${fmt(s.maxKineticEnergyEv,3)} eV`:`${fmt(s.photonEnergyEv,3)} < ${fmt(s.material.workFunctionEv,3)} eV`;refs.stepIndex.textContent=String(state.guideStep+1).padStart(2,"0");refs.stepTitle.textContent=guide[state.guideStep].title;refs.stepPrompt.textContent=guide[state.guideStep].prompt;refs.sceneTabs.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===state.mode));refs.routeSteps.forEach((b,i)=>b.classList.toggle("is-active",i===state.guideStep));refs.materialButtons.forEach(b=>b.classList.toggle("is-active",b.dataset.material===state.material));refs.rateButtons.forEach(b=>b.classList.toggle("is-active",Number(b.dataset.rate)===state.playbackRate));refs.keyButton.textContent=mode.key;refs.playButton.textContent=state.running?"▶ 运行中":"▶ 运行";refs.playButton.setAttribute("aria-pressed",String(state.running));[refs.wavelengthInput,refs.intensityInput,refs.voltageInput].forEach(rangeProgress);drawScene();drawCharts()}
  function setMode(name){if(!modes[name])return;state.mode=name;if(name==="intensity")Object.assign(state,{wavelengthNm:400,intensity:30,voltage:2,material:"sodium"});if(name==="stopping")Object.assign(state,{wavelengthNm:400,intensity:60,voltage:0,material:"sodium"});if(name==="materials")Object.assign(state,{wavelengthNm:350,intensity:60,voltage:2,material:"sodium"});render()}
  function reset(){Object.assign(state,{mode:"threshold",wavelengthNm:400,intensity:60,voltage:0,material:"sodium",running:true,playbackRate:.5,elapsed:0,guideStep:0,showPhotons:true,showElectrons:true,showEnergy:true,showField:true,showEvents:true});[refs.showPhotonsToggle,refs.showElectronsToggle,refs.showEnergyToggle,refs.showFieldToggle,refs.showEventsToggle].forEach(x=>x.checked=true);render()}
  [[refs.wavelengthInput,"wavelengthNm"],[refs.intensityInput,"intensity"],[refs.voltageInput,"voltage"]].forEach(([input,key])=>input.addEventListener("input",()=>{state[key]=Number(input.value);render()}));refs.sceneTabs.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));refs.routeSteps.forEach((b,i)=>b.addEventListener("click",()=>{state.guideStep=i;render()}));refs.materialButtons.forEach(b=>b.addEventListener("click",()=>{state.material=b.dataset.material;render()}));refs.rateButtons.forEach(b=>b.addEventListener("click",()=>{state.playbackRate=Number(b.dataset.rate);render()}));
  refs.presetButtons.forEach(b=>b.addEventListener("click",()=>{const p=b.dataset.preset;if(p==="violet")Object.assign(state,{mode:"threshold",wavelengthNm:400,intensity:60,voltage:0,material:"sodium"});if(p==="red")Object.assign(state,{mode:"threshold",wavelengthNm:650,intensity:100,voltage:3,material:"sodium"});if(p==="dim")Object.assign(state,{mode:"intensity",wavelengthNm:400,intensity:15,voltage:3,material:"sodium"});if(p==="zinc")Object.assign(state,{mode:"materials",wavelengthNm:250,intensity:60,voltage:2,material:"zinc"});render()}));refs.playButton.addEventListener("click",()=>{state.running=true;render()});refs.pauseButton.addEventListener("click",()=>{state.running=false;render()});refs.keyButton.addEventListener("click",()=>{const s=solve();if(state.mode==="threshold")state.wavelengthNm=Math.round(s.thresholdWavelengthNm/5)*5;if(state.mode==="intensity")state.intensity=100;if(state.mode==="stopping")state.voltage=-Math.ceil(s.stoppingVoltage*100)/100;if(state.mode==="materials")Object.assign(state,{material:"zinc",wavelengthNm:250,intensity:60,voltage:2});state.running=false;render()});refs.resetButton.addEventListener("click",reset);
  [[refs.showPhotonsToggle,"showPhotons"],[refs.showElectronsToggle,"showElectrons"],[refs.showEnergyToggle,"showEnergy"],[refs.showFieldToggle,"showField"],[refs.showEventsToggle,"showEvents"]].forEach(([input,key])=>input.addEventListener("change",()=>{state[key]=input.checked;render()}));refs.guideButton.addEventListener("click",()=>refs.guideDialog.showModal());refs.stepButton.addEventListener("click",()=>{state.guideStep=(state.guideStep+1)%3;render()});refs.focusButton.addEventListener("click",()=>{const active=document.body.classList.toggle("focus-mode");refs.focusButton.setAttribute("aria-pressed",String(active))});refs.fullscreenButton.addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
  function wavelengthFromPointer(e){const r=refs.canvas.getBoundingClientRect(),fraction=clamp((e.clientX-r.left)/r.width,0,1);state.wavelengthNm=Math.round((180+fraction*570)/5)*5;render()}refs.canvas.addEventListener("pointerdown",e=>{state.dragging=true;refs.canvas.setPointerCapture(e.pointerId);wavelengthFromPointer(e)});refs.canvas.addEventListener("pointermove",e=>{if(state.dragging)wavelengthFromPointer(e)});refs.canvas.addEventListener("pointerup",e=>{state.dragging=false;if(refs.canvas.hasPointerCapture(e.pointerId))refs.canvas.releasePointerCapture(e.pointerId)});refs.canvas.addEventListener("pointercancel",()=>state.dragging=false);window.addEventListener("resize",render);
  let last=performance.now();function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(state.running){state.elapsed+=dt*state.playbackRate;frameCount++;drawScene();if(frameCount%4===0)render()}requestAnimationFrame(frame)}window.photoelectricLab={solve:(input={})=>model.solve({...state,...input}),getState:()=>({...state}),setMode,setState:(next={})=>{Object.assign(state,next);render()},reset};render();requestAnimationFrame(frame);
})();
