(function () {
  "use strict";
  const M = window.PursuitModel;
  if (!M) throw new Error("PursuitModel is required");
  const MODES = {
    chase: { title: "同向追及", goal: "后车速度更大时，位置差如何连续减小到零", hint: "拖动时间探针，观察两条世界线交汇" },
    delay: { title: "延迟启动", goal: "分段位置函数怎样决定真正的相遇时刻", hint: "改变延迟与加速度，检查启动前后两段" },
    opposite: { title: "相向运动", goal: "相向速度符号如何转化为接近速率", hint: "比较地面速度和相对速度的符号" },
    reference: { title: "参考系变换", goal: "换匀速参考系后相遇事件为什么保持不变", hint: "切换地面、A车和B车参考系" }
  };
  const STEPS = [
    ["先写位置函数", "两车的初位置、速度和延迟启动分别进入位置函数的哪一项？"],
    ["再看相对运动", "有向间距的斜率与两车速度之差有什么关系？"],
    ["最后核对事件", "换到随 A 车运动的参考系后，相遇时刻是否改变？"]
  ];
  const state = { mode: "chase", gap: 40, vA: 6, vB: 10, aB: 0, delayB: 0, frame: "ground", time: 0, running: false, guideStep: 0, dragging: false, showStrobe: true, showVectors: true, showMeeting: true, showRelative: true };
  const $ = (id) => document.getElementById(id);
  const R = { canvas:$("pursuitCanvas"),positionChart:$("positionChart"),relativeChart:$("relativeChart"),gapInput:$("gapInput"),speedAInput:$("speedAInput"),speedBInput:$("speedBInput"),accelInput:$("accelInput"),delayInput:$("delayInput"),timeInput:$("timeInput"),gapValue:$("gapValue"),speedAValue:$("speedAValue"),speedBValue:$("speedBValue"),accelValue:$("accelValue"),delayValue:$("delayValue"),timeValue:$("timeValue"),timeMetric:$("timeMetric"),positionAMetric:$("positionAMetric"),positionBMetric:$("positionBMetric"),separationMetric:$("separationMetric"),relativeMetric:$("relativeMetric"),meetingMetric:$("meetingMetric"),natureText:$("natureText"),explanationText:$("explanationText"),modeTitle:$("modeTitle"),modeGoal:$("modeGoal"),stateBadge:$("stateBadge"),stageHint:$("stageHint"),positionStatus:$("positionStatus"),relativeStatus:$("relativeStatus"),stepIndex:$("stepIndex"),stepTitle:$("stepTitle"),stepPrompt:$("stepPrompt"),formulaReadout:$("formulaReadout"),playButton:$("playButton"),pauseButton:$("pauseButton"),keyButton:$("keyButton"),resetButton:$("resetButton"),guideButton:$("guideButton"),stepButton:$("stepButton"),focusButton:$("focusButton"),fullscreenButton:$("fullscreenButton"),guideDialog:$("guideDialog"),showStrobeToggle:$("showStrobeToggle"),showVectorsToggle:$("showVectorsToggle"),showMeetingToggle:$("showMeetingToggle"),showRelativeToggle:$("showRelativeToggle"),sceneTabs:[...document.querySelectorAll(".scene-tab[data-mode]")],routeSteps:[...document.querySelectorAll(".route-step")],frameButtons:[...document.querySelectorAll("[data-frame]")] };
  const ctx=R.canvas.getContext("2d"),pctx=R.positionChart.getContext("2d"),rctx=R.relativeChart.getContext("2d");
  const C={bg:"#090d0f",grid:"rgba(223,229,223,.055)",a:"#64c7d9",b:"#f2b84b",meet:"#79d992",relative:"#b58ce5",text:"#a6b0a9",muted:"#717b75"};
  const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)));
  const fmt=(v,d=2)=>Number(v).toFixed(d).replace("-","−");
  function input(){return inputFor(state);}
  function inputFor(source={}){const mode=MODES[source.mode]?source.mode:state.mode;const vB=mode==="opposite"?-(Math.abs(Number(source.vB??state.vB))):Number(source.vB??state.vB);const vA=Number(source.vA??state.vA);const frame=source.frame||state.frame;const frames={ground:0,A:vA,B:vB};return{xA0:mode==="opposite"?0:Number(source.gap??state.gap),xB0:mode==="opposite"?Number(source.gap??state.gap):0,vA,vB,aB:Number(source.aB??state.aB),delayB:Number(source.delayB??state.delayB),frameVelocity:frames[frame]||0};}
  function meeting(){return M.encounter(input());}
  function duration(){const hit=meeting();return hit.exists?Math.max(8,Math.min(30,hit.time*1.35)):20;}
  function size(canvas,context,minH=180){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=Math.max(280,Math.round(rect.width)),height=Math.max(minH,Math.round(rect.height));if(canvas.width!==width*dpr||canvas.height!==height*dpr){canvas.width=width*dpr;canvas.height=height*dpr}context.setTransform(dpr,0,0,dpr,0,0);return{width,height};}
  function line(context,x1,y1,x2,y2,color,width=1,dash=[]){context.save();context.strokeStyle=color;context.lineWidth=width;context.setLineDash(dash);context.beginPath();context.moveTo(x1,y1);context.lineTo(x2,y2);context.stroke();context.restore();}
  function text(context,value,x,y,color=C.text,size=10,align="left",weight=500){context.fillStyle=color;context.font=`${weight} ${size}px ui-sans-serif,system-ui`;context.textAlign=align;context.fillText(value,x,y);}
  function arrow(context,x1,y1,x2,y2,color){line(context,x1,y1,x2,y2,color,2);const a=Math.atan2(y2-y1,x2-x1);context.fillStyle=color;context.beginPath();context.moveTo(x2,y2);context.lineTo(x2-7*Math.cos(a-.48),y2-7*Math.sin(a-.48));context.lineTo(x2-7*Math.cos(a+.48),y2-7*Math.sin(a+.48));context.fill();}
  function background(context,width,height){context.fillStyle=C.bg;context.fillRect(0,0,width,height);for(let x=18;x<width;x+=42)line(context,x,0,x,height,C.grid);for(let y=18;y<height;y+=42)line(context,0,y,width,y,C.grid);}
  function worldBounds(series){const values=series.flatMap(point=>[point.xA,point.xB]);let min=Math.min(...values),max=Math.max(...values);const pad=Math.max(15,(max-min)*.14);return{min:min-pad,max:max+pad};}
  function drawCar(context,x,y,color,label,velocity,scale){context.fillStyle=color;context.fillRect(x-24,y-14,48,20);context.fillStyle="#111512";context.fillRect(x-13,y-9,18,8);context.fillStyle=color;context.beginPath();context.arc(x-14,y+9,5,0,Math.PI*2);context.arc(x+15,y+9,5,0,Math.PI*2);context.fill();text(context,label,x,y-22,color,10,"center",800);if(state.showVectors&&Math.abs(velocity)>.02)arrow(context,x,y+28,x+velocity*scale,y+28,color);}
  function drawScene(){const {width,height}=size(R.canvas,ctx,260),end=duration(),series=M.series(input(),end,120),bounds=worldBounds(series),mapX=x=>50+(x-bounds.min)/(bounds.max-bounds.min)*(width-100),current=M.stateAt(state.time,input()),hit=meeting(),roadA=height*.39,roadB=height*.66;background(ctx,width,height);line(ctx,35,roadA+16,width-35,roadA+16,"rgba(223,229,223,.28)",3);line(ctx,35,roadB+16,width-35,roadB+16,"rgba(223,229,223,.28)",3);
    if(state.showStrobe){for(let t=0;t<=Math.min(state.time,end);t+=Math.max(.5,end/12)){const s=M.stateAt(t,input());ctx.globalAlpha=.16;ctx.fillStyle=C.a;ctx.beginPath();ctx.arc(mapX(s.xA),roadA,4,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.b;ctx.beginPath();ctx.arc(mapX(s.xB),roadB,4,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}}
    const vectorScale=Math.min(4,(width-100)/Math.max(30,bounds.max-bounds.min)*2);drawCar(ctx,mapX(current.xA),roadA,C.a,"A",current.vA,vectorScale);drawCar(ctx,mapX(current.xB),roadB,C.b,"B",current.vB,vectorScale);
    if(state.showRelative){const y=height*.84;line(ctx,mapX(current.xB),y,mapX(current.xA),y,C.relative,2,[5,4]);text(ctx,`Δx = ${fmt(current.separation)} m`,(mapX(current.xA)+mapX(current.xB))/2,y-10,C.relative,10,"center",700);}
    if(state.showMeeting&&hit.exists){const x=mapX(hit.position-(input().frameVelocity||0)*hit.time);line(ctx,x,58,x,height-58,`${C.meet}88`,1.4,[5,5]);text(ctx,`相遇 t=${fmt(hit.time)} s`,x,42,C.meet,10,"center",700);}
    const trackY=height-28;line(ctx,45,trackY,width-45,trackY,"rgba(223,229,223,.18)",4);line(ctx,45,trackY,45+(width-90)*state.time/end,trackY,C.meet,4);ctx.fillStyle=C.meet;ctx.beginPath();ctx.arc(45+(width-90)*state.time/end,trackY,7,0,Math.PI*2);ctx.fill();text(ctx,`参考系：${state.frame==="ground"?"地面":state.frame==="A"?"随 A 车":"随 B 车初速"}`,width-15,height-8,C.muted,9,"right");}
  function axes(context,width,height,xMin,xMax,yMin,yMax,xLabel,yLabel){const p={l:47,r:18,t:20,b:34},x=v=>p.l+(v-xMin)/(xMax-xMin)*(width-p.l-p.r),y=v=>height-p.b-(v-yMin)/(Math.max(1e-9,yMax-yMin))*(height-p.t-p.b);line(context,p.l,p.t,p.l,height-p.b,"rgba(223,229,223,.28)");line(context,p.l,height-p.b,width-p.r,height-p.b,"rgba(223,229,223,.28)");text(context,xLabel,width-p.r,height-5,C.muted,8,"right");text(context,yLabel,7,13,C.muted,8);return{x,y,p};}
  function plot(context,points,map,key,color){context.strokeStyle=color;context.lineWidth=2;context.beginPath();points.forEach((point,index)=>{const x=map.x(point.time),y=map.y(point[key]);index?context.lineTo(x,y):context.moveTo(x,y)});context.stroke();}
  function drawCharts(){const end=duration(),series=M.series(input(),end,180),values=series.flatMap(s=>[s.xA,s.xB]),min=Math.min(...values),max=Math.max(...values),pad=Math.max(5,(max-min)*.12);let s=size(R.positionChart,pctx);background(pctx,s.width,s.height);let map=axes(pctx,s.width,s.height,0,end,min-pad,max+pad,"t / s","x / m");plot(pctx,series,map,"xA",C.a);plot(pctx,series,map,"xB",C.b);line(pctx,map.x(state.time),map.p.t,map.x(state.time),s.height-map.p.b,C.meet,1,[4,4]);
    s=size(R.relativeChart,rctx);background(rctx,s.width,s.height);const sep=series.map(p=>p.separation),abs=Math.max(5,...sep.map(Math.abs))*1.12;map=axes(rctx,s.width,s.height,0,end,-abs,abs,"t / s","Δx / m");line(rctx,map.p.l,map.y(0),s.width-map.p.r,map.y(0),`${C.meet}88`,1,[4,4]);plot(rctx,series,map,"separation",C.relative);line(rctx,map.x(state.time),map.p.t,map.x(state.time),s.height-map.p.b,C.meet,1,[4,4]);}
  function range(input,value){input.value=value;input.style.setProperty("--range-progress",`${(value-Number(input.min))/(Number(input.max)-Number(input.min))*100}%`);}
  function render(){const hit=meeting(),end=duration();state.time=clamp(state.time,0,end);R.timeInput.max=end;const current=M.stateAt(state.time,input()),mode=MODES[state.mode];range(R.gapInput,state.gap);range(R.speedAInput,state.vA);range(R.speedBInput,state.vB);range(R.accelInput,state.aB);range(R.delayInput,state.delayB);range(R.timeInput,state.time);R.gapValue.textContent=`${fmt(state.gap,0)} m`;R.speedAValue.textContent=`${fmt(state.vA,1)} m/s`;R.speedBValue.textContent=`${fmt(state.vB,1)} m/s`;R.accelValue.textContent=`${fmt(state.aB,1)} m/s²`;R.delayValue.textContent=`${fmt(state.delayB,1)} s`;R.timeValue.textContent=`${fmt(state.time)} s`;R.timeMetric.textContent=`${fmt(state.time)} s`;R.positionAMetric.textContent=`${fmt(current.xA)} m`;R.positionBMetric.textContent=`${fmt(current.xB)} m`;R.separationMetric.textContent=`${fmt(current.separation)} m`;R.relativeMetric.textContent=`${fmt(current.relativeVelocity)} m/s`;R.meetingMetric.textContent=hit.exists?`${fmt(hit.time)} s`:"无相遇";R.modeTitle.textContent=mode.title;R.modeGoal.textContent=mode.goal;R.stageHint.textContent=mode.hint;const passed=hit.exists&&state.time>=hit.time;R.stateBadge.textContent=!hit.exists?"不会相遇":passed?"已经相遇":"尚未相遇";R.stateBadge.className=`state-badge ${!hit.exists?"is-missed":passed?"is-met":""}`;R.natureText.textContent=!hit.exists?"当前参数下位置函数没有未来交点":Math.abs(current.separation)<.3?"两车位于同一位置":current.separation*current.relativeVelocity<0?"有向间距正在减小":"有向间距正在增大";R.explanationText.textContent=`d(Δx)/dt = vA−vB = ${fmt(current.relativeVelocity)} m/s`;R.formulaReadout.textContent=`Δx = xA − xB = ${fmt(current.separation)} m`;R.stepIndex.textContent=String(state.guideStep+1).padStart(2,"0");R.stepTitle.textContent=STEPS[state.guideStep][0];R.stepPrompt.textContent=STEPS[state.guideStep][1];R.sceneTabs.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===state.mode));R.routeSteps.forEach((b,i)=>b.classList.toggle("is-active",i===state.guideStep));R.frameButtons.forEach(b=>b.classList.toggle("is-active",b.dataset.frame===state.frame));R.playButton.textContent=state.running?"▶ 运行中":"▶ 运行";R.positionStatus.textContent=hit.exists?`交点 t=${fmt(hit.time)} s`:"两条世界线不相交";R.relativeStatus.textContent=`当前 Δv=${fmt(current.relativeVelocity)} m/s`;drawScene();drawCharts();}
  function setMode(mode){if(!MODES[mode])return;state.mode=mode;state.frame="ground";state.time=0;state.running=false;if(mode==="chase")Object.assign(state,{gap:40,vA:6,vB:10,aB:0,delayB:0});if(mode==="delay")Object.assign(state,{gap:20,vA:4,vB:12,aB:0,delayB:2});if(mode==="opposite")Object.assign(state,{gap:80,vA:6,vB:-10,aB:0,delayB:0});if(mode==="reference")Object.assign(state,{gap:36,vA:5,vB:9,aB:0,delayB:0});render();}
  function reset(){Object.assign(state,{mode:"chase",gap:40,vA:6,vB:10,aB:0,delayB:0,frame:"ground",time:0,running:false,guideStep:0,dragging:false,showStrobe:true,showVectors:true,showMeeting:true,showRelative:true});[[R.showStrobeToggle,"showStrobe"],[R.showVectorsToggle,"showVectors"],[R.showMeetingToggle,"showMeeting"],[R.showRelativeToggle,"showRelative"]].forEach(([input,key])=>input.checked=state[key]);render();}
  function setState(next={}){if(!next||typeof next!=="object")return;if(typeof next.mode==="string"&&MODES[next.mode])state.mode=next.mode;const ranges={gap:[10,100],vA:[-15,15],vB:[-15,20],aB:[-3,4],delayB:[0,8],time:[0,30]};Object.entries(ranges).forEach(([key,[min,max]])=>{if(Number.isFinite(Number(next[key])))state[key]=clamp(next[key],min,max)});if(["ground","A","B"].includes(next.frame))state.frame=next.frame;if(Number.isFinite(Number(next.guideStep)))state.guideStep=clamp(Math.round(next.guideStep),0,STEPS.length-1);["showStrobe","showVectors","showMeeting","showRelative"].forEach(key=>{if(typeof next[key]==="boolean")state[key]=next[key]});state.running=false;state.dragging=false;[[R.showStrobeToggle,"showStrobe"],[R.showVectorsToggle,"showVectors"],[R.showMeetingToggle,"showMeeting"],[R.showRelativeToggle,"showRelative"]].forEach(([input,key])=>input.checked=state[key]);render();}
  [[R.gapInput,"gap"],[R.speedAInput,"vA"],[R.speedBInput,"vB"],[R.accelInput,"aB"],[R.delayInput,"delayB"],[R.timeInput,"time"]].forEach(([input,key])=>input.addEventListener("input",()=>{state[key]=Number(input.value);state.running=false;render()}));R.sceneTabs.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));R.routeSteps.forEach((b,i)=>b.addEventListener("click",()=>{state.guideStep=i;render()}));R.frameButtons.forEach(b=>b.addEventListener("click",()=>{state.frame=b.dataset.frame;render()}));R.playButton.addEventListener("click",()=>{if(state.time>=duration())state.time=0;state.running=true;render()});R.pauseButton.addEventListener("click",()=>{state.running=false;render()});R.keyButton.addEventListener("click",()=>{const hit=meeting();if(hit.exists)state.time=hit.time;state.running=false;render()});R.resetButton.addEventListener("click",reset);[[R.showStrobeToggle,"showStrobe"],[R.showVectorsToggle,"showVectors"],[R.showMeetingToggle,"showMeeting"],[R.showRelativeToggle,"showRelative"]].forEach(([input,key])=>input.addEventListener("change",()=>{state[key]=input.checked;render()}));R.guideButton.addEventListener("click",()=>R.guideDialog.showModal());R.stepButton.addEventListener("click",()=>{state.guideStep=(state.guideStep+1)%STEPS.length;render()});R.focusButton.addEventListener("click",()=>{const on=document.body.classList.toggle("focus-mode");R.focusButton.setAttribute("aria-pressed",String(on))});R.fullscreenButton.addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
  function pointerTime(event){const rect=R.canvas.getBoundingClientRect();state.time=clamp((event.clientX-rect.left)/rect.width*duration(),0,duration());state.running=false;render();}R.canvas.addEventListener("pointerdown",event=>{state.dragging=true;R.canvas.setPointerCapture?.(event.pointerId);pointerTime(event)});R.canvas.addEventListener("pointermove",event=>{if(state.dragging)pointerTime(event)});R.canvas.addEventListener("pointerup",()=>state.dragging=false);R.canvas.addEventListener("pointercancel",()=>state.dragging=false);window.addEventListener("resize",render);
  let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.running){state.time=Math.min(duration(),state.time+dt);if(state.time>=duration())state.running=false;render()}requestAnimationFrame(frame)}window.pursuitLab={solve:(time,next={})=>M.stateAt(time,inputFor(next)),encounter:(next={})=>M.encounter(inputFor(next)),getState:()=>({...state}),setMode,setState,reset};render();requestAnimationFrame(frame);
})();
