(function () {
  "use strict";
  const M = window.RailRodModel;
  if (!M) throw new Error("RailRodModel is required");
  const MODES = {
    force: ["恒力启动", "速度增大时，为什么加速度会逐渐减小"],
    coast: ["撤力制动", "撤去外力后，动能以什么路径转化为焦耳热"],
    incline: ["斜面导轨", "重力沿轨分力怎样与摩擦、磁阻尼共同决定终态"],
    circuit: ["电路负载", "接电源与接电容为何产生两种不同的机电反馈"],
  };
  const STEPS = [["先看反馈", "速度增大后，感应电流和安培力如何响应？"], ["再找终态", "驱动力与磁阻力何时达到动态平衡？"], ["最后核能量", "输入能量分别流向动能、焦耳热或电场能多少？"]];
  const state = { mode: "force", circuitKind: "source", massKg: .5, lengthM: .5, fieldT: .8, resistanceOhm: .8, forceN: 1.2, initialSpeedMs: 0, angleDeg: 20, friction: .05, capacitanceF: 2, sourceVoltageV: 3, timeS: 2.5, guideStep: 0, showVectors: true, showCurrent: true, showTrail: true, showLedger: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { rail: $("railCanvas"), response: $("responseChart"), energy: $("energyChart"), mass: $("massInput"), length: $("lengthInput"), field: $("fieldInput"), resistance: $("resistanceInput"), force: $("forceInput"), speed: $("speedInput"), time: $("timeInput"), voltage: $("voltageInput"), capacitance: $("capacitanceInput"), angle: $("angleInput"), frictionInput: $("frictionInput"), kind: $("circuitKind"), massValue: $("massValue"), lengthValue: $("lengthValue"), fieldValue: $("fieldValue"), resistanceValue: $("resistanceValue"), forceValue: $("forceValue"), speedValue: $("speedValue"), timeValue: $("timeValue"), voltageValue: $("voltageValue"), capacitanceValue: $("capacitanceValue"), angleValue: $("angleValue"), frictionValue: $("frictionValue"), vectors: $("showVectorsToggle"), current: $("showCurrentToggle"), trail: $("showTrailToggle"), ledger: $("showLedgerToggle"), velocityMetric: $("velocityMetric"), emfMetric: $("emfMetric"), currentMetric: $("currentMetric"), magneticMetric: $("magneticMetric"), terminalMetric: $("terminalMetric"), residualMetric: $("residualMetric"), nature: $("natureText"), explanation: $("explanationText"), responseStatus: $("responseStatus"), energyStatus: $("energyStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), hint: $("stageHint"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.rail.getContext("2d"), rctx = R.response.getContext("2d"), ectx = R.energy.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, color, label) { line(k, x1, y1, x2, y2, color, 3); const a = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = color; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 9 * Math.cos(a - .5), y2 - 9 * Math.sin(a - .5)); k.lineTo(x2 - 9 * Math.cos(a + .5), y2 - 9 * Math.sin(a + .5)); k.fill(); if (label) text(k, label, x2 + 7, y2 - 7, color, 10, "left", 800); }
  function drawRail() {
    const s = size(R.rail, ctx, 270), p = M.solve(input()), left = 70, right = s.width - 65, top = 82, bottom = s.height - 72;
    bg(ctx, s.width, s.height);
    for (let y = top + 18; y < bottom; y += 50) for (let x = left + 18; x < right; x += 52) { ctx.strokeStyle = C.cyan; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.arc(x, y, 4, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = C.cyan; ctx.beginPath(); ctx.arc(x, y, 1.5, 0, Math.PI * 2); ctx.fill(); }
    line(ctx, left, top, right, top, C.text, 5); line(ctx, left, bottom, right, bottom, C.text, 5); line(ctx, left, top, left, bottom, C.amber, 4);
    const progress = clamp(p.displacementM / Math.max(3, Math.abs(p.displacementM) + 1), 0, 1), rodX = left + 70 + progress * (right - left - 110);
    if (state.showTrail) for (let i = 1; i <= 4; i++) line(ctx, rodX - i * 30, top + 4, rodX - i * 30, bottom - 4, `rgba(240,185,81,${.28 - i * .04})`, 4);
    line(ctx, rodX, top + 3, rodX, bottom - 3, C.amber, 9); text(ctx, "B ⊙", right - 8, 47, C.cyan, 11, "right", 800);
    if (state.showCurrent && Math.abs(p.currentA) > 1e-6) { arrow(ctx, rodX, bottom - 32, rodX, top + 32, C.violet, "I"); arrow(ctx, left + 20, top, rodX - 20, top, C.violet, ""); }
    if (state.showVectors) { arrow(ctx, rodX, top - 25, rodX + clamp(Math.abs(p.driveForceN) * 65, 24, 90), top - 25, C.green, state.mode === "incline" ? "mg∥−f" : state.mode === "circuit" && state.circuitKind === "source" ? "F安" : "F"); if (!(state.mode === "circuit" && state.circuitKind === "source")) arrow(ctx, rodX, bottom + 28, rodX - clamp(Math.abs(p.magneticForceN) * 65, 20, 90), bottom + 28, C.red, "F安"); arrow(ctx, rodX, (top + bottom) / 2, rodX + clamp(Math.abs(p.speedMs) * 18, 16, 110), (top + bottom) / 2, C.cyan, "v"); }
    if (state.mode === "circuit") { ctx.strokeStyle = C.green; ctx.lineWidth = 2; ctx.strokeRect(left - 42, (top + bottom) / 2 - 28, 40, 56); text(ctx, state.circuitKind === "source" ? `${fmt(state.sourceVoltageV, 1)} V` : `${fmt(state.capacitanceF, 1)} F`, left - 22, (top + bottom) / 2 + 4, C.green, 10, "center", 800); }
    text(ctx, `t=${fmt(state.timeS, 2)} s`, left, s.height - 24, C.text, 10); text(ctx, `x=${fmt(p.displacementM, 2)} m`, right, s.height - 24, C.amber, 10, "right", 800);
  }
  function axes(k, s, xmax, ymax) { const p = { l: 44, r: 18, t: 20, b: 30 }, x = v => p.l + v / xmax * (s.width - p.l - p.r), y = v => s.height - p.b - v / ymax * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(223,229,223,.3)"); line(k, p.l, s.height - p.b, s.width - p.r, s.height - p.b, "rgba(223,229,223,.3)"); return { x, y, p }; }
  function drawCharts() {
    const p = M.solve(input()), series = M.series(input(), 15, 180); let s = size(R.response, rctx); bg(rctx, s.width, s.height); const vmax = Math.max(.1, ...series.map(x => Math.abs(x.speedMs))) * 1.1, imax = Math.max(.1, ...series.map(x => Math.abs(x.currentA))) * 1.1, a = axes(rctx, s, 15, vmax); rctx.strokeStyle = C.cyan; rctx.lineWidth = 2; rctx.beginPath(); series.forEach((v, i) => i ? rctx.lineTo(a.x(v.timeS), a.y(Math.abs(v.speedMs))) : rctx.moveTo(a.x(v.timeS), a.y(Math.abs(v.speedMs)))); rctx.stroke(); rctx.strokeStyle = C.violet; rctx.beginPath(); series.forEach((v, i) => { const yy = a.y(Math.abs(v.currentA) / imax * vmax); i ? rctx.lineTo(a.x(v.timeS), yy) : rctx.moveTo(a.x(v.timeS), yy); }); rctx.stroke(); line(rctx, a.x(state.timeS), a.p.t, a.x(state.timeS), s.height - a.p.b, C.amber, 1, [4, 4]); text(rctx, "v", 8, 14, C.cyan, 9, "left", 800); text(rctx, "I", 24, 14, C.violet, 9, "left", 800);
    s = size(R.energy, ectx); bg(ectx, s.width, s.height); const cap = p.capacitorEnergyChangeJ || 0, values = state.showLedger ? [["输入", p.driveWorkJ, C.green], ["动能", p.kineticChangeJ, C.cyan], ["热", p.resistorHeatJ, C.red], ["电场能", cap, C.violet]] : [], max = Math.max(.01, ...values.map(v => Math.abs(v[1]))), x0 = 82; values.forEach((v, i) => { const y = 42 + i * 40, width = Math.abs(v[1]) / max * (s.width - 130); text(ectx, v[0], 16, y + 4, C.text, 9); ectx.fillStyle = v[2]; ectx.fillRect(x0, y - 8, width, 16); text(ectx, `${fmt(v[1])} J`, s.width - 16, y + 4, v[2], 9, "right", 800); });
  }
  function range(element, value) { element.value = value; element.style.setProperty("--range-progress", `${(value - Number(element.min)) / (Number(element.max) - Number(element.min)) * 100}%`); }
  function render() {
    const p = M.solve(input()), mode = MODES[state.mode], terminal = p.terminalReached, stopped = p.stoppedByStaticFriction;
    document.body.classList.toggle("is-circuit", state.mode === "circuit"); document.body.classList.toggle("is-incline", state.mode === "incline"); R.modeTitle.textContent = mode[0]; R.modeGoal.textContent = mode[1]; R.badge.textContent = stopped ? "静摩擦维持静止" : terminal ? "已接近终端状态" : p.accelerationMs2 < 0 ? "磁阻尼减速" : "正在加速"; R.badge.className = `state-badge ${terminal ? "is-terminal" : stopped ? "is-stopped" : ""}`;
    const fields = [[R.mass, state.massKg, R.massValue, "kg", 2], [R.length, state.lengthM, R.lengthValue, "m", 2], [R.field, state.fieldT, R.fieldValue, "T", 2], [R.resistance, state.resistanceOhm, R.resistanceValue, "Ω", 2], [R.force, state.forceN, R.forceValue, "N", 2], [R.speed, state.initialSpeedMs, R.speedValue, "m/s", 2], [R.time, state.timeS, R.timeValue, "s", 2], [R.voltage, state.sourceVoltageV, R.voltageValue, "V", 2], [R.capacitance, state.capacitanceF, R.capacitanceValue, "F", 2], [R.angle, state.angleDeg, R.angleValue, "°", 1], [R.frictionInput, state.friction, R.frictionValue, "", 3]]; fields.forEach(([el, value, label, unit, digits]) => { range(el, value); label.textContent = `${fmt(value, digits)} ${unit}`; }); R.kind.value = state.circuitKind;
    R.velocityMetric.textContent = `${fmt(p.speedMs)} m/s`; R.emfMetric.textContent = `${fmt(p.emfV)} V`; R.currentMetric.textContent = `${fmt(p.currentA)} A`; R.magneticMetric.textContent = `${fmt(p.magneticForceN)} N`; R.terminalMetric.textContent = `${fmt(p.terminalSpeedMs)} m/s`; R.residualMetric.textContent = `${fmt(p.energyResidualJ, 6)} J`; R.nature.textContent = state.mode === "circuit" && state.circuitKind === "capacitor" ? `等效质量增加 ${fmt(p.electromagneticMassKg)} kg` : stopped ? "沿轨驱动力不足以克服摩擦" : terminal ? "驱动力与磁反馈已接近平衡" : "磁反馈随速度变化"; R.explanation.textContent = state.mode === "circuit" && state.circuitKind === "capacitor" ? "F=(m+CB²L²)a" : state.mode === "circuit" ? "U−BLv=IR" : "F−B²L²v/R=ma"; R.responseStatus.textContent = `t=${fmt(state.timeS, 2)}s · τ=${fmt(p.tauS, 2)}s`; R.energyStatus.textContent = Math.abs(p.energyResidualJ) < 1e-8 ? "账本闭合" : "检查残差"; R.formula.textContent = state.mode === "circuit" && state.circuitKind === "capacitor" ? "F=(m+CB²L²)a" : state.mode === "circuit" ? "U−BLv=IR" : "ε=BLv";
    R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawRail(); drawCharts();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "force") Object.assign(state, { initialSpeedMs: 0, forceN: 1.2, timeS: 2.5 }); if (mode === "coast") Object.assign(state, { initialSpeedMs: 6, forceN: 0, timeS: 2.5 }); if (mode === "incline") Object.assign(state, { initialSpeedMs: 0, forceN: 1.2, angleDeg: 20, friction: .05, timeS: 2.5 }); if (mode === "circuit") Object.assign(state, { initialSpeedMs: 0, forceN: 1.2, timeS: 2.5 }); render(); }
  function reset() { Object.assign(state, { mode: "force", circuitKind: "source", massKg: .5, lengthM: .5, fieldT: .8, resistanceOhm: .8, forceN: 1.2, initialSpeedMs: 0, angleDeg: 20, friction: .05, capacitanceF: 2, sourceVoltageV: 3, timeS: 2.5, guideStep: 0, showVectors: true, showCurrent: true, showTrail: true, showLedger: true, dragging: false }); [[R.vectors, "showVectors"], [R.current, "showCurrent"], [R.trail, "showTrail"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { massKg: [.1, 5], lengthM: [.1, 1.5], fieldT: [0, 2], resistanceOhm: [.05, 10], forceN: [0, 10], initialSpeedMs: [0, 15], angleDeg: [0, 45], friction: [0, .5], capacitanceF: [.05, 10], sourceVoltageV: [0, 12], timeS: [0, 15] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); if (MODES[next.mode]) state.mode = next.mode; if (["source", "capacitor"].includes(next.circuitKind)) state.circuitKind = next.circuitKind; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showVectors", "showCurrent", "showTrail", "showLedger"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.mass, "massKg"], [R.length, "lengthM"], [R.field, "fieldT"], [R.resistance, "resistanceOhm"], [R.force, "forceN"], [R.speed, "initialSpeedMs"], [R.time, "timeS"], [R.voltage, "sourceVoltageV"], [R.capacitance, "capacitanceF"], [R.angle, "angleDeg"], [R.frictionInput, "friction"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); R.kind.addEventListener("change", () => { state.circuitKind = R.kind.value; render(); }); [[R.vectors, "showVectors"], [R.current, "showCurrent"], [R.trail, "showTrail"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.rail.getBoundingClientRect(); state.timeS = clamp((event.clientX - box.left) / box.width * 15, 0, 15); render(); } R.rail.addEventListener("pointerdown", event => { state.dragging = true; R.rail.setPointerCapture?.(event.pointerId); drag(event); }); R.rail.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.rail.addEventListener("pointerup", () => state.dragging = false); R.rail.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.railRodLab = { solve: next => M.solve(next), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
