(function () {
  "use strict";
  const M = window.RutherfordModel;
  if (!M) throw new Error("RutherfordModel is required");
  const MODES = { trajectory: ["单粒子轨迹", "拖动入射高度，观察库仑斥力如何形成双曲线偏转"], statistics: ["束流统计", "按入射面积均匀采样，区分常见小角与稀有大角事件"], closest: ["最近距离", "比较能量、核电荷和碰撞参数对最近接近的限制"], compare: ["模型对照", "检验均匀正电球为什么无法解释大角反弹"] };
  const STEPS = [["先调碰撞参数", "为什么绝大多数远离原子核的 α 粒子只发生小角偏转？"], ["再积累统计", "入射束横截面均匀时，为什么碰撞参数应按 p(b)∝b 采样？"], ["最后比较模型", "哪一种正电荷分布能够产生少量但明确的大角散射？"]];
  const state = { mode: "trajectory", projectileCharge: 2, targetZ: 79, energyMeV: 5, impactFm: 50, maxImpactFm: 200, atomRadiusFm: 50000, seed: 17, eventCount: 2000, guideStep: 0, showAsymptote: true, showClosest: true, showEvents: true, showThomson: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("scatterCanvas"), histogram: $("histogramChart"), secondary: $("secondaryChart"), target: $("targetInput"), energy: $("energyInput"), impact: $("impactInput"), maxImpact: $("maxImpactInput"), events: $("eventsInput"), radius: $("radiusInput"), seed: $("seedInput"), targetValue: $("targetValue"), energyValue: $("energyValue"), impactValue: $("impactValue"), maxImpactValue: $("maxImpactValue"), eventsValue: $("eventsValue"), radiusValue: $("radiusValue"), seedValue: $("seedValue"), asymptote: $("showAsymptoteToggle"), closest: $("showClosestToggle"), eventToggle: $("showEventsToggle"), thomson: $("showThomsonToggle"), angleMetric: $("angleMetric"), closestMetric: $("closestMetric"), headMetric: $("headMetric"), b90Metric: $("b90Metric"), backMetric: $("backMetric"), thomsonMetric: $("thomsonMetric"), nature: $("natureText"), explanation: $("explanationText"), badge: $("stateBadge"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), histogramStatus: $("histogramStatus"), secondaryKicker: $("secondaryKicker"), secondaryTitle: $("secondaryTitle"), secondaryStatus: $("secondaryStatus"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")], materials: [...document.querySelectorAll("[data-z]")] };
  const mctx = R.main.getContext("2d"), hctx = R.histogram.getContext("2d"), sctx = R.secondary.getContext("2d");
  const C = { bg: "#070b0e", grid: "rgba(220,230,226,.055)", cyan: "#64c7d9", amber: "#f2bd52", violet: "#b58ce5", green: "#79d992", red: "#ff786e", text: "#aab3ad", muted: "#707b75" };
  const clamp = M.clamp;
  const fmt = (value, digits = 3) => Number(value).toFixed(digits).replace("-", "−");
  function size(canvas, context, minHeight = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minHeight, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, stroke, width = 1, dash = []) { k.save(); k.strokeStyle = stroke; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, fill = C.text, px = 9, align = "left", weight = 600) { k.fillStyle = fill; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 15; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 15; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function drawMain() { const s = size(R.main, mctx, 280), result = M.scatter(state), trajectory = M.trajectory(state, 700), maxX = Math.max(...trajectory.map(p => Math.abs(p.xFm)), 300), maxY = Math.max(...trajectory.map(p => Math.abs(p.yFm)), state.impactFm * 2, 200), scale = Math.min((s.width - 80) / (2 * maxX), (s.height - 60) / (2 * maxY)), cx = s.width * .52, cy = s.height * .55, map = p => ({ x: cx + p.xFm * scale, y: cy - p.yFm * scale }); bg(mctx, s.width, s.height); if (state.showAsymptote) { const first = map(trajectory[0]), last = map(trajectory.at(-1)); line(mctx, 20, cy - state.impactFm * scale, cx, cy - state.impactFm * scale, "rgba(100,199,217,.55)", 1, [6, 5]); const theta = result.angleRad; line(mctx, cx, cy, cx + Math.cos(theta) * s.width, cy - Math.sin(theta) * s.width, "rgba(181,140,229,.55)", 1, [6, 5]); text(mctx, `θ=${fmt(result.angleDeg, 2)}°`, last.x - 6, last.y - 10, C.violet, 9, "right"); text(mctx, `b=${fmt(state.impactFm, 1)}fm`, first.x + 8, first.y - 8, C.cyan, 9); }
    mctx.strokeStyle = C.amber; mctx.lineWidth = 2.5; mctx.beginPath(); trajectory.forEach((point, index) => { const p = map(point); index ? mctx.lineTo(p.x, p.y) : mctx.moveTo(p.x, p.y); }); mctx.stroke(); mctx.fillStyle = C.red; mctx.shadowColor = C.red; mctx.shadowBlur = 12; mctx.beginPath(); mctx.arc(cx, cy, 9, 0, Math.PI * 2); mctx.fill(); mctx.shadowBlur = 0; text(mctx, `+${state.targetZ}e`, cx, cy + 3, "#180806", 8, "center", 800); if (state.showClosest) { const closest = trajectory.reduce((best, point) => point.radiusFm < best.radiusFm ? point : best), p = map(closest); line(mctx, cx, cy, p.x, p.y, C.green, 2); mctx.fillStyle = C.green; mctx.beginPath(); mctx.arc(p.x, p.y, 5, 0, Math.PI * 2); mctx.fill(); text(mctx, `rmin=${fmt(result.closestFm, 1)}fm`, p.x + 8, p.y - 8, C.green, 9); }
    if (state.mode === "statistics" && state.showEvents) { const events = M.eventAngles(state, Math.min(state.eventCount, 1200)); events.forEach((event, index) => { const radius = Math.min(s.width, s.height) * (.34 + (index % 7) * .012), angle = (index % 2 ? 1 : -1) * event.angleRad + event.azimuthRad * .04, x = cx + Math.cos(angle) * radius, y = cy - Math.sin(angle) * radius; mctx.fillStyle = event.backscattered ? C.violet : C.cyan; mctx.globalAlpha = event.backscattered ? .85 : .16; mctx.fillRect(x, y, event.backscattered ? 3 : 2, event.backscattered ? 3 : 2); }); mctx.globalAlpha = 1; }
    if (state.mode === "compare" && state.showThomson) { const small = M.thomsonAngle(state).angleRad, y = cy - state.impactFm * scale; line(mctx, 20, y, s.width - 20, y - Math.tan(small) * (s.width - 40), C.green, 2, [5, 4]); text(mctx, "汤姆孙均匀正电球：近似直穿", s.width - 20, y - 10, C.green, 9, "right"); }
    text(mctx, state.mode === "statistics" ? "事件点按入射面积均匀采样，不代表确定粒子轨迹" : "上下拖动入射束改变碰撞参数 b", 18, s.height - 12, C.muted, 8); }
  function axes(k, s, xmin, xmax, ymin, ymax, log = false) { const p = { l: 40, r: 14, t: 18, b: 28 }, transform = value => log ? Math.log10(Math.max(1e-12, value)) : value, tymin = transform(ymin), tymax = transform(ymax), x = v => p.l + (v - xmin) / (xmax - xmin) * (s.width - p.l - p.r), y = v => s.height - p.b - (transform(v) - tymin) / (tymax - tymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(220,230,226,.28)"); line(k, p.l, s.height - p.b, s.width - p.r, s.height - p.b, "rgba(220,230,226,.28)"); return { x, y, p }; }
  function drawHistogram() { const s = size(R.histogram, hctx), events = M.eventAngles(state, state.eventCount), bins = 36, counts = Array(bins).fill(0); events.forEach(event => counts[Math.min(bins - 1, Math.floor(event.angleDeg / 180 * bins))] += 1); const max = Math.max(1, ...counts), a = axes(hctx, s, 0, 180, 0, max); bg(hctx, s.width, s.height); counts.forEach((count, index) => { const x1 = a.x(index * 180 / bins), x2 = a.x((index + 1) * 180 / bins); hctx.fillStyle = index >= bins / 2 ? C.violet : C.cyan; hctx.globalAlpha = .35 + .65 * count / max; hctx.fillRect(x1 + 1, a.y(count), Math.max(1, x2 - x1 - 2), a.y(0) - a.y(count)); }); hctx.globalAlpha = 1; line(hctx, a.x(90), a.y(0), a.x(90), a.y(max), C.amber, 1, [4, 4]); text(hctx, "计数", 7, 13, C.cyan); text(hctx, "θ/°", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawImpact() { const s = size(R.secondary, sctx), values = Array.from({ length: 220 }, (_, i) => M.scatter({ ...state, impactFm: 1 + 299 * i / 219 })), a = axes(sctx, s, 1, 300, .1, 180, true); bg(sctx, s.width, s.height); sctx.strokeStyle = C.amber; sctx.lineWidth = 2; sctx.beginPath(); values.forEach((v, i) => i ? sctx.lineTo(a.x(v.impactFm), a.y(v.angleDeg)) : sctx.moveTo(a.x(v.impactFm), a.y(v.angleDeg))); sctx.stroke(); const current = M.scatter(state); sctx.fillStyle = C.green; sctx.beginPath(); sctx.arc(a.x(state.impactFm), a.y(current.angleDeg), 5, 0, Math.PI * 2); sctx.fill(); line(sctx, a.x(current.b90Fm), a.y(.1), a.x(current.b90Fm), a.y(180), C.violet, 1, [4, 4]); text(sctx, "θ/°（对数）", 7, 13, C.amber); text(sctx, "b/fm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawCompare() { const s = size(R.secondary, sctx), a = axes(sctx, s, 1, 300, 1e-6, 180, true); bg(sctx, s.width, s.height); [[false, C.amber], [true, C.green]].forEach(([thomson, stroke]) => { sctx.strokeStyle = stroke; sctx.lineWidth = 2; sctx.beginPath(); for (let i = 0; i < 220; i += 1) { const b = 1 + 299 * i / 219, value = thomson ? M.thomsonAngle({ ...state, impactFm: b }).angleDeg : M.scatter({ ...state, impactFm: b }).angleDeg; i ? sctx.lineTo(a.x(b), a.y(value)) : sctx.moveTo(a.x(b), a.y(value)); } sctx.stroke(); }); text(sctx, "核式结构", 8, 13, C.amber); text(sctx, "汤姆孙", 65, 13, C.green); text(sctx, "b/fm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawSecondary() { state.mode === "compare" ? drawCompare() : drawImpact(); }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - +el.min) / (+el.max - +el.min) * 100}%`); }
  function render() { const d = M.scatter(state), th = M.thomsonAngle(state), probability = M.expectedFractionAbove(90, state), back = d.backscattered; [[R.target, state.targetZ], [R.energy, state.energyMeV], [R.impact, state.impactFm], [R.maxImpact, state.maxImpactFm], [R.events, state.eventCount], [R.radius, state.atomRadiusFm], [R.seed, state.seed]].forEach(([el, value]) => range(el, value)); R.targetValue.textContent = fmt(state.targetZ, 0); R.energyValue.textContent = `${fmt(state.energyMeV, 2)} MeV`; R.impactValue.textContent = `${fmt(state.impactFm, 1)} fm`; R.maxImpactValue.textContent = `${fmt(state.maxImpactFm, 0)} fm`; R.eventsValue.textContent = fmt(state.eventCount, 0); R.radiusValue.textContent = `${fmt(state.atomRadiusFm, 0)} fm`; R.seedValue.textContent = fmt(state.seed, 0); R.angleMetric.textContent = `${fmt(d.angleDeg)}°`; R.closestMetric.textContent = `${fmt(d.closestFm)} fm`; R.headMetric.textContent = `${fmt(d.headOnClosestFm)} fm`; R.b90Metric.textContent = `${fmt(d.b90Fm)} fm`; R.backMetric.textContent = `${fmt(probability * 100, 3)}%`; R.thomsonMetric.textContent = `${fmt(th.angleDeg, 6)}°`; R.nature.textContent = back ? "反向散射" : d.angleDeg > 20 ? "明显偏转" : "小角前向散射"; R.explanation.textContent = back ? "极小 b 使 α 粒子接近高电荷密度核心" : d.angleDeg > 20 ? "小 b 使粒子进入强库仑场区域" : "大多数粒子远离原子核"; R.badge.textContent = `${back ? "反向" : "前向"}散射 ${fmt(d.angleDeg, 1)}°`; R.badge.className = `state-badge${back ? " is-back" : ""}`; R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.histogramStatus.textContent = `N=${state.eventCount} · 大角预期 ${fmt(probability * 100, 2)}%`; R.secondaryKicker.textContent = state.mode === "compare" ? "MODEL COMPARISON" : "IMPACT RESPONSE"; R.secondaryTitle.textContent = state.mode === "compare" ? "核式结构与均匀正电球" : "散射角—碰撞参数"; R.secondaryStatus.textContent = state.mode === "compare" ? `相差约 ${fmt(d.angleDeg / Math.max(1e-12, th.angleDeg), 0)} 倍` : `b=${fmt(state.impactFm, 1)}fm`; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = state.mode === "statistics" ? "p(b)db=2b db/bmax²" : state.mode === "compare" ? "大角事件排除均匀正电球" : "θ=2 arctan[k/(2Eb)]"; R.tabs.forEach(button => button.classList.toggle("is-active", button.dataset.mode === state.mode)); R.route.forEach((button, index) => button.classList.toggle("is-active", index === state.guideStep)); R.materials.forEach(button => button.classList.toggle("is-active", +button.dataset.z === state.targetZ)); drawMain(); drawHistogram(); drawSecondary(); }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "trajectory") Object.assign(state, { impactFm: 50, energyMeV: 5 }); if (mode === "statistics") Object.assign(state, { impactFm: 80, eventCount: 4000, maxImpactFm: 200 }); if (mode === "closest") Object.assign(state, { impactFm: 5, energyMeV: 5 }); if (mode === "compare") Object.assign(state, { impactFm: 20, energyMeV: 5, atomRadiusFm: 50000 }); render(); }
  function reset() { Object.assign(state, { mode: "trajectory", projectileCharge: 2, targetZ: 79, energyMeV: 5, impactFm: 50, maxImpactFm: 200, atomRadiusFm: 50000, seed: 17, eventCount: 2000, guideStep: 0, showAsymptote: true, showClosest: true, showEvents: true, showThomson: true, dragging: false }); [[R.asymptote, "showAsymptote"], [R.closest, "showClosest"], [R.eventToggle, "showEvents"], [R.thomson, "showThomson"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { if (MODES[next.mode]) state.mode = next.mode; [["projectileCharge", 1, 4], ["targetZ", 1, 92], ["energyMeV", .5, 20], ["impactFm", .05, 500], ["maxImpactFm", 5, 1000], ["atomRadiusFm", 1000, 100000], ["seed", 1, 1e9], ["eventCount", 100, 10000], ["guideStep", 0, 2]].forEach(([key, min, max]) => { if (Number.isFinite(+next[key])) state[key] = clamp(+next[key], min, max); }); ["showAsymptote", "showClosest", "showEvents", "showThomson"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.seed = Math.round(state.seed); state.eventCount = Math.round(state.eventCount / 100) * 100; state.dragging = false; render(); }
  [[R.target, "targetZ"], [R.energy, "energyMeV"], [R.impact, "impactFm"], [R.maxImpact, "maxImpactFm"], [R.events, "eventCount"], [R.radius, "atomRadiusFm"], [R.seed, "seed"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.asymptote, "showAsymptote"], [R.closest, "showClosest"], [R.eventToggle, "showEvents"], [R.thomson, "showThomson"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.materials.forEach(button => button.addEventListener("click", () => { state.targetZ = +button.dataset.z; render(); })); R.tabs.forEach(button => button.addEventListener("click", () => setMode(button.dataset.mode))); R.route.forEach((button, index) => button.addEventListener("click", () => { state.guideStep = index; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const active = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(active)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(); state.impactFm = clamp(Math.abs((box.height / 2 - (event.clientY - box.top)) / (box.height / 2) * 300), 1, 300); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.rutherfordLab = { scatter: next => M.scatter(next), differentialCrossSection: (angle, next) => M.differentialCrossSection(angle, next), thomsonAngle: next => M.thomsonAngle(next), eventAngles: (next, count) => M.eventAngles(next, count), expectedFractionAbove: (angle, next) => M.expectedFractionAbove(angle, next), trajectory: next => M.trajectory(next), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
