(function () {
  "use strict";
  const M = window.SingleSlitModel;
  if (!M) throw new Error("SingleSlitModel is required");
  const MODES = { width: ["中央亮纹", "测量中央亮纹两侧首暗纹之间的距离"], huygens: ["子波相消", "用缝内连续子波的振幅矢量解释暗纹"], limit: ["近似边界", "比较精确暗纹位置与小角近似的适用范围"], photon: ["单光子", "观察离散落点如何累积为 sinc² 概率分布"] };
  const STEPS = [["先找暗纹", "从中央向外移动探针，第一处光强为零的位置满足什么关系？"], ["再看子波", "一级暗纹处，缝内各点到观察点的相位为何正好覆盖 2π？"], ["最后改孔径", "减小缝宽后，中央亮纹为什么会展宽而不是变窄？"]];
  const state = { mode: "width", wavelengthNm: 600, slitWidthMm: .06, screenDistanceM: 1.2, probeMm: 0, guideStep: 0, showWaves: true, showMinima: true, showPhasors: true, showPhotons: true, photonCount: 0, photonSeed: 17, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("singleSlitCanvas"), profile: $("intensityChart"), secondary: $("secondaryChart"), wavelength: $("wavelengthInput"), width: $("widthInput"), distance: $("distanceInput"), probe: $("probeInput"), wavelengthValue: $("wavelengthValue"), widthValue: $("widthValue"), distanceValue: $("distanceValue"), probeValue: $("probeValue"), waves: $("showWavesToggle"), minima: $("showMinimaToggle"), phasors: $("showPhasorsToggle"), photons: $("showPhotonsToggle"), photonCount: $("photonCount"), first: $("firstMetric"), central: $("centralMetric"), angle: $("angleMetric"), path: $("pathMetric"), intensity: $("intensityMetric"), error: $("errorMetric"), nature: $("natureText"), explanation: $("explanationText"), badge: $("stateBadge"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), profileStatus: $("profileStatus"), secondaryKicker: $("secondaryKicker"), secondaryTitle: $("secondaryTitle"), secondaryStatus: $("secondaryStatus"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), one: $("onePhotonButton"), burst: $("burstButton"), clear: $("clearButton"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), pctx = R.profile.getContext("2d"), sctx = R.secondary.getContext("2d");
  const C = { bg: "#070c0e", grid: "rgba(220,230,226,.055)", cyan: "#64c7d9", amber: "#f2bd52", violet: "#b58ce5", green: "#79d992", red: "#ff786e", text: "#aab3ad", muted: "#707b75" };
  const clamp = M.clamp;
  const fmt = (value, digits = 3) => Number(value).toFixed(digits).replace("-", "−");
  function color() { const hue = 270 - (state.wavelengthNm - 380) / 370 * 270; return `hsl(${hue} 80% 66%)`; }
  function size(canvas, context, minHeight = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minHeight, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, stroke, width = 1, dash = []) { k.save(); k.strokeStyle = stroke; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, fill = C.text, px = 9, align = "left", weight = 600) { k.fillStyle = fill; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function background(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 15; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 15; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function scaleFor(d, height) { return Math.min(5.2, (height * .42) / (d.firstMinimumMm * 4.5)); }
  function drawMain() {
    const s = size(R.main, ctx, 280), d = M.derived(state), wave = color(), cy = s.height / 2, sourceX = 45, slitX = s.width * .36, screenX = s.width - 38, scale = scaleFor(d, s.height), mapY = mm => cy - mm * scale;
    background(ctx, s.width, s.height); text(ctx, "单色平面波", 18, 22, wave); text(ctx, "观察屏", screenX, 22, C.text, 9, "center");
    for (let x = sourceX; x < slitX - 8; x += 25) line(ctx, x, 28, x, s.height - 28, wave, 1, [3, 5]);
    const visualHalf = clamp(12 + (state.slitWidthMm - .01) / .19 * 34, 12, 46); line(ctx, slitX, 20, slitX, cy - visualHalf, C.text, 6); line(ctx, slitX, cy + visualHalf, slitX, s.height - 20, C.text, 6); text(ctx, `a=${fmt(state.slitWidthMm, 3)} mm`, slitX, cy - visualHalf - 10, C.amber, 9, "center");
    if (state.showWaves) for (let radius = 25; radius < screenX - slitX; radius += 34) { ctx.strokeStyle = `${wave.replace("hsl", "hsl")}`; ctx.globalAlpha = .18; ctx.beginPath(); ctx.arc(slitX, cy, radius, -1.05, 1.05); ctx.stroke(); ctx.globalAlpha = 1; }
    line(ctx, screenX, 20, screenX, s.height - 20, "rgba(220,230,226,.32)", 3);
    const span = d.firstMinimumMm * 4.5;
    for (let yy = -span; yy <= span; yy += span / 120) { const intensity = M.intensityAt(yy, state).intensity, py = mapY(yy); ctx.fillStyle = wave; ctx.globalAlpha = .03 + .92 * Math.sqrt(intensity); ctx.fillRect(screenX - 8, py - 2, 16, 4); } ctx.globalAlpha = 1;
    if (state.showMinima) M.minima(state, 4).forEach(item => [-1, 1].forEach(sign => { const py = mapY(sign * item.positionMm); line(ctx, screenX - 18, py, screenX + 18, py, C.violet, 1); text(ctx, `${sign < 0 ? "−" : "+"}${item.order}`, screenX - 22, py + 3, C.violet, 8, "right"); }));
    const probeY = mapY(state.probeMm); line(ctx, slitX, cy, screenX, probeY, C.cyan, 1, [6, 5]); ctx.fillStyle = C.amber; ctx.beginPath(); ctx.arc(screenX, probeY, 7, 0, Math.PI * 2); ctx.fill(); text(ctx, `y=${fmt(state.probeMm, 2)} mm`, screenX - 12, clamp(probeY - 10, 18, s.height - 10), C.amber, 9, "right");
    if (state.mode === "photon" && state.showPhotons && state.photonCount) { const hits = M.photonHits(state, Math.min(state.photonCount, 1200), state.photonSeed); hits.forEach((hit, index) => { const py = mapY(hit), jitter = ((index * 37) % 19) - 9; ctx.fillStyle = wave; ctx.globalAlpha = .22 + (index % 5) * .12; ctx.fillRect(screenX - 13 + jitter, py, 2, 2); }); ctx.globalAlpha = 1; }
    text(ctx, state.mode === "photon" ? "单次落点局域，大量事件显现概率分布" : "拖动观察屏上的探针", 18, s.height - 14, C.muted, 8);
  }
  function axes(k, s, xmin, xmax, ymin, ymax, pad = { l: 38, r: 14, t: 18, b: 28 }) { const x = value => pad.l + (value - xmin) / (xmax - xmin) * (s.width - pad.l - pad.r), y = value => s.height - pad.b - (value - ymin) / (ymax - ymin) * (s.height - pad.t - pad.b); line(k, pad.l, pad.t, pad.l, s.height - pad.b, "rgba(220,230,226,.28)"); line(k, pad.l, y(0), s.width - pad.r, y(0), "rgba(220,230,226,.28)"); return { x, y, pad }; }
  function drawProfile() { const s = size(R.profile, pctx), d = M.derived(state), span = d.firstMinimumMm * 4.5, values = M.profile(state, span, 241); background(pctx, s.width, s.height); const a = axes(pctx, s, -span, span, 0, 1.06); pctx.strokeStyle = color(); pctx.lineWidth = 2; pctx.beginPath(); values.forEach((v, i) => i ? pctx.lineTo(a.x(v.probeMm), a.y(v.intensity)) : pctx.moveTo(a.x(v.probeMm), a.y(v.intensity))); pctx.stroke(); if (state.showMinima) M.minima(state, 4).forEach(item => [-1, 1].forEach(sign => line(pctx, a.x(sign * item.positionMm), a.y(0), a.x(sign * item.positionMm), a.y(1), "rgba(181,140,229,.35)", 1, [3, 4]))); const q = M.intensityAt(state.probeMm, state); pctx.fillStyle = C.amber; pctx.beginPath(); pctx.arc(a.x(state.probeMm), a.y(q.intensity), 5, 0, Math.PI * 2); pctx.fill(); text(pctx, "I/I₀", 7, 13, C.cyan); text(pctx, "y/mm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawPhasor() { const s = size(R.secondary, sctx), ph = M.phasors(state, 48); background(sctx, s.width, s.height); const scale = Math.min(s.width, s.height) * .34, ox = s.width * .46, oy = s.height * .52; if (state.showPhasors) ph.vectors.forEach((v, index) => line(sctx, ox + v.x * scale, oy - v.y * scale, ox + (v.x + v.dx) * scale, oy - (v.y + v.dy) * scale, index % 6 ? C.violet : C.amber, 1.5)); line(sctx, ox, oy, ox + ph.resultant.x * scale, oy - ph.resultant.y * scale, C.green, 3); text(sctx, `相位跨度 ${fmt(ph.phaseSpan / Math.PI, 2)}π`, 14, 18, C.violet); text(sctx, `合振幅 ${fmt(ph.resultant.magnitude, 3)} A₀`, 14, s.height - 12, C.green); }
  function drawLimit() { const s = size(R.secondary, sctx); background(sctx, s.width, s.height); const widths = Array.from({ length: 80 }, (_, i) => .01 + .19 * i / 79), points = widths.map(width => M.derived({ ...state, slitWidthMm: width })), ymax = Math.max(...points.map(v => v.centralWidthMm)) * 1.04, a = axes(sctx, s, .01, .2, 0, ymax); [["exact", C.amber], ["approx", C.cyan]].forEach(([kind, stroke]) => { sctx.strokeStyle = stroke; sctx.lineWidth = 2; sctx.beginPath(); points.forEach((v, i) => { const y = kind === "exact" ? v.centralWidthMm : v.approximateCentralWidthMm; i ? sctx.lineTo(a.x(widths[i]), a.y(y)) : sctx.moveTo(a.x(widths[i]), a.y(y)); }); sctx.stroke(); }); text(sctx, "精确", 12, 16, C.amber); text(sctx, "小角近似", 48, 16, C.cyan); text(sctx, "a/mm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawPhotons() { const s = size(R.secondary, sctx), d = M.derived(state), span = d.firstMinimumMm * 5, bins = 54, counts = Array(bins).fill(0), hits = M.photonHits(state, Math.min(state.photonCount, 5000), state.photonSeed); hits.forEach(hit => { const index = Math.floor((hit + span) / (2 * span) * bins); if (index >= 0 && index < bins) counts[index] += 1; }); background(sctx, s.width, s.height); const max = Math.max(1, ...counts), bar = s.width / bins; counts.forEach((count, i) => { sctx.fillStyle = color(); sctx.globalAlpha = .25 + .7 * count / max; sctx.fillRect(i * bar, s.height - 22 - count / max * (s.height - 42), Math.max(1, bar - 1), count / max * (s.height - 42)); }); sctx.globalAlpha = 1; text(sctx, `${hits.length} 个离散事件`, 12, 16, C.cyan); }
  function drawSecondary() { if (state.mode === "limit") drawLimit(); else if (state.mode === "photon") drawPhotons(); else drawPhasor(); }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - +el.min) / (+el.max - +el.min) * 100}%`); }
  function render() { const d = M.derived(state), atCenter = Math.abs(state.probeMm) < d.firstMinimumMm * .08, minimum = d.isMinimum; R.wavelengthValue.textContent = `${fmt(state.wavelengthNm, 0)} nm`; R.widthValue.textContent = `${fmt(state.slitWidthMm, 3)} mm`; R.distanceValue.textContent = `${fmt(state.screenDistanceM, 2)} m`; R.probeValue.textContent = `${fmt(state.probeMm, 2)} mm`; [[R.wavelength, state.wavelengthNm], [R.width, state.slitWidthMm], [R.distance, state.screenDistanceM], [R.probe, state.probeMm]].forEach(v => range(v[0], v[1])); R.first.textContent = `${fmt(d.firstMinimumMm)} mm`; R.central.textContent = `${fmt(d.centralWidthMm)} mm`; R.angle.textContent = `${fmt(d.thetaDeg)}°`; R.path.textContent = `${fmt(d.pathEdgeWaves)} λ`; R.intensity.textContent = fmt(d.intensity); R.error.textContent = `${fmt(d.approximationErrorPercent)}%`; R.nature.textContent = minimum ? `${d.nearestMinimumOrder} 级暗纹` : atCenter ? "中央主极大" : "次级亮区或过渡区"; R.explanation.textContent = minimum ? `缝边程差≈${d.nearestMinimumOrder}λ，子波相消` : atCenter ? "所有子波同相叠加" : "连续子波未完全闭合"; R.badge.textContent = minimum ? `暗纹 · m=${d.nearestMinimumOrder}` : atCenter ? "中央主极大" : `I/I₀=${fmt(d.intensity)}`; R.badge.className = `state-badge${minimum ? " is-minimum" : ""}`; R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.profileStatus.textContent = `中央亮纹宽 ${fmt(d.centralWidthMm, 2)} mm`; R.secondaryKicker.textContent = state.mode === "limit" ? "EXACT VS APPROX" : state.mode === "photon" ? "PHOTON HISTOGRAM" : "PHASOR SUM"; R.secondaryTitle.textContent = state.mode === "limit" ? "精确宽度与小角近似" : state.mode === "photon" ? "单光子落点统计" : "缝内子波振幅矢量和"; R.secondaryStatus.textContent = state.mode === "limit" ? `误差 ${fmt(d.approximationErrorPercent)}%` : state.mode === "photon" ? `${state.photonCount} 次探测` : `|A|/A₀=${fmt(Math.sqrt(d.intensity))}`; R.photonCount.textContent = `${state.photonCount} 次探测`; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = minimum ? `a sinθ=${d.nearestMinimumOrder}λ` : state.mode === "limit" ? "yₘ=L tan[arcsin(mλ/a)]" : "I/I₀=(sinα/α)²"; R.tabs.forEach(button => button.classList.toggle("is-active", button.dataset.mode === state.mode)); R.route.forEach((button, index) => button.classList.toggle("is-active", index === state.guideStep)); drawMain(); drawProfile(); drawSecondary(); }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "width") state.probeMm = 0; if (mode === "huygens") state.probeMm = M.derived(state).firstMinimumMm; if (mode === "limit") Object.assign(state, { slitWidthMm: .012, probeMm: 0 }); if (mode === "photon" && !state.photonCount) state.photonCount = 100; render(); }
  function reset() { Object.assign(state, { mode: "width", wavelengthNm: 600, slitWidthMm: .06, screenDistanceM: 1.2, probeMm: 0, guideStep: 0, showWaves: true, showMinima: true, showPhasors: true, showPhotons: true, photonCount: 0, photonSeed: 17, dragging: false }); [[R.waves, "showWaves"], [R.minima, "showMinima"], [R.phasors, "showPhasors"], [R.photons, "showPhotons"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { if (MODES[next.mode]) state.mode = next.mode; [["wavelengthNm", 380, 750], ["slitWidthMm", .005, .3], ["screenDistanceM", .2, 3], ["probeMm", -160, 160], ["guideStep", 0, 2], ["photonCount", 0, 10000], ["photonSeed", 1, 1e9]].forEach(([key, min, max]) => { if (Number.isFinite(+next[key])) state[key] = clamp(+next[key], min, max); }); ["showWaves", "showMinima", "showPhasors", "showPhotons"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.wavelength, "wavelengthNm"], [R.width, "slitWidthMm"], [R.distance, "screenDistanceM"], [R.probe, "probeMm"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.waves, "showWaves"], [R.minima, "showMinima"], [R.phasors, "showPhasors"], [R.photons, "showPhotons"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(button => button.addEventListener("click", () => setMode(button.dataset.mode))); R.route.forEach((button, index) => button.addEventListener("click", () => { state.guideStep = index; render(); })); R.one.addEventListener("click", () => { state.photonCount += 1; state.mode = "photon"; render(); }); R.burst.addEventListener("click", () => { state.photonCount = Math.min(10000, state.photonCount + 100); state.mode = "photon"; render(); }); R.clear.addEventListener("click", () => { state.photonCount = 0; render(); }); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const active = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(active)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(), d = M.derived(state), scale = scaleFor(d, box.height), cy = box.height / 2; state.probeMm = clamp((cy - (event.clientY - box.top)) / scale, -100, 100); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.singleSlitLab = { derived: next => M.derived(next), intensityAt: (y, next) => M.intensityAt(y, next), minima: next => M.minima(next), phasors: next => M.phasors(next), photonHits: (next, count, seed) => M.photonHits(next, count, seed), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
