(function () {
  "use strict";
  const M = window.ThinFilmModel;
  if (!M) throw new Error("ThinFilmModel is required");
  const MODES = { soap: ["肥皂膜", "判断两次反射的相位突变如何改变明暗条件"], coating: ["增透膜", "同时匹配振幅和相位，使设计波长的反射趋近于零"], wedge: ["空气劈尖", "沿厚度梯度读取等厚干涉条纹与接触暗纹"], color: ["白光色膜", "观察不同波长被选择性反射后形成的综合色彩"] };
  const STEPS = [["先数相位突变", "两次反射分别从光疏到光密还是从光密到光疏？"], ["再算往返光程", "传播相位 4πnt cosθ₁/λ 与界面相位如何共同决定明暗？"], ["最后叠加振幅", "为什么增透条件不仅要求相位相反，还要求两束反射振幅接近？"]];
  const soapAngleDeg = 25;
  const soapThicknessNm = 600 / (4 * 1.33 * Math.cos(Math.asin(Math.sin(soapAngleDeg * Math.PI / 180) / 1.33)));
  const state = { mode: "soap", wavelengthNm: 600, thicknessNm: soapThicknessNm, incidentIndex: 1, filmIndex: 1.33, substrateIndex: 1, incidenceDeg: soapAngleDeg, polarization: "unpolarized", wedgeSlopeUrad: 120, positionMm: 4, guideStep: 0, showRays: true, showPhase: true, showMultiple: true, showSpectrum: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("filmCanvas"), spectrum: $("spectrumChart"), secondary: $("secondaryChart"), wavelength: $("wavelengthInput"), thickness: $("thicknessInput"), film: $("filmInput"), substrate: $("substrateInput"), angle: $("angleInput"), position: $("positionInput"), slope: $("slopeInput"), wavelengthValue: $("wavelengthValue"), thicknessValue: $("thicknessValue"), filmValue: $("filmValue"), substrateValue: $("substrateValue"), angleValue: $("angleValue"), positionValue: $("positionValue"), slopeValue: $("slopeValue"), rays: $("showRaysToggle"), phase: $("showPhaseToggle"), multiple: $("showMultipleToggle"), spectrumToggle: $("showSpectrumToggle"), refraction: $("refractionMetric"), path: $("pathMetric"), phaseMetric: $("phaseMetric"), reflectance: $("reflectanceMetric"), top: $("topMetric"), bottom: $("bottomMetric"), nature: $("natureText"), explanation: $("explanationText"), badge: $("stateBadge"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), dragHint: $("dragHint"), spectrumStatus: $("spectrumStatus"), secondaryKicker: $("secondaryKicker"), secondaryTitle: $("secondaryTitle"), secondaryStatus: $("secondaryStatus"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), spctx = R.spectrum.getContext("2d"), sectx = R.secondary.getContext("2d");
  const C = { bg: "#070c0e", grid: "rgba(220,230,226,.055)", cyan: "#64c7d9", amber: "#f2bd52", violet: "#b58ce5", green: "#79d992", red: "#ff786e", text: "#aab3ad", muted: "#707b75" };
  const clamp = M.clamp;
  const fmt = (value, digits = 3) => Number(value).toFixed(digits).replace("-", "−");
  function wavelengthRgb(wavelength) { let r = 0, g = 0, b = 0; if (wavelength < 440) { r = -(wavelength - 440) / 60; b = 1; } else if (wavelength < 490) { g = (wavelength - 440) / 50; b = 1; } else if (wavelength < 510) { g = 1; b = -(wavelength - 510) / 20; } else if (wavelength < 580) { r = (wavelength - 510) / 70; g = 1; } else if (wavelength < 645) { r = 1; g = -(wavelength - 645) / 65; } else r = 1; const factor = wavelength < 420 ? .35 + .65 * (wavelength - 380) / 40 : wavelength > 700 ? .35 + .65 * (750 - wavelength) / 50 : 1; return [r, g, b].map(v => Math.round(255 * Math.max(0, v) * factor)); }
  function waveColor(wavelength = state.wavelengthNm, alpha = 1) { const rgb = wavelengthRgb(wavelength); return `rgba(${rgb.join(",")},${alpha})`; }
  function filmColor() { const spectrum = M.spectrum(state, 75); let r = 0, g = 0, b = 0, total = 0; spectrum.forEach(point => { const rgb = wavelengthRgb(point.wavelengthNm), weight = point.reflectance; r += rgb[0] * weight; g += rgb[1] * weight; b += rgb[2] * weight; total += weight; }); const scale = total ? Math.min(2.8, 45 / total) : 0; return `rgb(${Math.min(255, Math.round(r * scale / 75))},${Math.min(255, Math.round(g * scale / 75))},${Math.min(255, Math.round(b * scale / 75))})`; }
  function size(canvas, context, minHeight = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minHeight, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, stroke, width = 1, dash = []) { k.save(); k.strokeStyle = stroke; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, fill = C.text, px = 9, align = "left", weight = 600) { k.fillStyle = fill; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 15; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 15; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, stroke, label) { line(k, x1, y1, x2, y2, stroke, 2.5); const angle = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = stroke; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 8 * Math.cos(angle - .45), y2 - 8 * Math.sin(angle - .45)); k.lineTo(x2 - 8 * Math.cos(angle + .45), y2 - 8 * Math.sin(angle + .45)); k.fill(); if (label) text(k, label, x2 + 6, y2 - 5, stroke, 9); }
  function drawLayer() { const s = size(R.main, ctx, 280), d = M.derived(state), wave = waveColor(), center = s.width * .5, top = s.height * .42, visualThickness = 28 + state.thicknessNm / 1200 * 90; bg(ctx, s.width, s.height); ctx.fillStyle = state.mode === "color" ? filmColor() : "rgba(100,199,217,.16)"; ctx.fillRect(28, top, s.width - 56, visualThickness); ctx.fillStyle = "rgba(170,184,178,.16)"; ctx.fillRect(28, top + visualThickness, s.width - 56, s.height - top - visualThickness - 25); line(ctx, 28, top, s.width - 28, top, C.cyan, 2); line(ctx, 28, top + visualThickness, s.width - 28, top + visualThickness, C.violet, 2); text(ctx, `n₀=${fmt(state.incidentIndex, 2)}`, 38, top - 18, C.text); text(ctx, `膜 n₁=${fmt(state.filmIndex, 2)} · t=${fmt(state.thicknessNm, 1)}nm`, 38, top + 18, C.cyan); text(ctx, `基底 n₂=${fmt(state.substrateIndex, 2)}`, 38, top + visualThickness + 22, C.text);
    if (state.showRays) { const dx = 90 * Math.sin(d.theta0), entryX = center, startX = center - dx, startY = 32; arrow(ctx, startX, startY, entryX, top, wave, "入射"); arrow(ctx, entryX, top, center + dx, 34, wave, "R₁"); const filmDx = visualThickness * Math.tan(d.theta1); line(ctx, entryX, top, entryX + filmDx, top + visualThickness, wave, 2); line(ctx, entryX + filmDx, top + visualThickness, entryX + 2 * filmDx, top, wave, 2); arrow(ctx, entryX + 2 * filmDx, top, entryX + 2 * filmDx + dx, 34, wave, "R₂"); if (state.showMultiple) for (let i = 1; i <= 3; i += 1) { const offset = i * 2 * filmDx + i * 16; line(ctx, entryX + offset, top, entryX + offset + filmDx, top + visualThickness, waveColor(state.wavelengthNm, .18), 1); line(ctx, entryX + offset + filmDx, top + visualThickness, entryX + offset + 2 * filmDx, top, waveColor(state.wavelengthNm, .18), 1); } }
    if (state.showPhase) { text(ctx, d.topPhaseFlip ? "上界面 +π" : "上界面 0", s.width - 38, top - 9, d.topPhaseFlip ? C.amber : C.muted, 9, "right"); text(ctx, d.bottomPhaseFlip ? "下界面 +π" : "下界面 0", s.width - 38, top + visualThickness + 14, d.bottomPhaseFlip ? C.amber : C.muted, 9, "right"); }
    text(ctx, "上下拖动界面改变膜厚", 22, s.height - 12, C.muted, 8);
  }
  function drawWedge() { const s = size(R.main, ctx, 280), d = M.derived(state), left = 34, right = s.width - 34, top = s.height * .34, bottom = s.height * .68; bg(ctx, s.width, s.height); ctx.fillStyle = "rgba(180,194,188,.15)"; ctx.fillRect(left, top - 35, right - left, 35); ctx.fillRect(left, bottom, right - left, 42); ctx.fillStyle = "rgba(100,199,217,.1)"; ctx.beginPath(); ctx.moveTo(left, top); ctx.lineTo(right, bottom); ctx.lineTo(left, bottom); ctx.closePath(); ctx.fill(); line(ctx, left, top, right, bottom, C.cyan, 2); line(ctx, left, bottom, right, bottom, C.violet, 2); const samples = 180; for (let i = 0; i < samples; i += 1) { const xRatio = i / (samples - 1), xMm = xRatio * 20, thicknessNm = xMm * 1e-3 * state.wedgeSlopeUrad * 1e-6 * 1e9, value = M.reflectance({ ...state, thicknessNm }).reflectance; ctx.fillStyle = waveColor(state.wavelengthNm, .05 + Math.min(.95, value * 12)); ctx.fillRect(left + xRatio * (right - left), bottom + 6, (right - left) / samples + 1, 30); } const px = left + state.positionMm / 20 * (right - left), py = top + state.positionMm / 20 * (bottom - top); line(ctx, px, py - 20, px, bottom + 45, C.amber, 2); ctx.fillStyle = C.amber; ctx.beginPath(); ctx.arc(px, py, 6, 0, Math.PI * 2); ctx.fill(); text(ctx, `x=${fmt(state.positionMm, 2)}mm`, px, py - 26, C.amber, 9, "center"); text(ctx, `局部 t=${fmt(d.localThicknessNm, 1)}nm`, px, bottom + 58, C.amber, 9, "center"); text(ctx, `条纹间距≈${fmt(d.wedgeSpacingMm, 3)}mm`, 22, 22, C.cyan); text(ctx, "左右拖动探针读取等厚条纹", 22, s.height - 12, C.muted, 8); }
  function drawMain() { state.mode === "wedge" ? drawWedge() : drawLayer(); }
  function axes(k, s, xmin, xmax, ymin, ymax) { const p = { l: 40, r: 14, t: 18, b: 28 }, x = v => p.l + (v - xmin) / (xmax - xmin) * (s.width - p.l - p.r), y = v => s.height - p.b - (v - ymin) / (ymax - ymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(220,230,226,.28)"); line(k, p.l, y(0), s.width - p.r, y(0), "rgba(220,230,226,.28)"); return { x, y, p }; }
  function drawSpectrum() { const s = size(R.spectrum, spctx), values = M.spectrum(state, 161), max = Math.max(.06, ...values.map(v => v.reflectance)) * 1.08, a = axes(spctx, s, 380, 750, 0, max); bg(spctx, s.width, s.height); if (state.showSpectrum) values.forEach((v, i) => { const next = values[i + 1]; if (!next) return; line(spctx, a.x(v.wavelengthNm), a.y(v.reflectance), a.x(next.wavelengthNm), a.y(next.reflectance), waveColor(v.wavelengthNm), 2); }); const current = M.reflectance(state); line(spctx, a.x(state.wavelengthNm), a.y(0), a.x(state.wavelengthNm), a.y(current.reflectance), C.amber, 1, [4, 4]); spctx.fillStyle = C.amber; spctx.beginPath(); spctx.arc(a.x(state.wavelengthNm), a.y(current.reflectance), 5, 0, Math.PI * 2); spctx.fill(); text(spctx, "R", 8, 13, C.cyan); text(spctx, "λ/nm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawThickness() { const s = size(R.secondary, sectx), values = M.thicknessSweep(state, 201, 1200), max = Math.max(.05, ...values.map(v => v.reflectance)) * 1.08, a = axes(sectx, s, 0, 1200, 0, max); bg(sectx, s.width, s.height); sectx.strokeStyle = C.violet; sectx.lineWidth = 2; sectx.beginPath(); values.forEach((v, i) => i ? sectx.lineTo(a.x(v.thicknessNm), a.y(v.reflectance)) : sectx.moveTo(a.x(v.thicknessNm), a.y(v.reflectance))); sectx.stroke(); const d = M.reflectance(state); sectx.fillStyle = C.amber; sectx.beginPath(); sectx.arc(a.x(state.thicknessNm), a.y(d.reflectance), 5, 0, Math.PI * 2); sectx.fill(); text(sectx, "R", 8, 13, C.violet); text(sectx, "t/nm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawWedgeChart() { const s = size(R.secondary, sectx), a = axes(sectx, s, 0, 20, 0, .2); bg(sectx, s.width, s.height); sectx.strokeStyle = C.cyan; sectx.lineWidth = 2; sectx.beginPath(); for (let i = 0; i <= 240; i += 1) { const x = 20 * i / 240, thicknessNm = x * 1e-3 * state.wedgeSlopeUrad * 1e-6 * 1e9, value = M.reflectance({ ...state, thicknessNm }).reflectance; i ? sectx.lineTo(a.x(x), a.y(value)) : sectx.moveTo(a.x(x), a.y(value)); } sectx.stroke(); const d = M.derived(state); sectx.fillStyle = C.amber; sectx.beginPath(); sectx.arc(a.x(state.positionMm), a.y(d.localReflectance), 5, 0, Math.PI * 2); sectx.fill(); text(sectx, "R(x)", 8, 13, C.cyan); text(sectx, "x/mm", s.width - 8, s.height - 6, C.muted, 8, "right"); }
  function drawSecondary() { state.mode === "wedge" ? drawWedgeChart() : drawThickness(); }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - +el.min) / (+el.max - +el.min) * 100}%`); }
  function render() { const d = M.derived(state), dark = d.reflectance < .002, strong = d.reflectance > .05; document.body.classList.toggle("wedge-mode", state.mode === "wedge"); [[R.wavelength, state.wavelengthNm], [R.thickness, state.thicknessNm], [R.film, state.filmIndex], [R.substrate, state.substrateIndex], [R.angle, state.incidenceDeg], [R.position, state.positionMm], [R.slope, state.wedgeSlopeUrad]].forEach(([el, value]) => range(el, value)); R.wavelengthValue.textContent = `${fmt(state.wavelengthNm, 0)} nm`; R.thicknessValue.textContent = `${fmt(state.thicknessNm, 1)} nm`; R.filmValue.textContent = fmt(state.filmIndex); R.substrateValue.textContent = fmt(state.substrateIndex); R.angleValue.textContent = `${fmt(state.incidenceDeg, 1)}°`; R.positionValue.textContent = `${fmt(state.positionMm, 2)} mm`; R.slopeValue.textContent = `${fmt(state.wedgeSlopeUrad, 0)} μrad`; R.refraction.textContent = `${fmt(d.theta1 * 180 / Math.PI)}°`; R.path.textContent = `${fmt(d.opticalPathNm, 1)} nm`; R.phaseMetric.textContent = `${fmt(d.wrappedPhaseRad / Math.PI, 2)}π`; R.reflectance.textContent = `${fmt(100 * (state.mode === "wedge" ? d.localReflectance : d.reflectance), 2)}%`; R.top.textContent = d.topPhaseFlip ? "+π" : "0"; R.bottom.textContent = d.bottomPhaseFlip ? "+π" : "0"; R.nature.textContent = state.mode === "wedge" ? d.localReflectance < .002 ? "接近暗纹" : "等厚亮区或过渡区" : dark ? "反射接近相消" : strong ? "反射增强" : "部分相消"; R.explanation.textContent = state.mode === "coating" ? "四分之一波厚度与折射率匹配共同增透" : state.mode === "wedge" ? "厚度随位置线性变化" : d.topPhaseFlip === d.bottomPhaseFlip ? "两界面相变相同，明暗由传播相位决定" : "一次半波损失改变明暗条件"; R.badge.textContent = state.mode === "wedge" ? `局部 R=${fmt(100 * d.localReflectance, 2)}%` : `反射率 ${fmt(100 * d.reflectance, 2)}%`; R.badge.className = `state-badge${dark ? " is-dark" : ""}`; R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.dragHint.textContent = state.mode === "wedge" ? "左右拖动劈尖探针" : "上下拖动界面改变膜厚"; R.spectrumStatus.textContent = state.mode === "color" ? `综合色 ${filmColor()}` : `选中 ${fmt(state.wavelengthNm, 0)} nm`; R.secondaryKicker.textContent = state.mode === "wedge" ? "EQUAL-THICKNESS FRINGES" : "THICKNESS RESPONSE"; R.secondaryTitle.textContent = state.mode === "wedge" ? "反射率—劈尖位置" : "反射率—膜厚"; R.secondaryStatus.textContent = state.mode === "wedge" ? `Δx=${fmt(d.wedgeSpacingMm, 3)}mm` : `t=${fmt(state.thicknessNm, 1)}nm`; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = state.mode === "wedge" ? "Δx≈λ/(2nγ cosθ₁)" : dark ? "r总≈0" : "Δφ=4πnt cosθ₁/λ+Δφ反射"; R.tabs.forEach(button => button.classList.toggle("is-active", button.dataset.mode === state.mode)); R.route.forEach((button, index) => button.classList.toggle("is-active", index === state.guideStep)); drawMain(); drawSpectrum(); drawSecondary(); }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "soap") Object.assign(state, { wavelengthNm: 600, thicknessNm: soapThicknessNm, incidentIndex: 1, filmIndex: 1.33, substrateIndex: 1, incidenceDeg: soapAngleDeg }); if (mode === "coating") { const q = M.idealQuarterWave(550, 1.5); Object.assign(state, { wavelengthNm: 550, thicknessNm: q.thicknessNm, incidentIndex: 1, filmIndex: q.filmIndex, substrateIndex: 1.5, incidenceDeg: 0 }); } if (mode === "wedge") Object.assign(state, { wavelengthNm: 550, thicknessNm: 0, incidentIndex: 1.5, filmIndex: 1, substrateIndex: 1.5, incidenceDeg: 0, wedgeSlopeUrad: 100, positionMm: 4 }); if (mode === "color") Object.assign(state, { wavelengthNm: 550, thicknessNm: 420, incidentIndex: 1, filmIndex: 1.4, substrateIndex: 1.52, incidenceDeg: 20 }); render(); }
  function reset() { Object.assign(state, { mode: "soap", wavelengthNm: 600, thicknessNm: soapThicknessNm, incidentIndex: 1, filmIndex: 1.33, substrateIndex: 1, incidenceDeg: soapAngleDeg, polarization: "unpolarized", wedgeSlopeUrad: 120, positionMm: 4, guideStep: 0, showRays: true, showPhase: true, showMultiple: true, showSpectrum: true, dragging: false }); [[R.rays, "showRays"], [R.phase, "showPhase"], [R.multiple, "showMultiple"], [R.spectrumToggle, "showSpectrum"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { if (MODES[next.mode]) state.mode = next.mode; [["wavelengthNm", 380, 750], ["thicknessNm", 0, 2000], ["incidentIndex", 1, 2.6], ["filmIndex", 1, 2.4], ["substrateIndex", 1, 2.6], ["incidenceDeg", 0, 75], ["wedgeSlopeUrad", 10, 1000], ["positionMm", 0, 20], ["guideStep", 0, 2]].forEach(([key, min, max]) => { if (Number.isFinite(+next[key])) state[key] = clamp(+next[key], min, max); }); ["showRays", "showPhase", "showMultiple", "showSpectrum"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); if (["s", "p", "unpolarized"].includes(next.polarization)) state.polarization = next.polarization; state.dragging = false; render(); }
  [[R.wavelength, "wavelengthNm"], [R.thickness, "thicknessNm"], [R.film, "filmIndex"], [R.substrate, "substrateIndex"], [R.angle, "incidenceDeg"], [R.position, "positionMm"], [R.slope, "wedgeSlopeUrad"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.rays, "showRays"], [R.phase, "showPhase"], [R.multiple, "showMultiple"], [R.spectrumToggle, "showSpectrum"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(button => button.addEventListener("click", () => setMode(button.dataset.mode))); R.route.forEach((button, index) => button.addEventListener("click", () => { state.guideStep = index; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const active = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(active)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(); if (state.mode === "wedge") state.positionMm = clamp((event.clientX - box.left) / box.width * 20, 0, 20); else state.thicknessNm = clamp((event.clientY - box.top) / box.height * 1200, 0, 1200); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.thinFilmLab = { derived: next => M.derived(next), reflectance: (next, wavelength) => M.reflectance(next, wavelength), spectrum: next => M.spectrum(next), idealQuarterWave: M.idealQuarterWave, getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
