(function () {
  "use strict";
  const M = window.ThreeFieldModel;
  if (!M) throw new Error("ThreeFieldModel is required");
  const MODES = { straight: ["三力直线平衡", "什么速度能让重力、电场力和磁场力恰好平衡"], cycloid: ["旋轮线漂移", "圆周分运动怎样叠加成沿水平方向漂移的旋轮线"], projectile: ["关磁场边界", "磁场撤去后为什么轨迹退化为恒加速度类抛体"], circle: ["重电平衡圆周", "电场力平衡重力后为什么只剩匀速圆周运动"] };
  const STEPS = [["先列三种力", "三种力分别沿什么方向，哪一种与速度有关？"], ["再拆漂移与回旋", "导引中心速度与相对圆周速度怎样合成？"], ["最后核功和能", "为什么磁场力改变轨迹却始终不改变动能？"]];
  const state = { mode: "straight", massPg: 1, chargeFc: 1, electricVm: 19.6, magneticT: 1, initialVxMs: 9.8, initialVyMs: 0, initialXM: 0, initialYM: 0, gravity: 9.8, timeS: 5, guideStep: 0, showForces: true, showDrift: true, showTrail: true, showLedger: true, dragging: false };
  const $ = id => document.getElementById(id);
  const R = { main: $("trajectoryCanvas"), velocityChart: $("velocityChart"), energyChart: $("energyChart"), mass: $("massInput"), charge: $("chargeInput"), electric: $("electricInput"), magnetic: $("magneticInput"), vx: $("vxInput"), vy: $("vyInput"), time: $("timeInput"), massValue: $("massValue"), chargeValue: $("chargeValue"), electricValue: $("electricValue"), magneticValue: $("magneticValue"), vxValue: $("vxValue"), vyValue: $("vyValue"), timeValue: $("timeValue"), forces: $("showForcesToggle"), drift: $("showDriftToggle"), trail: $("showTrailToggle"), ledger: $("showLedgerToggle"), positionMetric: $("positionMetric"), velocityMetric: $("velocityMetric"), driftMetric: $("driftMetric"), forceMetric: $("forceMetric"), powerMetric: $("powerMetric"), residualMetric: $("residualMetric"), nature: $("natureText"), explanation: $("explanationText"), velocityStatus: $("velocityStatus"), energyStatus: $("energyStatus"), modeTitle: $("modeTitle"), modeGoal: $("modeGoal"), badge: $("stateBadge"), stepIndex: $("stepIndex"), stepTitle: $("stepTitle"), stepPrompt: $("stepPrompt"), formula: $("formulaReadout"), reset: $("resetButton"), guide: $("guideButton"), step: $("stepButton"), focus: $("focusButton"), fullscreen: $("fullscreenButton"), dialog: $("guideDialog"), tabs: [...document.querySelectorAll(".scene-tab[data-mode]")], route: [...document.querySelectorAll(".route-step")] };
  const ctx = R.main.getContext("2d"), vctx = R.velocityChart.getContext("2d"), ectx = R.energyChart.getContext("2d");
  const C = { bg: "#070b0c", grid: "rgba(223,229,223,.06)", cyan: "#64c7d9", amber: "#f0b951", green: "#79d992", red: "#ff786e", violet: "#b58ce5", text: "#a6b0a9", muted: "#717b75" };
  const clamp = (v, a, b) => Math.min(b, Math.max(a, Number(v)));
  const fmt = (v, d = 3) => Number.isFinite(v) ? Number(v).toFixed(d).replace("-", "−") : "∞";
  const input = extra => ({ ...state, ...(extra || {}) });
  function size(canvas, context, minH = 180) { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2), width = Math.max(280, Math.round(box.width)), height = Math.max(minH, Math.round(box.height)); if (canvas.width !== width * dpr || canvas.height !== height * dpr) { canvas.width = width * dpr; canvas.height = height * dpr; } context.setTransform(dpr, 0, 0, dpr, 0, 0); return { width, height }; }
  function line(k, x1, y1, x2, y2, color, width = 1, dash = []) { k.save(); k.strokeStyle = color; k.lineWidth = width; k.setLineDash(dash); k.beginPath(); k.moveTo(x1, y1); k.lineTo(x2, y2); k.stroke(); k.restore(); }
  function text(k, value, x, y, color = C.text, px = 10, align = "left", weight = 500) { k.fillStyle = color; k.font = `${weight} ${px}px ui-sans-serif,system-ui`; k.textAlign = align; k.fillText(value, x, y); }
  function bg(k, width, height) { k.fillStyle = C.bg; k.fillRect(0, 0, width, height); for (let x = 18; x < width; x += 42) line(k, x, 0, x, height, C.grid); for (let y = 18; y < height; y += 42) line(k, 0, y, width, y, C.grid); }
  function arrow(k, x1, y1, x2, y2, color, label) { line(k, x1, y1, x2, y2, color, 3); const a = Math.atan2(y2 - y1, x2 - x1); k.fillStyle = color; k.beginPath(); k.moveTo(x2, y2); k.lineTo(x2 - 9 * Math.cos(a - .5), y2 - 9 * Math.sin(a - .5)); k.lineTo(x2 - 9 * Math.cos(a + .5), y2 - 9 * Math.sin(a + .5)); k.fill(); if (label) text(k, label, x2 + 6, y2 - 6, color, 10, "left", 800); }
  function bounds(points) { const xs = points.map(p => p.xM), ys = points.map(p => p.yM), minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys); return { minX, maxX, minY, maxY, spanX: Math.max(2, maxX - minX), spanY: Math.max(2, maxY - minY) }; }
  function drawMain() {
    const s = size(R.main, ctx, 290), duration = Math.max(8, state.timeS), points = M.trajectory(input(), duration, 300), p = M.stateAt(state.timeS, input()), b = bounds(points), pad = 48, scale = Math.min((s.width - 2 * pad) / b.spanX, (s.height - 2 * pad) / b.spanY), x = value => pad + (value - b.minX) * scale + ((s.width - 2 * pad) - b.spanX * scale) / 2, y = value => s.height - pad - (value - b.minY) * scale - ((s.height - 2 * pad) - b.spanY * scale) / 2;
    bg(ctx, s.width, s.height); if (state.showTrail) { ctx.strokeStyle = C.cyan; ctx.lineWidth = 2; ctx.beginPath(); points.filter(v => v.timeS <= state.timeS + 1e-9).forEach((v, i) => i ? ctx.lineTo(x(v.xM), y(v.yM)) : ctx.moveTo(x(v.xM), y(v.yM))); ctx.stroke(); for (let i = 0; i <= 8; i += 1) { const q = M.stateAt(state.timeS * i / 8, input()); ctx.fillStyle = "rgba(100,199,217,.45)"; ctx.beginPath(); ctx.arc(x(q.xM), y(q.yM), 3, 0, Math.PI * 2); ctx.fill(); } }
    if (state.showField) {}
    const px = x(p.xM), py = y(p.yM); ctx.fillStyle = state.chargeFc >= 0 ? C.amber : C.violet; ctx.beginPath(); ctx.arc(px, py, 8, 0, Math.PI * 2); ctx.fill(); text(ctx, state.chargeFc >= 0 ? "+q" : "−q", px, py + 3, C.bg, 8, "center", 900);
    if (state.showDrift && Math.abs(p.omega) > 1e-10) arrow(ctx, px, py + 24, px + clamp(p.driftVxMs * 7, -90, 90), py + 24, C.green, "vd");
    if (state.showForces) { const unit = 5e16, fyE = p.electricForceN * unit, fyG = p.gravityForceN * unit, fxB = p.magneticForceXN * unit, fyB = p.magneticForceYN * unit; arrow(ctx, px, py, px, py - clamp(fyE, -80, 80), C.green, "qE"); arrow(ctx, px, py, px, py + clamp(fyG, 15, 80), C.amber, "mg"); if (Math.hypot(fxB, fyB) > 2) arrow(ctx, px, py, px + clamp(fxB, -80, 80), py - clamp(fyB, -80, 80), C.red, "qv×B"); }
    text(ctx, state.electricVm >= 0 ? "E ↑" : "E ↓", 22, 28, C.green, 10, "left", 800); text(ctx, state.magneticT >= 0 ? "B ⊙" : "B ⊗", s.width - 22, 28, C.cyan, 10, "right", 800); text(ctx, `t=${fmt(state.timeS, 2)} s`, 22, s.height - 20, C.text, 10); text(ctx, `v=${fmt(p.speedMs)} m/s`, s.width - 22, s.height - 20, C.cyan, 10, "right", 800);
  }
  function axes(k, s, xmax, ymin, ymax) { const p = { l: 44, r: 18, t: 20, b: 30 }, x = v => p.l + v / (xmax || 1) * (s.width - p.l - p.r), y = v => s.height - p.b - (v - ymin) / (ymax - ymin || 1) * (s.height - p.t - p.b); line(k, p.l, p.t, p.l, s.height - p.b, "rgba(223,229,223,.3)"); line(k, p.l, y(0), s.width - p.r, y(0), "rgba(223,229,223,.3)"); return { x, y, p }; }
  function drawCharts() {
    const p = M.stateAt(state.timeS, input()), series = M.trajectory(input(), 15, 240), all = series.flatMap(v => [v.vxMs, v.vyMs, v.driftVxMs]); let s = size(R.velocityChart, vctx); bg(vctx, s.width, s.height); const min = Math.min(-.1, ...all) * 1.1, max = Math.max(.1, ...all) * 1.1, a = axes(vctx, s, 15, min, max); [["vxMs", C.cyan], ["vyMs", C.violet], ["driftVxMs", C.green]].forEach(([key, color]) => { vctx.strokeStyle = color; vctx.lineWidth = 2; vctx.beginPath(); series.forEach((v, i) => i ? vctx.lineTo(a.x(v.timeS), a.y(v[key])) : vctx.moveTo(a.x(v.timeS), a.y(v[key]))); vctx.stroke(); }); line(vctx, a.x(state.timeS), a.p.t, a.x(state.timeS), s.height - a.p.b, C.amber, 1, [4, 4]); text(vctx, "vx", 8, 14, C.cyan, 9, "left", 800); text(vctx, "vy", 28, 14, C.violet, 9, "left", 800); text(vctx, "vd", 48, 14, C.green, 9, "left", 800);
    s = size(R.energyChart, ectx); bg(ectx, s.width, s.height); const values = state.showLedger ? [["ΔK", p.kineticChangeJ, C.cyan], ["WE", p.electricWorkJ, C.green], ["Wg", p.gravityWorkJ, C.amber], ["WB", p.magneticPowerW * state.timeS, C.red]] : [], scale = Math.max(1e-18, ...values.map(v => Math.abs(v[1]))), mid = s.width * .48; line(ectx, mid, 20, mid, s.height - 24, "rgba(223,229,223,.2)"); values.forEach((v, i) => { const yy = 42 + i * 40, width = Math.abs(v[1]) / scale * s.width * .34; text(ectx, v[0], 16, yy + 4, C.text, 9); ectx.fillStyle = v[2]; ectx.fillRect(v[1] < 0 ? mid - width : mid, yy - 8, width, 16); text(ectx, `${fmt(v[1] * 1e15, 3)} fJ`, s.width - 14, yy + 4, v[2], 9, "right", 800); });
  }
  function range(el, value) { el.value = value; el.style.setProperty("--range-progress", `${(value - Number(el.min)) / (Number(el.max) - Number(el.min)) * 100}%`); }
  function render() {
    const p = M.stateAt(state.timeS, input()), balanced = Math.hypot(p.netForceXN, p.netForceYN) < 1e-18, boundary = Math.abs(state.magneticT) < .01;
    R.modeTitle.textContent = MODES[state.mode][0]; R.modeGoal.textContent = MODES[state.mode][1]; R.badge.textContent = balanced ? "三力平衡，匀速直线" : boundary ? "磁耦合关闭，恒加速度" : state.mode === "circle" ? "导引中心静止，纯圆周" : "回旋叠加水平漂移"; R.badge.className = `state-badge ${balanced ? "is-balanced" : boundary ? "is-boundary" : ""}`;
    const fields = [[R.mass, state.massPg, R.massValue, "pg"], [R.charge, state.chargeFc, R.chargeValue, "fC"], [R.electric, state.electricVm, R.electricValue, "V/m"], [R.magnetic, state.magneticT, R.magneticValue, "T"], [R.vx, state.initialVxMs, R.vxValue, "m/s"], [R.vy, state.initialVyMs, R.vyValue, "m/s"], [R.time, state.timeS, R.timeValue, "s"]]; fields.forEach(([el, value, label, unit]) => { range(el, value); label.textContent = `${fmt(value, 2)} ${unit}`; });
    R.positionMetric.textContent = `(${fmt(p.xM, 2)}, ${fmt(p.yM, 2)}) m`; R.velocityMetric.textContent = `${fmt(p.speedMs)} m/s`; R.driftMetric.textContent = `${fmt(p.driftVxMs)} m/s`; R.forceMetric.textContent = `${fmt(p.netForceYN * 1e15)} fN`; R.powerMetric.textContent = `${fmt(p.magneticPowerW, 9)} W`; R.residualMetric.textContent = `${fmt(p.energyResidualJ, 9)} J`; R.nature.textContent = balanced ? "三力在竖直方向平衡" : boundary ? "只剩电场力与重力的恒合力" : state.mode === "circle" ? "qE=mg，磁场力提供向心力" : "导引中心匀速漂移"; R.explanation.textContent = balanced ? "qE−mg−qvB=0" : boundary ? "ay=qE/m−g" : state.mode === "circle" ? "qE=mg" : "v=vd+u"; R.velocityStatus.textContent = `t=${fmt(state.timeS, 2)}s · ω=${fmt(p.omega)}rad/s`; R.energyStatus.textContent = Math.abs(p.energyResidualJ) < 1e-24 && Math.abs(p.magneticPowerW) < 1e-24 ? "账本闭合" : "检查残差"; R.stepIndex.textContent = String(state.guideStep + 1).padStart(2, "0"); R.stepTitle.textContent = STEPS[state.guideStep][0]; R.stepPrompt.textContent = STEPS[state.guideStep][1]; R.formula.textContent = boundary ? "ay=qE/m−g" : state.mode === "circle" ? "qE=mg" : balanced ? "qE−mg−qvB=0" : "v=vd+u"; R.tabs.forEach(b => b.classList.toggle("is-active", b.dataset.mode === state.mode)); R.route.forEach((b, i) => b.classList.toggle("is-active", i === state.guideStep)); drawMain(); drawCharts();
  }
  function setMode(mode) { if (!MODES[mode]) return; state.mode = mode; if (mode === "straight") Object.assign(state, { massPg: 1, chargeFc: 1, electricVm: 19.6, magneticT: 1, initialVxMs: 9.8, initialVyMs: 0, initialXM: 0, initialYM: 0, timeS: 5 }); if (mode === "cycloid") Object.assign(state, { massPg: 1, chargeFc: 1, electricVm: 19.6, magneticT: 1, initialVxMs: 0, initialVyMs: 0, timeS: Math.PI * 1.5 }); if (mode === "projectile") Object.assign(state, { massPg: 1, chargeFc: 1, electricVm: 0, magneticT: 0, initialVxMs: 3, initialVyMs: 0, initialYM: 2, timeS: .5 }); if (mode === "circle") Object.assign(state, { massPg: 1, chargeFc: 1, electricVm: 9.8, magneticT: 1, initialVxMs: 2, initialVyMs: 0, initialXM: 0, initialYM: 0, timeS: Math.PI / 2 }); render(); }
  function reset() { Object.assign(state, { mode: "straight", massPg: 1, chargeFc: 1, electricVm: 19.6, magneticT: 1, initialVxMs: 9.8, initialVyMs: 0, initialXM: 0, initialYM: 0, gravity: 9.8, timeS: 5, guideStep: 0, showForces: true, showDrift: true, showTrail: true, showLedger: true, dragging: false }); [[R.forces, "showForces"], [R.drift, "showDrift"], [R.trail, "showTrail"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.checked = state[key]); render(); }
  function setState(next = {}) { const limits = { massPg: [.1, 10], chargeFc: [-5, 5], electricVm: [-50, 50], magneticT: [-3, 3], initialVxMs: [-20, 20], initialVyMs: [-20, 20], initialXM: [-20, 20], initialYM: [-20, 20], timeS: [0, 15] }; Object.entries(limits).forEach(([key, bounds]) => { if (Number.isFinite(+next[key])) state[key] = clamp(next[key], bounds[0], bounds[1]); }); if (MODES[next.mode]) state.mode = next.mode; if (Number.isFinite(+next.guideStep)) state.guideStep = clamp(Math.round(next.guideStep), 0, 2); ["showForces", "showDrift", "showTrail", "showLedger"].forEach(key => { if (typeof next[key] === "boolean") state[key] = next[key]; }); state.dragging = false; render(); }
  [[R.mass, "massPg"], [R.charge, "chargeFc"], [R.electric, "electricVm"], [R.magnetic, "magneticT"], [R.vx, "initialVxMs"], [R.vy, "initialVyMs"], [R.time, "timeS"]].forEach(([el, key]) => el.addEventListener("input", () => { state[key] = +el.value; render(); })); [[R.forces, "showForces"], [R.drift, "showDrift"], [R.trail, "showTrail"], [R.ledger, "showLedger"]].forEach(([el, key]) => el.addEventListener("change", () => { state[key] = el.checked; render(); })); R.tabs.forEach(b => b.addEventListener("click", () => setMode(b.dataset.mode))); R.route.forEach((b, i) => b.addEventListener("click", () => { state.guideStep = i; render(); })); R.reset.addEventListener("click", reset); R.guide.addEventListener("click", () => R.dialog.showModal()); R.step.addEventListener("click", () => { state.guideStep = (state.guideStep + 1) % 3; render(); }); R.focus.addEventListener("click", () => { const on = document.body.classList.toggle("focus-mode"); R.focus.setAttribute("aria-pressed", String(on)); }); R.fullscreen.addEventListener("click", () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen()); function drag(event) { const box = R.main.getBoundingClientRect(); state.timeS = clamp((event.clientX - box.left) / box.width * 15, 0, 15); render(); } R.main.addEventListener("pointerdown", event => { state.dragging = true; R.main.setPointerCapture?.(event.pointerId); drag(event); }); R.main.addEventListener("pointermove", event => { if (state.dragging) drag(event); }); R.main.addEventListener("pointerup", () => state.dragging = false); R.main.addEventListener("pointercancel", () => state.dragging = false); window.addEventListener("resize", render); window.threeFieldLab = { stateAt: (time, next) => M.stateAt(time, next), trajectory: (next, duration, count) => M.trajectory(next, duration, count), getState: () => ({ ...state }), setMode, setState, reset }; render();
})();
