(function () {
  const M = window.VerticalMotionModel;
  if (!M) throw new Error("VerticalMotionModel is required");
  const state = {
    mode:"vacuum",heightM:20,speedMs:20,gravity:9.8,massA:.2,massB:5,
    frameVelocity:3,dragMass:1,areaCm2:100,dragCoefficient:.47,
    progress:0,running:false,guideStep:0,showStrobe:true,showVectors:true,
    showGrid:true,showForces:true,dragging:false,
  };
  const $=(id)=>document.getElementById(id);
  const R={canvas:$("motionCanvas"),motionChart:$("motionChart"),evidenceChart:$("evidenceChart"),sceneTabs:[...document.querySelectorAll('.scene-tab[data-mode]')],routeSteps:[...document.querySelectorAll('.route-step')],presets:[...document.querySelectorAll('[data-preset]')],speedRow:$("speedRow"),vacuumSection:$("vacuumSection"),frameSection:$("frameSection"),dragSection:$("dragSection"),heightInput:$("heightInput"),speedInput:$("speedInput"),gravityInput:$("gravityInput"),massAInput:$("massAInput"),massBInput:$("massBInput"),frameVelocityInput:$("frameVelocityInput"),dragMassInput:$("dragMassInput"),areaInput:$("areaInput"),dragCoefficientInput:$("dragCoefficientInput"),timeInput:$("timeInput"),heightValue:$("heightValue"),speedValue:$("speedValue"),gravityValue:$("gravityValue"),massAValue:$("massAValue"),massBValue:$("massBValue"),frameVelocityValue:$("frameVelocityValue"),dragMassValue:$("dragMassValue"),areaValue:$("areaValue"),dragCoefficientValue:$("dragCoefficientValue"),playbackValue:$("playbackValue"),modeTitle:$("modeTitle"),modeGoal:$("modeGoal"),stateBadge:$("stateBadge"),stageHint:$("stageHint"),metricLabels:[1,2,3,4,5,6].map(n=>$("metric"+n+"Label")),metrics:[1,2,3,4,5,6].map(n=>$("metric"+n)),motionNature:$("motionNature"),motionExplanation:$("motionExplanation"),motionTitle:$("motionTitle"),motionStatus:$("motionStatus"),evidenceTitle:$("evidenceTitle"),evidenceStatus:$("evidenceStatus"),stepIndex:$("stepIndex"),stepTitle:$("stepTitle"),stepPrompt:$("stepPrompt"),formulaReadout:$("formulaReadout"),playButton:$("playButton"),pauseButton:$("pauseButton"),keyButton:$("keyButton"),resetButton:$("resetButton"),guideButton:$("guideButton"),stepButton:$("stepButton"),focusButton:$("focusButton"),fullscreenButton:$("fullscreenButton"),guideDialog:$("guideDialog"),showStrobeToggle:$("showStrobeToggle"),showVectorsToggle:$("showVectorsToggle"),showGridToggle:$("showGridToggle"),showForcesToggle:$("showForcesToggle")};
  const ctx=R.canvas.getContext('2d'),mctx=R.motionChart.getContext('2d'),ectx=R.evidenceChart.getContext('2d');
  const C={bg:'#090d0f',grid:'rgba(223,229,223,.055)',cyan:'#64c6d8',green:'#7ad798',amber:'#f0b951',red:'#ff786e',violet:'#b59ae5',white:'#dfe5df',muted:'#84908a'};
  const modes={vacuum:{title:'真空同落',goal:'改变两个物体的质量，检查真空中是否仍同时落地',hint:'拖动时间，比较两个物体的高度、速度和落地时刻'},throw:{title:'竖直上抛',goal:'定位最高点和同高度返回时刻，比较速度与加速度',hint:'暂停在最高点，确认 v=0 但 a=−g'},frame:{title:'参考系变换',goal:'比较地面系和匀速移动参考系中的位置与速度读数',hint:'改变参考系速度，观察相对速度改变而加速度不变'},drag:{title:'空气阻力',goal:'比较真空与二次阻力下落，观察终端速度怎样形成',hint:'改变质量和迎风面积，比较重力与阻力的竞争'}};
  const guide=[["先统一正方向","物体向下运动时，速度和加速度为什么都写成负值？"],["再比较关键时刻","最高点速度瞬时为零时，重力加速度是否也变为零？"],["最后检查边界","真空中质量无关的结论，为什么不能直接套到有空气阻力的情形？"]];
  function fmt(v,d=2){return Number(v).toFixed(d)}
  function signed(v,d=2){if(Math.abs(v)<10**(-d)/2)return fmt(0,d);return(v>0?'+':'−')+fmt(Math.abs(v),d)}
  function size(canvas,context){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),width=Math.max(300,Math.round(rect.width)),height=Math.max(170,Math.round(rect.height));if(canvas.width!==width*ratio||canvas.height!==height*ratio){canvas.width=width*ratio;canvas.height=height*ratio}context.setTransform(ratio,0,0,ratio,0,0);return{width,height}}
  function grid(context,width,height){context.fillStyle=C.bg;context.fillRect(0,0,width,height);context.strokeStyle=C.grid;context.lineWidth=1;for(let x=18;x<width;x+=42){context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke()}for(let y=18;y<height;y+=42){context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke()}}
  function text(context,value,x,y,color=C.white,font='10px ui-monospace,monospace',align='left'){context.fillStyle=color;context.font=font;context.textAlign=align;context.fillText(value,x,y)}
  function arrow(context,x1,y1,x2,y2,color,label=''){const a=Math.atan2(y2-y1,x2-x1);context.save();context.strokeStyle=context.fillStyle=color;context.lineWidth=2.3;context.beginPath();context.moveTo(x1,y1);context.lineTo(x2,y2);context.stroke();context.beginPath();context.moveTo(x2,y2);context.lineTo(x2-8*Math.cos(a-.48),y2-8*Math.sin(a-.48));context.lineTo(x2-8*Math.cos(a+.48),y2-8*Math.sin(a+.48));context.fill();if(label)text(context,label,x2+5,y2-4,color,'700 10px monospace');context.restore()}
  function current(){
    const vacuumDuration=M.landingTime({initialHeightM:state.heightM,initialVelocityMs:0,gravityMs2:state.gravity});
    const throwBase=M.verticalThrow({initialHeightM:state.heightM,initialSpeedMs:state.speedMs,gravityMs2:state.gravity,timeS:0});
    const frameDuration=throwBase.impactTimeS;
    const dragBase=M.quadraticDragDrop({heightM:state.heightM,massKg:state.dragMass,areaM2:state.areaCm2/1e4,dragCoefficient:state.dragCoefficient,gravityMs2:state.gravity,timeS:0});
    const duration=state.mode==='vacuum'?vacuumDuration:state.mode==='throw'||state.mode==='frame'?frameDuration:dragBase.impactTimeS;
    const timeS=state.progress*duration;
    const vacuum=M.freeFall({initialHeightM:state.heightM,gravityMs2:state.gravity,timeS});
    const thrown=M.verticalThrow({initialHeightM:state.heightM,initialSpeedMs:state.speedMs,gravityMs2:state.gravity,timeS});
    const frame=M.inertialFrame({initialHeightM:state.heightM,initialVelocityMs:state.speedMs,gravityMs2:state.gravity,timeS,frameVelocityMs:state.frameVelocity});
    const drag=M.quadraticDragDrop({heightM:state.heightM,massKg:state.dragMass,areaM2:state.areaCm2/1e4,dragCoefficient:state.dragCoefficient,gravityMs2:state.gravity,timeS});
    const vacuumAtDragTime=M.freeFall({initialHeightM:state.heightM,gravityMs2:state.gravity,timeS});
    return{duration,timeS,vacuum,thrown,frame,drag,vacuumAtDragTime,throwBase,dragBase};
  }
  function describe(q){
    if(state.mode==='throw'){
      const s=q.thrown,nearApex=Math.abs(s.velocityMs)<.2,returned=Math.abs(s.heightM-state.heightM)<.08&&s.timeS>s.apexTimeS+.05;
      return{badge:nearApex?'最高点 · v=0':returned?'返回原高度':s.velocityMs>0?'上升':'下降',cls:nearApex?'is-apex':'is-fall',labels:['运动时间 t','当前高度 y','竖直速度 v','竖直加速度 a','最高点时刻','返回原高度'],values:[fmt(s.timeS,3)+' s',fmt(s.heightM,3)+' m',signed(s.velocityMs,3)+' m/s','−'+fmt(s.gravityMs2,3)+' m/s²',fmt(s.apexTimeS,3)+' s',fmt(s.returnToLaunchTimeS,3)+' s'],nature:nearApex?'最高点速度为零，但重力加速度仍指向下方':returned?'返回同一高度时，速度与初速度等大反向':s.velocityMs>0?'物体向上运动，速度为正且逐渐减小':'物体向下运动，速度为负且大小增大',explanation:`yₘₐₓ=${fmt(s.apexHeightM,3)} m；同高度速度对称`,formula:nearApex?'v=0，a=−g≠0':'v=v₀−gt',motionTitle:'y-t 与 v-t 同步图',motionStatus:'抛物线 / 直线',evidenceTitle:'同高度速度对称',evidenceStatus:'v下=−v上'};
    }
    if(state.mode==='frame'){
      const s=q.frame;
      return{badge:`参考系 ${signed(state.frameVelocity,1)} m/s`,cls:'is-frame',labels:['运动时间 t','地面系高度 y','地面系速度 v','相对位置 y′','相对速度 v′','相对加速度 a′'],values:[fmt(s.timeS,3)+' s',fmt(s.heightM,3)+' m',signed(s.velocityMs,3)+' m/s',signed(s.relativeHeightM,3)+' m',signed(s.relativeVelocityMs,3)+' m/s','−'+fmt(s.gravityMs2,3)+' m/s²'],nature:'匀速参考系改变位置和速度读数，不改变加速度',explanation:`v′=v−vꜰ=${signed(s.relativeVelocityMs,3)} m/s`,formula:'a′=a=−g',motionTitle:'两参考系的位置读数',motionStatus:'曲率相同',evidenceTitle:'速度与加速度变换',evidenceStatus:'v′=v−vꜰ'};
    }
    if(state.mode==='drag'){
      const s=q.drag,ratio=s.terminalSpeedMs===Infinity?0:s.downwardSpeedMs/s.terminalSpeedMs,nearTerminal=ratio>.95;
      return{badge:state.dragCoefficient===0?'阻力关闭 · 真空':nearTerminal?'接近终端速度':'阻力正在增大',cls:'is-drag',labels:['运动时间 t','空气中高度 y','空气中速率 |v|','终端速度 vₜ','空气阻力 fᴅ','落地时间'],values:[fmt(s.timeS,3)+' s',fmt(s.heightM,3)+' m',fmt(s.downwardSpeedMs,3)+' m/s',s.terminalSpeedMs===Infinity?'∞':fmt(s.terminalSpeedMs,3)+' m/s',fmt(s.dragForceN,3)+' N',fmt(s.impactTimeS,3)+' s'],nature:state.dragCoefficient===0?'阻力为零，模型退化为真空自由落体':nearTerminal?'阻力接近重力，合力和加速度趋近零':'速度增加使二次阻力增大，下落加速度逐渐减小',explanation:`mg=${fmt(s.weightN,2)} N，fᴅ=${fmt(s.dragForceN,2)} N`,formula:'fᴅ=½ρCᴅAv²',motionTitle:'真空与空气中的速度',motionStatus:'终端速度边界',evidenceTitle:'重力与阻力账本',evidenceStatus:'ma=mg−fᴅ'};
    }
    const s=q.vacuum;
    return{badge:s.landed?'同时落地':'同时释放',cls:'is-fall',labels:['运动时间 t','当前高度 y','竖直速度 v','竖直加速度 a','落地时间','质量影响'],values:[fmt(s.timeS,3)+' s',fmt(s.heightM,3)+' m',signed(s.velocityMs,3)+' m/s','−'+fmt(s.gravityMs2,3)+' m/s²',fmt(s.impactTimeS,3)+' s','0'],nature:s.landed?'两个物体在同一时刻到达地面':'真空中两个物体具有相同的加速度',explanation:`mA=${fmt(state.massA,2)} kg，mB=${fmt(state.massB,2)} kg；y(t) 完全相同`,formula:'a=−g，与质量无关',motionTitle:'位置与速度时间图',motionStatus:'a=−g',evidenceTitle:'等时间隔频闪',evidenceStatus:'间距逐渐增大'};
  }
  function worldScale(q){const max=state.mode==='throw'||state.mode==='frame'?q.throwBase.apexHeightM:state.heightM;return Math.max(5,max*1.08)}
  function screenY(y,maxH,top,bottom){return bottom-(Math.max(0,Math.min(maxH,y))/maxH)*(bottom-top)}
  function ball(context,x,y,r,color,label){context.fillStyle=color;context.beginPath();context.arc(x,y,r,0,Math.PI*2);context.fill();context.strokeStyle='rgba(255,255,255,.45)';context.lineWidth=1;context.stroke();if(label)text(context,label,x,y-r-8,color,'700 10px sans-serif','center')}
  function ruler(width,height,maxH){if(!state.showGrid)return;const x=30,top=24,bottom=height-32;ctx.strokeStyle='rgba(223,229,223,.25)';ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();for(let i=0;i<=5;i++){const y=bottom-(bottom-top)*i/5;ctx.beginPath();ctx.moveTo(x-4,y);ctx.lineTo(x+5,y);ctx.stroke();text(ctx,fmt(maxH*i/5,0)+' m',x+9,y+3,C.muted,'9px monospace')}}
  function vectors(x,y,v,g){if(!state.showVectors)return;const vLen=Math.min(70,Math.abs(v)*3),aLen=Math.min(55,g*4);if(vLen>2)arrow(ctx,x,y,x,y-Math.sign(v)*vLen,C.cyan,'v');arrow(ctx,x+20,y-5,x+20,y-5+aLen,C.amber,'a')}
  function drawStrobes(input,x,maxH,top,bottom,color,duration){if(!state.showStrobe)return;const points=M.strobe({...input,endTimeS:duration},9);points.forEach((p,i)=>{ctx.fillStyle=color+(i===points.length-1?'aa':'38');ctx.beginPath();ctx.arc(x,screenY(p.heightM,maxH,top,bottom),i===points.length-1?4:2.5,0,Math.PI*2);ctx.fill()})}
  function drawVacuum(q,width,height){const maxH=worldScale(q),top=24,bottom=height-34;ctx.strokeStyle='#56615a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(48,bottom);ctx.lineTo(width-35,bottom);ctx.stroke();ruler(width,height,maxH);const xs=[width*.42,width*.7],masses=[state.massA,state.massB],colors=[C.cyan,C.violet];xs.forEach((x,i)=>{drawStrobes({initialHeightM:state.heightM,initialVelocityMs:0,gravityMs2:state.gravity},x,maxH,top,bottom,colors[i],q.vacuum.impactTimeS);const y=screenY(q.vacuum.heightM,maxH,top,bottom),r=8+Math.min(6,Math.log10(masses[i]+1)*6);ball(ctx,x,y,r,colors[i],`${fmt(masses[i],2)} kg`);vectors(x,y,q.vacuum.velocityMs,state.gravity)});text(ctx,'相同 y(t) · 相同 v(t) · 相同落地时刻',width/2,22,C.green,'700 11px sans-serif','center')}
  function drawThrow(q,width,height,frameView=false){const maxH=worldScale(q),top=24,bottom=height-34,cx=width*.58;ctx.strokeStyle='#56615a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(48,bottom);ctx.lineTo(width-35,bottom);ctx.stroke();ruler(width,height,maxH);drawStrobes({initialHeightM:state.heightM,initialVelocityMs:state.speedMs,gravityMs2:state.gravity},cx,maxH,top,bottom,C.violet,q.throwBase.impactTimeS);const s=q.thrown,y=screenY(s.heightM,maxH,top,bottom);ball(ctx,cx,y,11,C.violet,'球');vectors(cx,y,s.velocityMs,state.gravity);const launchY=screenY(state.heightM,maxH,top,bottom),apexY=screenY(s.apexHeightM,maxH,top,bottom);ctx.setLineDash([5,5]);ctx.strokeStyle='rgba(240,185,81,.45)';ctx.beginPath();ctx.moveTo(48,launchY);ctx.lineTo(width-35,launchY);ctx.moveTo(48,apexY);ctx.lineTo(width-35,apexY);ctx.stroke();ctx.setLineDash([]);text(ctx,'出发高度',width-42,launchY-6,C.muted,'9px sans-serif','right');text(ctx,'最高点',width-42,apexY-6,C.amber,'9px sans-serif','right');if(frameView)drawFrameInset(q,width,height)}
  function drawFrameInset(q,width,height){const boxW=Math.min(190,width*.34),boxH=92,x=48,y=height-130;ctx.fillStyle='rgba(181,154,229,.09)';ctx.strokeStyle=C.violet;ctx.lineWidth=2;ctx.fillRect(x,y,boxW,boxH);ctx.strokeRect(x,y,boxW,boxH);text(ctx,'匀速参考系',x+10,y+17,C.violet,'700 9px sans-serif');text(ctx,`y′=${signed(q.frame.relativeHeightM,2)} m`,x+10,y+42,C.white,'700 10px monospace');text(ctx,`v′=${signed(q.frame.relativeVelocityMs,2)} m/s`,x+10,y+62,C.white,'700 10px monospace');text(ctx,`a′=−${fmt(state.gravity,2)} m/s²`,x+10,y+82,C.amber,'700 10px monospace')}
  function drawDrag(q,width,height){const maxH=state.heightM*1.08,top=24,bottom=height-34;ctx.strokeStyle='#56615a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(48,bottom);ctx.lineTo(width-35,bottom);ctx.stroke();ruler(width,height,maxH);const lanes=[{x:width*.42,s:q.vacuumAtDragTime,color:C.cyan,label:'真空'},{x:width*.7,s:q.drag,color:C.red,label:'空气'}];lanes.forEach(l=>{const y=screenY(l.s.heightM,maxH,top,bottom);ball(ctx,l.x,y,11,l.color,l.label);const velocity=l.s.velocityMs;vectors(l.x,y,velocity,state.gravity)});if(state.showForces){const y=screenY(q.drag.heightM,maxH,top,bottom),x=width*.7;arrow(ctx,x+30,y,x+30,y+Math.min(65,q.drag.weightN*5),C.amber,'mg');if(q.drag.dragForceN>0)arrow(ctx,x-30,y,x-30,y-Math.min(65,q.drag.dragForceN*5),C.red,'fᴅ')}text(ctx,`空气落地 ${fmt(q.drag.impactTimeS,2)} s · 真空落地 ${fmt(q.vacuumAtDragTime.impactTimeS,2)} s`,width/2,22,C.white,'700 10px monospace','center')}
  function drawMain(q){const{width,height}=size(R.canvas,ctx);grid(ctx,width,height);if(state.mode==='vacuum')drawVacuum(q,width,height);else if(state.mode==='drag')drawDrag(q,width,height);else drawThrow(q,width,height,state.mode==='frame')}
  function axes(context,width,height,yLabel){const a={left:42,right:width-18,top:18,bottom:height-30};context.strokeStyle='rgba(223,229,223,.26)';context.beginPath();context.moveTo(a.left,a.top);context.lineTo(a.left,a.bottom);context.lineTo(a.right,a.bottom);context.stroke();text(context,yLabel,8,14,C.muted);text(context,'t',a.right,height-10,C.muted,'9px monospace','right');return a}
  function plot(context,pts,color,w=2){context.strokeStyle=color;context.lineWidth=w;context.beginPath();pts.forEach((p,i)=>i?context.lineTo(p.x,p.y):context.moveTo(p.x,p.y));context.stroke()}
  function sampleAt(q,p){const t=q.duration*p;if(state.mode==='drag')return{main:M.quadraticDragDrop({heightM:state.heightM,massKg:state.dragMass,areaM2:state.areaCm2/1e4,dragCoefficient:state.dragCoefficient,gravityMs2:state.gravity,timeS:t}),other:M.freeFall({initialHeightM:state.heightM,gravityMs2:state.gravity,timeS:t})};if(state.mode==='vacuum')return{main:M.freeFall({initialHeightM:state.heightM,gravityMs2:state.gravity,timeS:t})};return{main:M.verticalThrow({initialHeightM:state.heightM,initialSpeedMs:state.speedMs,gravityMs2:state.gravity,timeS:t})}}
  function drawMotionChart(q){const{width,height}=size(R.motionChart,mctx);grid(mctx,width,height);const a=axes(mctx,width,height,'归一化');const yPts=[],vPts=[],other=[];let maxH=state.mode==='throw'||state.mode==='frame'?q.throwBase.apexHeightM:state.heightM,maxV=Math.max(state.speedMs,state.gravity*q.duration,1);if(state.mode==='drag'&&q.drag.terminalSpeedMs!==Infinity)maxV=Math.max(maxV,q.drag.terminalSpeedMs);for(let i=0;i<=160;i++){const p=i/160,s=sampleAt(q,p),x=a.left+(a.right-a.left)*p;yPts.push({x,y:a.bottom-(s.main.heightM/maxH)*(a.bottom-a.top)});vPts.push({x,y:(a.top+a.bottom)/2-(s.main.velocityMs/maxV)*(a.bottom-a.top)*.43});if(s.other)other.push({x,y:(a.top+a.bottom)/2-(s.other.velocityMs/maxV)*(a.bottom-a.top)*.43})}plot(mctx,yPts,C.violet,2.2);plot(mctx,vPts,C.cyan,2.1);if(other.length)plot(mctx,other,C.amber,1.6);const cursor=a.left+(a.right-a.left)*state.progress;mctx.strokeStyle=C.white;mctx.setLineDash([3,4]);mctx.beginPath();mctx.moveTo(cursor,a.top);mctx.lineTo(cursor,a.bottom);mctx.stroke();mctx.setLineDash([]);text(mctx,'y',a.left+6,a.top+11,C.violet,'700 9px monospace');text(mctx,'v',a.left+25,a.top+11,C.cyan,'700 9px monospace');if(other.length)text(mctx,'v真空',a.left+43,a.top+11,C.amber,'700 9px monospace')}
  function drawEvidence(q){const{width,height}=size(R.evidenceChart,ectx);grid(ectx,width,height);if(state.mode==='drag'){const s=q.drag,max=Math.max(s.weightN,s.dragForceN,1),base=height-34,barW=(width-100)/2;[["重力 mg",s.weightN,C.amber,38],["空气阻力 fᴅ",s.dragForceN,C.red,58+barW]].forEach(([label,val,color,x])=>{ectx.fillStyle='rgba(255,255,255,.07)';ectx.fillRect(x,45,barW,100);ectx.fillStyle=color;const h=100*val/max;ectx.fillRect(x,145-h,barW,h);text(ectx,label,x+barW/2,163,color,'700 9px sans-serif','center');text(ectx,fmt(val,2)+' N',x+barW/2,33,C.white,'700 9px monospace','center')});text(ectx,`a↓=${fmt(s.accelerationDownMs2,3)} m/s²`,width/2,base,C.green,'700 10px monospace','center');return}
    if(state.mode==='frame'){const ground=q.frame.velocityMs,relative=q.frame.relativeVelocityMs,max=Math.max(Math.abs(ground),Math.abs(relative),1),cx=width/2,scale=(width*.36)/max;ectx.strokeStyle='rgba(255,255,255,.25)';ectx.beginPath();ectx.moveTo(cx,28);ectx.lineTo(cx,height-28);ectx.stroke();arrow(ectx,cx,68,cx+ground*scale,68,C.cyan,'v 地面系');arrow(ectx,cx,120,cx+relative*scale,120,C.violet,'v′ 移动系');arrow(ectx,cx,165,cx-state.gravity*Math.min(8,scale),165,C.amber,'a=a′=−g');return}
    const input=state.mode==='vacuum'?{initialHeightM:state.heightM,initialVelocityMs:0,gravityMs2:state.gravity}:{initialHeightM:state.heightM,initialVelocityMs:state.speedMs,gravityMs2:state.gravity};const points=M.strobe({...input,endTimeS:q.duration},9),left=35,right=width-22,base=height-30,maxH=state.mode==='throw'?q.throwBase.apexHeightM:state.heightM;points.forEach((p,i)=>{const x=left+(right-left)*i/(points.length-1),y=base-(p.heightM/maxH)*(height-55);ectx.fillStyle=i<=Math.floor(state.progress*8+.001)?C.cyan:'rgba(100,198,216,.25)';ectx.beginPath();ectx.arc(x,y,4,0,Math.PI*2);ectx.fill();text(ectx,fmt(p.timeS,1),x,height-12,C.muted,'8px monospace','center')});if(state.mode==='throw'){const up=q.throwBase.apexTimeS,down=q.throwBase.returnToLaunchTimeS-q.throwBase.apexTimeS;text(ectx,`上升 ${fmt(up,3)} s`,width*.28,22,C.violet,'700 9px monospace','center');text(ectx,`回到原高再用 ${fmt(down,3)} s`,width*.7,22,C.amber,'700 9px monospace','center')}else text(ectx,'相等时间间隔内，位移增量越来越大',width/2,22,C.white,'700 9px sans-serif','center')}
  function update(q){const d=describe(q),mode=modes[state.mode];R.modeTitle.textContent=mode.title;R.modeGoal.textContent=mode.goal;R.stageHint.textContent=mode.hint;R.stateBadge.textContent=d.badge;R.stateBadge.className='state-badge '+d.cls;d.labels.forEach((v,i)=>R.metricLabels[i].textContent=v);d.values.forEach((v,i)=>R.metrics[i].textContent=v);R.motionNature.textContent=d.nature;R.motionExplanation.textContent=d.explanation;R.formulaReadout.textContent=d.formula;R.motionTitle.textContent=d.motionTitle;R.motionStatus.textContent=d.motionStatus;R.evidenceTitle.textContent=d.evidenceTitle;R.evidenceStatus.textContent=d.evidenceStatus;R.heightValue.textContent=fmt(state.heightM,1)+' m';R.speedValue.textContent=fmt(state.speedMs,1)+' m/s';R.gravityValue.textContent=fmt(state.gravity,2)+' m/s²';R.massAValue.textContent=fmt(state.massA,2)+' kg';R.massBValue.textContent=fmt(state.massB,2)+' kg';R.frameVelocityValue.textContent=signed(state.frameVelocity,1)+' m/s';R.dragMassValue.textContent=fmt(state.dragMass,2)+' kg';R.areaValue.textContent=fmt(state.areaCm2,0)+' cm²';R.dragCoefficientValue.textContent=fmt(state.dragCoefficient,2);R.playbackValue.textContent=`${state.running?'运行中':'已暂停'} · ${fmt(q.timeS,2)} s`;R.timeInput.value=state.progress;const[t,p]=guide[state.guideStep];R.stepIndex.textContent=String(state.guideStep+1).padStart(2,'0');R.stepTitle.textContent=t;R.stepPrompt.textContent=p}
  function fill(input){const min=Number(input.min),max=Number(input.max),v=Number(input.value);input.style.setProperty('--range-progress',`${(v-min)/(max-min)*100}%`)}
  function render(){const q=current();update(q);drawMain(q);drawMotionChart(q);drawEvidence(q);document.querySelectorAll('input[type="range"]').forEach(fill)}
  function setMode(mode){state.mode=mode;R.sceneTabs.forEach(t=>t.classList.toggle('is-active',t.dataset.mode===mode));R.speedRow.hidden=mode==='vacuum'||mode==='drag';R.vacuumSection.hidden=mode!=='vacuum';R.frameSection.hidden=mode!=='frame';R.dragSection.hidden=mode!=='drag';render()}
  function sync(){R.heightInput.value=state.heightM;R.speedInput.value=state.speedMs;R.gravityInput.value=state.gravity;R.massAInput.value=state.massA;R.massBInput.value=state.massB;R.frameVelocityInput.value=state.frameVelocity;R.dragMassInput.value=state.dragMass;R.areaInput.value=state.areaCm2;R.dragCoefficientInput.value=state.dragCoefficient}
  function bind(input,key){input.addEventListener('input',()=>{state[key]=Number(input.value);render()})}
  bind(R.heightInput,'heightM');bind(R.speedInput,'speedMs');bind(R.gravityInput,'gravity');bind(R.massAInput,'massA');bind(R.massBInput,'massB');bind(R.frameVelocityInput,'frameVelocity');bind(R.dragMassInput,'dragMass');bind(R.areaInput,'areaCm2');bind(R.dragCoefficientInput,'dragCoefficient');R.timeInput.addEventListener('input',()=>{state.progress=Number(R.timeInput.value);state.running=false;render()});
  R.sceneTabs.forEach(t=>t.addEventListener('click',()=>setMode(t.dataset.mode)));R.routeSteps.forEach((b,i)=>b.addEventListener('click',()=>{state.guideStep=i;R.routeSteps.forEach((x,j)=>x.classList.toggle('is-active',i===j));render()}));R.presets.forEach(b=>b.addEventListener('click',()=>{if(b.dataset.preset==='release'){setMode('vacuum');state.progress=0}if(b.dataset.preset==='apex'){setMode('throw');const q=current();state.progress=q.throwBase.apexTimeS/q.throwBase.impactTimeS}if(b.dataset.preset==='return'){setMode('throw');const q=current();state.progress=Math.min(1,q.throwBase.returnToLaunchTimeS/q.throwBase.impactTimeS)}if(b.dataset.preset==='terminal'){setMode('drag');Object.assign(state,{heightM:120,dragMass:.2,areaCm2:1000,dragCoefficient:1,progress:.72})}state.running=false;sync();render()}));
  R.playButton.addEventListener('click',()=>{state.running=true;render()});R.pauseButton.addEventListener('click',()=>{state.running=false;render()});R.keyButton.addEventListener('click',()=>{if(state.mode==='throw'||state.mode==='frame'){const q=current(),points=[0,q.throwBase.apexTimeS/q.throwBase.impactTimeS,Math.min(1,q.throwBase.returnToLaunchTimeS/q.throwBase.impactTimeS),1];state.progress=points.find(p=>p>state.progress+.002)??0}else state.progress=state.progress<.5?1:0;state.running=false;render()});R.resetButton.addEventListener('click',()=>{Object.assign(state,{mode:'vacuum',heightM:20,speedMs:20,gravity:9.8,massA:.2,massB:5,frameVelocity:3,dragMass:1,areaCm2:100,dragCoefficient:.47,progress:0,running:false,guideStep:0});sync();setMode('vacuum')});R.stepButton.addEventListener('click',()=>{state.guideStep=(state.guideStep+1)%guide.length;R.routeSteps.forEach((x,j)=>x.classList.toggle('is-active',state.guideStep===j));render()});R.guideButton.addEventListener('click',()=>R.guideDialog.showModal());R.focusButton.addEventListener('click',()=>{const on=document.body.classList.toggle('focus-mode');R.focusButton.setAttribute('aria-pressed',String(on))});R.fullscreenButton.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()});[[R.showStrobeToggle,'showStrobe'],[R.showVectorsToggle,'showVectors'],[R.showGridToggle,'showGrid'],[R.showForcesToggle,'showForces']].forEach(([input,key])=>input.addEventListener('change',()=>{state[key]=input.checked;render()}));
  function pointerTime(e){const r=R.canvas.getBoundingClientRect();state.progress=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));state.running=false;render()}R.canvas.addEventListener('pointerdown',e=>{state.dragging=true;R.canvas.setPointerCapture?.(e.pointerId);pointerTime(e)});R.canvas.addEventListener('pointermove',e=>{if(state.dragging)pointerTime(e)});R.canvas.addEventListener('pointerup',()=>state.dragging=false);R.canvas.addEventListener('pointercancel',()=>state.dragging=false);window.addEventListener('resize',render);let previous=performance.now();function frame(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;if(state.running){state.progress=(state.progress+dt*.13)%1;render()}requestAnimationFrame(frame)}sync();setMode('vacuum');requestAnimationFrame(frame);
})();
